# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cortexdb/v1/admin.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'cortexdb/v1/admin.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ortexdb/v1/admin.proto\x12\x0b\x63ortexdb.v1\"\x0f\n\rHealthRequest\"\x1c\n\x0eHealthResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\"\r\n\x0bInfoRequest\"F\n\x0cInfoResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x0f\n\x07\x64\x62_path\x18\x02 \x01(\t\x12\x14\n\x0chas_embedder\x18\x03 \x01(\x08\x32\x8e\x01\n\x0c\x41\x64minService\x12\x41\n\x06Health\x12\x1a.cortexdb.v1.HealthRequest\x1a\x1b.cortexdb.v1.HealthResponse\x12;\n\x04Info\x12\x18.cortexdb.v1.InfoRequest\x1a\x19.cortexdb.v1.InfoResponseB4Z2github.com/liliang-cn/cortexdb/v2/pkg/rpc/v1;rpcv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cortexdb.v1.admin_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/liliang-cn/cortexdb/v2/pkg/rpc/v1;rpcv1'
  _globals['_HEALTHREQUEST']._serialized_start=40
  _globals['_HEALTHREQUEST']._serialized_end=55
  _globals['_HEALTHRESPONSE']._serialized_start=57
  _globals['_HEALTHRESPONSE']._serialized_end=85
  _globals['_INFOREQUEST']._serialized_start=87
  _globals['_INFOREQUEST']._serialized_end=100
  _globals['_INFORESPONSE']._serialized_start=102
  _globals['_INFORESPONSE']._serialized_end=172
  _globals['_ADMINSERVICE']._serialized_start=175
  _globals['_ADMINSERVICE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
