# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cortexdb_client._pb.cortexdb.v1 import graph_pb2 as cortexdb_dot_v1_dot_graph__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cortexdb/v1/graph_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KnowledgeGraphServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UpsertNamespace = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/UpsertNamespace',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.UpsertNamespaceRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.UpsertNamespaceResponse.FromString,
                _registered_method=True)
        self.ListNamespaces = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/ListNamespaces',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.ListNamespacesRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.ListNamespacesResponse.FromString,
                _registered_method=True)
        self.UpsertKnowledgeGraph = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/UpsertKnowledgeGraph',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.UpsertKnowledgeGraphRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.UpsertKnowledgeGraphResponse.FromString,
                _registered_method=True)
        self.FindKnowledgeGraph = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/FindKnowledgeGraph',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.FindKnowledgeGraphRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.FindKnowledgeGraphResponse.FromString,
                _registered_method=True)
        self.DeleteKnowledgeGraph = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/DeleteKnowledgeGraph',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.DeleteKnowledgeGraphRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.DeleteKnowledgeGraphResponse.FromString,
                _registered_method=True)
        self.ImportKnowledgeGraph = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/ImportKnowledgeGraph',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.ImportKnowledgeGraphRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.ImportKnowledgeGraphResponse.FromString,
                _registered_method=True)
        self.ExportKnowledgeGraph = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/ExportKnowledgeGraph',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.ExportKnowledgeGraphRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.ExportKnowledgeGraphResponse.FromString,
                _registered_method=True)
        self.QuerySparql = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/QuerySparql',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.QuerySparqlRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.QuerySparqlResponse.FromString,
                _registered_method=True)
        self.ValidateShacl = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/ValidateShacl',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.ValidateShaclRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.ValidateShaclResponse.FromString,
                _registered_method=True)
        self.RefreshInference = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/RefreshInference',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.RefreshInferenceRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.RefreshInferenceResponse.FromString,
                _registered_method=True)
        self.SummarizeInference = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/SummarizeInference',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.SummarizeInferenceRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.SummarizeInferenceResponse.FromString,
                _registered_method=True)
        self.ExplainInference = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/ExplainInference',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.ExplainInferenceRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.ExplainInferenceResponse.FromString,
                _registered_method=True)
        self.ExplainInferenceMatch = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/ExplainInferenceMatch',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.ExplainInferenceMatchRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.ExplainInferenceMatchResponse.FromString,
                _registered_method=True)
        self.SaveOntologySchema = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/SaveOntologySchema',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.SaveOntologySchemaRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.SaveOntologySchemaResponse.FromString,
                _registered_method=True)
        self.GetOntologySchema = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/GetOntologySchema',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.GetOntologySchemaRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.GetOntologySchemaResponse.FromString,
                _registered_method=True)
        self.ListOntologySchemas = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/ListOntologySchemas',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.ListOntologySchemasRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.ListOntologySchemasResponse.FromString,
                _registered_method=True)
        self.DeleteOntologySchema = channel.unary_unary(
                '/cortexdb.v1.KnowledgeGraphService/DeleteOntologySchema',
                request_serializer=cortexdb_dot_v1_dot_graph__pb2.DeleteOntologySchemaRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graph__pb2.DeleteOntologySchemaResponse.FromString,
                _registered_method=True)


class KnowledgeGraphServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def UpsertNamespace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListNamespaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertKnowledgeGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindKnowledgeGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteKnowledgeGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ImportKnowledgeGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExportKnowledgeGraph(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QuerySparql(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateShacl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SummarizeInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainInference(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExplainInferenceMatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SaveOntologySchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOntologySchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListOntologySchemas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteOntologySchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KnowledgeGraphServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UpsertNamespace': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertNamespace,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.UpsertNamespaceRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.UpsertNamespaceResponse.SerializeToString,
            ),
            'ListNamespaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListNamespaces,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.ListNamespacesRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.ListNamespacesResponse.SerializeToString,
            ),
            'UpsertKnowledgeGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertKnowledgeGraph,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.UpsertKnowledgeGraphRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.UpsertKnowledgeGraphResponse.SerializeToString,
            ),
            'FindKnowledgeGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.FindKnowledgeGraph,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.FindKnowledgeGraphRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.FindKnowledgeGraphResponse.SerializeToString,
            ),
            'DeleteKnowledgeGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteKnowledgeGraph,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.DeleteKnowledgeGraphRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.DeleteKnowledgeGraphResponse.SerializeToString,
            ),
            'ImportKnowledgeGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.ImportKnowledgeGraph,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.ImportKnowledgeGraphRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.ImportKnowledgeGraphResponse.SerializeToString,
            ),
            'ExportKnowledgeGraph': grpc.unary_unary_rpc_method_handler(
                    servicer.ExportKnowledgeGraph,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.ExportKnowledgeGraphRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.ExportKnowledgeGraphResponse.SerializeToString,
            ),
            'QuerySparql': grpc.unary_unary_rpc_method_handler(
                    servicer.QuerySparql,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.QuerySparqlRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.QuerySparqlResponse.SerializeToString,
            ),
            'ValidateShacl': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateShacl,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.ValidateShaclRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.ValidateShaclResponse.SerializeToString,
            ),
            'RefreshInference': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshInference,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.RefreshInferenceRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.RefreshInferenceResponse.SerializeToString,
            ),
            'SummarizeInference': grpc.unary_unary_rpc_method_handler(
                    servicer.SummarizeInference,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.SummarizeInferenceRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.SummarizeInferenceResponse.SerializeToString,
            ),
            'ExplainInference': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainInference,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.ExplainInferenceRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.ExplainInferenceResponse.SerializeToString,
            ),
            'ExplainInferenceMatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ExplainInferenceMatch,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.ExplainInferenceMatchRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.ExplainInferenceMatchResponse.SerializeToString,
            ),
            'SaveOntologySchema': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveOntologySchema,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.SaveOntologySchemaRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.SaveOntologySchemaResponse.SerializeToString,
            ),
            'GetOntologySchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOntologySchema,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.GetOntologySchemaRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.GetOntologySchemaResponse.SerializeToString,
            ),
            'ListOntologySchemas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListOntologySchemas,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.ListOntologySchemasRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.ListOntologySchemasResponse.SerializeToString,
            ),
            'DeleteOntologySchema': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteOntologySchema,
                    request_deserializer=cortexdb_dot_v1_dot_graph__pb2.DeleteOntologySchemaRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graph__pb2.DeleteOntologySchemaResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortexdb.v1.KnowledgeGraphService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cortexdb.v1.KnowledgeGraphService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KnowledgeGraphService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UpsertNamespace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/UpsertNamespace',
            cortexdb_dot_v1_dot_graph__pb2.UpsertNamespaceRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.UpsertNamespaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListNamespaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/ListNamespaces',
            cortexdb_dot_v1_dot_graph__pb2.ListNamespacesRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.ListNamespacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertKnowledgeGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/UpsertKnowledgeGraph',
            cortexdb_dot_v1_dot_graph__pb2.UpsertKnowledgeGraphRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.UpsertKnowledgeGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindKnowledgeGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/FindKnowledgeGraph',
            cortexdb_dot_v1_dot_graph__pb2.FindKnowledgeGraphRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.FindKnowledgeGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteKnowledgeGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/DeleteKnowledgeGraph',
            cortexdb_dot_v1_dot_graph__pb2.DeleteKnowledgeGraphRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.DeleteKnowledgeGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ImportKnowledgeGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/ImportKnowledgeGraph',
            cortexdb_dot_v1_dot_graph__pb2.ImportKnowledgeGraphRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.ImportKnowledgeGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExportKnowledgeGraph(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/ExportKnowledgeGraph',
            cortexdb_dot_v1_dot_graph__pb2.ExportKnowledgeGraphRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.ExportKnowledgeGraphResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QuerySparql(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/QuerySparql',
            cortexdb_dot_v1_dot_graph__pb2.QuerySparqlRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.QuerySparqlResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateShacl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/ValidateShacl',
            cortexdb_dot_v1_dot_graph__pb2.ValidateShaclRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.ValidateShaclResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/RefreshInference',
            cortexdb_dot_v1_dot_graph__pb2.RefreshInferenceRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.RefreshInferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SummarizeInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/SummarizeInference',
            cortexdb_dot_v1_dot_graph__pb2.SummarizeInferenceRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.SummarizeInferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/ExplainInference',
            cortexdb_dot_v1_dot_graph__pb2.ExplainInferenceRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.ExplainInferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExplainInferenceMatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/ExplainInferenceMatch',
            cortexdb_dot_v1_dot_graph__pb2.ExplainInferenceMatchRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.ExplainInferenceMatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SaveOntologySchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/SaveOntologySchema',
            cortexdb_dot_v1_dot_graph__pb2.SaveOntologySchemaRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.SaveOntologySchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOntologySchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/GetOntologySchema',
            cortexdb_dot_v1_dot_graph__pb2.GetOntologySchemaRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.GetOntologySchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListOntologySchemas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/ListOntologySchemas',
            cortexdb_dot_v1_dot_graph__pb2.ListOntologySchemasRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.ListOntologySchemasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteOntologySchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.KnowledgeGraphService/DeleteOntologySchema',
            cortexdb_dot_v1_dot_graph__pb2.DeleteOntologySchemaRequest.SerializeToString,
            cortexdb_dot_v1_dot_graph__pb2.DeleteOntologySchemaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
