# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cortexdb_client._pb.cortexdb.v1 import graphrag_pb2 as cortexdb_dot_v1_dot_graphrag__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cortexdb/v1/graphrag_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GraphRagServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InsertGraphDocument = channel.unary_unary(
                '/cortexdb.v1.GraphRagService/InsertGraphDocument',
                request_serializer=cortexdb_dot_v1_dot_graphrag__pb2.InsertGraphDocumentRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graphrag__pb2.InsertGraphDocumentResponse.FromString,
                _registered_method=True)
        self.SearchGraphRag = channel.unary_unary(
                '/cortexdb.v1.GraphRagService/SearchGraphRag',
                request_serializer=cortexdb_dot_v1_dot_graphrag__pb2.SearchGraphRagRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graphrag__pb2.SearchGraphRagResponse.FromString,
                _registered_method=True)
        self.InsertText = channel.unary_unary(
                '/cortexdb.v1.GraphRagService/InsertText',
                request_serializer=cortexdb_dot_v1_dot_graphrag__pb2.InsertTextRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graphrag__pb2.InsertTextResponse.FromString,
                _registered_method=True)
        self.InsertTextBatch = channel.unary_unary(
                '/cortexdb.v1.GraphRagService/InsertTextBatch',
                request_serializer=cortexdb_dot_v1_dot_graphrag__pb2.InsertTextBatchRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graphrag__pb2.InsertTextBatchResponse.FromString,
                _registered_method=True)
        self.SearchText = channel.unary_unary(
                '/cortexdb.v1.GraphRagService/SearchText',
                request_serializer=cortexdb_dot_v1_dot_graphrag__pb2.SearchTextRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graphrag__pb2.SearchTextResponse.FromString,
                _registered_method=True)
        self.HybridSearchText = channel.unary_unary(
                '/cortexdb.v1.GraphRagService/HybridSearchText',
                request_serializer=cortexdb_dot_v1_dot_graphrag__pb2.HybridSearchTextRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_graphrag__pb2.HybridSearchTextResponse.FromString,
                _registered_method=True)


class GraphRagServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def InsertGraphDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchGraphRag(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InsertTextBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HybridSearchText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GraphRagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InsertGraphDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertGraphDocument,
                    request_deserializer=cortexdb_dot_v1_dot_graphrag__pb2.InsertGraphDocumentRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graphrag__pb2.InsertGraphDocumentResponse.SerializeToString,
            ),
            'SearchGraphRag': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchGraphRag,
                    request_deserializer=cortexdb_dot_v1_dot_graphrag__pb2.SearchGraphRagRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graphrag__pb2.SearchGraphRagResponse.SerializeToString,
            ),
            'InsertText': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertText,
                    request_deserializer=cortexdb_dot_v1_dot_graphrag__pb2.InsertTextRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graphrag__pb2.InsertTextResponse.SerializeToString,
            ),
            'InsertTextBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.InsertTextBatch,
                    request_deserializer=cortexdb_dot_v1_dot_graphrag__pb2.InsertTextBatchRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graphrag__pb2.InsertTextBatchResponse.SerializeToString,
            ),
            'SearchText': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchText,
                    request_deserializer=cortexdb_dot_v1_dot_graphrag__pb2.SearchTextRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graphrag__pb2.SearchTextResponse.SerializeToString,
            ),
            'HybridSearchText': grpc.unary_unary_rpc_method_handler(
                    servicer.HybridSearchText,
                    request_deserializer=cortexdb_dot_v1_dot_graphrag__pb2.HybridSearchTextRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_graphrag__pb2.HybridSearchTextResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortexdb.v1.GraphRagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cortexdb.v1.GraphRagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GraphRagService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InsertGraphDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.GraphRagService/InsertGraphDocument',
            cortexdb_dot_v1_dot_graphrag__pb2.InsertGraphDocumentRequest.SerializeToString,
            cortexdb_dot_v1_dot_graphrag__pb2.InsertGraphDocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchGraphRag(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.GraphRagService/SearchGraphRag',
            cortexdb_dot_v1_dot_graphrag__pb2.SearchGraphRagRequest.SerializeToString,
            cortexdb_dot_v1_dot_graphrag__pb2.SearchGraphRagResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.GraphRagService/InsertText',
            cortexdb_dot_v1_dot_graphrag__pb2.InsertTextRequest.SerializeToString,
            cortexdb_dot_v1_dot_graphrag__pb2.InsertTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InsertTextBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.GraphRagService/InsertTextBatch',
            cortexdb_dot_v1_dot_graphrag__pb2.InsertTextBatchRequest.SerializeToString,
            cortexdb_dot_v1_dot_graphrag__pb2.InsertTextBatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.GraphRagService/SearchText',
            cortexdb_dot_v1_dot_graphrag__pb2.SearchTextRequest.SerializeToString,
            cortexdb_dot_v1_dot_graphrag__pb2.SearchTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HybridSearchText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.GraphRagService/HybridSearchText',
            cortexdb_dot_v1_dot_graphrag__pb2.HybridSearchTextRequest.SerializeToString,
            cortexdb_dot_v1_dot_graphrag__pb2.HybridSearchTextResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
