# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from cortexdb_client._pb.cortexdb.v1 import memory_pb2 as cortexdb_dot_v1_dot_memory__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cortexdb/v1/memory_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MemoryServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SaveMemory = channel.unary_unary(
                '/cortexdb.v1.MemoryService/SaveMemory',
                request_serializer=cortexdb_dot_v1_dot_memory__pb2.SaveMemoryRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_memory__pb2.SaveMemoryResponse.FromString,
                _registered_method=True)
        self.UpdateMemory = channel.unary_unary(
                '/cortexdb.v1.MemoryService/UpdateMemory',
                request_serializer=cortexdb_dot_v1_dot_memory__pb2.UpdateMemoryRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_memory__pb2.SaveMemoryResponse.FromString,
                _registered_method=True)
        self.GetMemory = channel.unary_unary(
                '/cortexdb.v1.MemoryService/GetMemory',
                request_serializer=cortexdb_dot_v1_dot_memory__pb2.GetMemoryRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_memory__pb2.GetMemoryResponse.FromString,
                _registered_method=True)
        self.SearchMemory = channel.unary_unary(
                '/cortexdb.v1.MemoryService/SearchMemory',
                request_serializer=cortexdb_dot_v1_dot_memory__pb2.SearchMemoryRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_memory__pb2.SearchMemoryResponse.FromString,
                _registered_method=True)
        self.DeleteMemory = channel.unary_unary(
                '/cortexdb.v1.MemoryService/DeleteMemory',
                request_serializer=cortexdb_dot_v1_dot_memory__pb2.DeleteMemoryRequest.SerializeToString,
                response_deserializer=cortexdb_dot_v1_dot_memory__pb2.DeleteMemoryResponse.FromString,
                _registered_method=True)


class MemoryServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def SaveMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMemory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MemoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SaveMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SaveMemory,
                    request_deserializer=cortexdb_dot_v1_dot_memory__pb2.SaveMemoryRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_memory__pb2.SaveMemoryResponse.SerializeToString,
            ),
            'UpdateMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMemory,
                    request_deserializer=cortexdb_dot_v1_dot_memory__pb2.UpdateMemoryRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_memory__pb2.SaveMemoryResponse.SerializeToString,
            ),
            'GetMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMemory,
                    request_deserializer=cortexdb_dot_v1_dot_memory__pb2.GetMemoryRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_memory__pb2.GetMemoryResponse.SerializeToString,
            ),
            'SearchMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchMemory,
                    request_deserializer=cortexdb_dot_v1_dot_memory__pb2.SearchMemoryRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_memory__pb2.SearchMemoryResponse.SerializeToString,
            ),
            'DeleteMemory': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMemory,
                    request_deserializer=cortexdb_dot_v1_dot_memory__pb2.DeleteMemoryRequest.FromString,
                    response_serializer=cortexdb_dot_v1_dot_memory__pb2.DeleteMemoryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cortexdb.v1.MemoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cortexdb.v1.MemoryService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MemoryService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SaveMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.MemoryService/SaveMemory',
            cortexdb_dot_v1_dot_memory__pb2.SaveMemoryRequest.SerializeToString,
            cortexdb_dot_v1_dot_memory__pb2.SaveMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.MemoryService/UpdateMemory',
            cortexdb_dot_v1_dot_memory__pb2.UpdateMemoryRequest.SerializeToString,
            cortexdb_dot_v1_dot_memory__pb2.SaveMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.MemoryService/GetMemory',
            cortexdb_dot_v1_dot_memory__pb2.GetMemoryRequest.SerializeToString,
            cortexdb_dot_v1_dot_memory__pb2.GetMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.MemoryService/SearchMemory',
            cortexdb_dot_v1_dot_memory__pb2.SearchMemoryRequest.SerializeToString,
            cortexdb_dot_v1_dot_memory__pb2.SearchMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMemory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cortexdb.v1.MemoryService/DeleteMemory',
            cortexdb_dot_v1_dot_memory__pb2.DeleteMemoryRequest.SerializeToString,
            cortexdb_dot_v1_dot_memory__pb2.DeleteMemoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
