# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cortexdb/v1/tools.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'cortexdb/v1/tools.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x63ortexdb/v1/tools.proto\x12\x0b\x63ortexdb.v1\"N\n\x0eToolDefinition\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x19\n\x11input_schema_json\x18\x03 \x01(\t\"\x12\n\x10ListToolsRequest\"?\n\x11ListToolsResponse\x12*\n\x05tools\x18\x01 \x03(\x0b\x32\x1b.cortexdb.v1.ToolDefinition\"2\n\x0f\x43\x61llToolRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\targs_json\x18\x02 \x01(\t\"\'\n\x10\x43\x61llToolResponse\x12\x13\n\x0bresult_json\x18\x01 \x01(\t2\xa3\x01\n\x0cToolsService\x12J\n\tListTools\x12\x1d.cortexdb.v1.ListToolsRequest\x1a\x1e.cortexdb.v1.ListToolsResponse\x12G\n\x08\x43\x61llTool\x12\x1c.cortexdb.v1.CallToolRequest\x1a\x1d.cortexdb.v1.CallToolResponseB4Z2github.com/liliang-cn/cortexdb/v2/pkg/rpc/v1;rpcv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cortexdb.v1.tools_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/liliang-cn/cortexdb/v2/pkg/rpc/v1;rpcv1'
  _globals['_TOOLDEFINITION']._serialized_start=40
  _globals['_TOOLDEFINITION']._serialized_end=118
  _globals['_LISTTOOLSREQUEST']._serialized_start=120
  _globals['_LISTTOOLSREQUEST']._serialized_end=138
  _globals['_LISTTOOLSRESPONSE']._serialized_start=140
  _globals['_LISTTOOLSRESPONSE']._serialized_end=203
  _globals['_CALLTOOLREQUEST']._serialized_start=205
  _globals['_CALLTOOLREQUEST']._serialized_end=255
  _globals['_CALLTOOLRESPONSE']._serialized_start=257
  _globals['_CALLTOOLRESPONSE']._serialized_end=296
  _globals['_TOOLSSERVICE']._serialized_start=299
  _globals['_TOOLSSERVICE']._serialized_end=462
# @@protoc_insertion_point(module_scope)
