package cortexdb

func KnowledgeMemoryFacadeToolDefinitions() []ToolDefinition {
	definitions := []ToolDefinition{
		{
			Name:        "knowledge_memory_remember",
			Mutates:     true,
			Description: "Store one episodic memory item in the CortexDB KnowledgeMemory facade. Prefer this over memory_save when you want to build a higher-level memory/knowledge workflow.",
			InputSchema: toolObjectSchema(
				[]string{"memory_id", "content"},
				map[string]any{
					"memory_id":   toolStringSchema("Stable memory ID."),
					"user_id":     toolStringSchema("Optional user ID for user-scoped memory."),
					"session_id":  toolStringSchema("Optional session ID for session-scoped memory."),
					"scope":       toolEnumSchema("Memory scope.", MemoryScopeGlobal, MemoryScopeUser, MemoryScopeSession),
					"namespace":   toolStringSchema("Optional memory namespace."),
					"role":        toolStringSchema("Optional message role."),
					"content":     toolStringSchema("Memory text content."),
					"metadata":    toolMapSchema("Optional metadata."),
					"importance":  toolNumberSchema("Optional importance score."),
					"ttl_seconds": toolIntegerSchema("Optional TTL in seconds."),
				},
			),
		},
		{
			Name:        "knowledge_memory_recall",
			Description: "Recall from the CortexDB KnowledgeMemory facade by fusing episodic memory, durable knowledge, graph expansion, and a packed context window.",
			InputSchema: toolObjectSchema(
				[]string{"query"},
				map[string]any{
					"query":                  toolStringSchema("Natural-language query or recall goal."),
					"user_id":                toolStringSchema("Optional user ID for memory recall."),
					"session_id":             toolStringSchema("Optional session ID for session-scoped memory recall."),
					"scope":                  toolEnumSchema("Optional memory scope.", MemoryScopeGlobal, MemoryScopeUser, MemoryScopeSession),
					"namespace":              toolStringSchema("Optional memory namespace."),
					"collection":             toolStringSchema("Optional knowledge collection."),
					"top_k_memories":         toolIntegerSchema("Maximum number of memory hits."),
					"top_k_knowledge":        toolIntegerSchema("Maximum number of knowledge hits."),
					"max_memory_items":       toolIntegerSchema("Maximum memory items included in the context pack."),
					"max_memory_chars":       toolIntegerSchema("Maximum character budget for memory context."),
					"keywords":               toolStringArraySchema("Expanded keywords, aliases, abbreviations, and synonyms."),
					"alternate_queries":      toolStringArraySchema("Alternate phrasings generated from the same goal."),
					"entity_names":           toolStringArraySchema("Structured entity hints."),
					"retrieval_mode":         toolEnumSchema("Preferred retrieval strategy.", RetrievalModeAuto, RetrievalModeLexical, RetrievalModeGraph),
					"disable_memory":         toolBooleanSchema("Skip episodic memory recall."),
					"disable_knowledge":      toolBooleanSchema("Skip durable knowledge recall."),
					"disable_graph":          toolBooleanSchema("Disable graph expansion."),
					"graph_light":            toolBooleanSchema("Enable lighter graph traversal defaults for lower latency."),
					"max_hops":               toolIntegerSchema("Graph expansion depth."),
					"max_related_chunks":     toolIntegerSchema("Maximum graph-expanded chunks."),
					"max_context_chunks":     toolIntegerSchema("Maximum chunks in final context."),
					"max_context_chars":      toolIntegerSchema("Maximum context character budget."),
					"per_document_limit":     toolIntegerSchema("Maximum chunks per document."),
					"max_expansion_seeds":    toolIntegerSchema("Optional cap on seed chunks expanded through the graph."),
					"max_traversal_nodes":    toolIntegerSchema("Optional cap on graph nodes inspected during expansion."),
					"max_entities_per_chunk": toolIntegerSchema("Optional cap on graph-derived entities attached to each chunk."),
					"plan":                   toolRetrievalPlanSchema("Optional structured retrieval plan."),
				},
			),
		},
		{
			Name:        "knowledge_memory_build_context_pack",
			Description: "Assemble a KnowledgeMemory context pack from memory, knowledge, and graph retrieval results. This returns the same fused retrieval diagnostics as knowledge_memory_recall, centered on prompt-ready context.",
			InputSchema: toolObjectSchema(
				[]string{"query"},
				map[string]any{
					"query":                  toolStringSchema("Natural-language query or planning goal."),
					"user_id":                toolStringSchema("Optional user ID for memory recall."),
					"session_id":             toolStringSchema("Optional session ID for session-scoped memory recall."),
					"scope":                  toolEnumSchema("Optional memory scope.", MemoryScopeGlobal, MemoryScopeUser, MemoryScopeSession),
					"namespace":              toolStringSchema("Optional memory namespace."),
					"collection":             toolStringSchema("Optional knowledge collection."),
					"top_k_memories":         toolIntegerSchema("Maximum number of memory hits."),
					"top_k_knowledge":        toolIntegerSchema("Maximum number of knowledge hits."),
					"max_memory_items":       toolIntegerSchema("Maximum memory items included in the context pack."),
					"max_memory_chars":       toolIntegerSchema("Maximum character budget for memory context."),
					"keywords":               toolStringArraySchema("Expanded keywords, aliases, abbreviations, and synonyms."),
					"alternate_queries":      toolStringArraySchema("Alternate phrasings generated from the same goal."),
					"entity_names":           toolStringArraySchema("Structured entity hints."),
					"retrieval_mode":         toolEnumSchema("Preferred retrieval strategy.", RetrievalModeAuto, RetrievalModeLexical, RetrievalModeGraph),
					"disable_memory":         toolBooleanSchema("Skip episodic memory recall."),
					"disable_knowledge":      toolBooleanSchema("Skip durable knowledge recall."),
					"disable_graph":          toolBooleanSchema("Disable graph expansion."),
					"graph_light":            toolBooleanSchema("Enable lighter graph traversal defaults for lower latency."),
					"max_hops":               toolIntegerSchema("Graph expansion depth."),
					"max_related_chunks":     toolIntegerSchema("Maximum graph-expanded chunks."),
					"max_context_chunks":     toolIntegerSchema("Maximum chunks in final context."),
					"max_context_chars":      toolIntegerSchema("Maximum context character budget."),
					"per_document_limit":     toolIntegerSchema("Maximum chunks per document."),
					"max_expansion_seeds":    toolIntegerSchema("Optional cap on seed chunks expanded through the graph."),
					"max_traversal_nodes":    toolIntegerSchema("Optional cap on graph nodes inspected during expansion."),
					"max_entities_per_chunk": toolIntegerSchema("Optional cap on graph-derived entities attached to each chunk."),
					"plan":                   toolRetrievalPlanSchema("Optional structured retrieval plan."),
				},
			),
		},
		{
			Name:        "knowledge_memory_promote_to_knowledge",
			Mutates:     true,
			Description: "Promote one or more memory items into durable knowledge, preserving source memory provenance.",
			InputSchema: toolObjectSchema(
				[]string{"memory_ids"},
				map[string]any{
					"memory_ids":    toolStringArraySchema("Memory IDs to promote."),
					"knowledge_id":  toolStringSchema("Optional stable knowledge ID."),
					"title":         toolStringSchema("Optional title."),
					"source_url":    toolStringSchema("Optional source URL."),
					"author":        toolStringSchema("Optional author."),
					"collection":    toolStringSchema("Optional chunk collection."),
					"chunk_size":    toolIntegerSchema("Optional chunk size in words."),
					"chunk_overlap": toolIntegerSchema("Optional chunk overlap in words."),
					"join_with":     toolStringSchema("Optional separator used to join source memories."),
					"metadata":      toolMapSchema("Optional metadata."),
					"entities":      toolEntityArraySchema(),
					"relations":     toolRelationArraySchema(),
				},
			),
		},
		{
			Name:        "knowledge_memory_expand_entity_context",
			Description: "Expand graph context around entities and assemble a context pack with related chunks.",
			InputSchema: toolObjectSchema(
				[]string{},
				map[string]any{
					"entity_ids":             toolStringArraySchema("Optional explicit entity node IDs."),
					"entity_names":           toolStringArraySchema("Optional entity names."),
					"max_hops":               toolIntegerSchema("Graph expansion depth."),
					"edge_types":             toolStringArraySchema("Optional edge type filter."),
					"node_types":             toolStringArraySchema("Optional node type filter."),
					"limit":                  toolIntegerSchema("Optional node result limit."),
					"top_k_chunks":           toolIntegerSchema("Maximum number of related chunks to load."),
					"max_context_chunks":     toolIntegerSchema("Maximum chunks in final context."),
					"max_context_chars":      toolIntegerSchema("Maximum context character budget."),
					"per_document_limit":     toolIntegerSchema("Maximum chunks per document."),
					"retrieval_mode":         toolEnumSchema("Preferred retrieval strategy for context packing.", RetrievalModeAuto, RetrievalModeLexical, RetrievalModeGraph),
					"disable_graph":          toolBooleanSchema("Disable graph-derived entity enrichment while packing context."),
					"graph_light":            toolBooleanSchema("Enable lighter graph traversal defaults for lower latency."),
					"max_entities_per_chunk": toolIntegerSchema("Optional cap on graph-derived entities attached to each chunk."),
				},
			),
		},
		{
			Name:        "knowledge_memory_neighbors",
			Description: "Resolve one entity or node and return its graph neighbors.",
			InputSchema: toolObjectSchema(
				[]string{},
				map[string]any{
					"node_id":     toolStringSchema("Optional explicit node ID."),
					"entity_name": toolStringSchema("Optional entity name."),
					"max_depth":   toolIntegerSchema("Traversal depth."),
					"edge_types":  toolStringArraySchema("Optional edge type filter."),
					"node_types":  toolStringArraySchema("Optional node type filter."),
					"direction":   toolEnumSchema("Traversal direction.", "out", "in", "both"),
					"limit":       toolIntegerSchema("Optional result limit."),
				},
			),
		},
		{
			Name:        "knowledge_memory_shortest_path",
			Description: "Resolve two entities or nodes and return the graph shortest path between them.",
			InputSchema: toolObjectSchema(
				[]string{},
				map[string]any{
					"from_node_id":     toolStringSchema("Optional explicit start node ID."),
					"to_node_id":       toolStringSchema("Optional explicit target node ID."),
					"from_entity_name": toolStringSchema("Optional start entity name."),
					"to_entity_name":   toolStringSchema("Optional target entity name."),
				},
			),
		},
		{
			Name: "knowledge_memory_reflect",
			// The deterministic fallback only recalls and summarizes, but a
			// configured KnowledgeMemoryReflector is an arbitrary caller-
			// supplied implementation holding the context, and nothing in the
			// interface stops it writing. Whether reflection mutates is
			// therefore not decidable from this repository, and an undecidable
			// tool is a write.
			Mutates:     true,
			Description: "Recall from the KnowledgeMemory and synthesize a structured reflection. If a KnowledgeMemoryReflector is configured, it is used; otherwise CortexDB falls back to deterministic consolidation.",
			InputSchema: toolObjectSchema(
				[]string{"recall"},
				map[string]any{
					"recall": toolObjectSchema(
						[]string{"query"},
						map[string]any{
							"query":                  toolStringSchema("Natural-language recall goal."),
							"user_id":                toolStringSchema("Optional user ID for memory recall."),
							"session_id":             toolStringSchema("Optional session ID for session-scoped memory recall."),
							"scope":                  toolEnumSchema("Optional memory scope.", MemoryScopeGlobal, MemoryScopeUser, MemoryScopeSession),
							"namespace":              toolStringSchema("Optional memory namespace."),
							"collection":             toolStringSchema("Optional knowledge collection."),
							"top_k_memories":         toolIntegerSchema("Maximum number of memory hits."),
							"top_k_knowledge":        toolIntegerSchema("Maximum number of knowledge hits."),
							"max_memory_items":       toolIntegerSchema("Maximum memory items included in the context pack."),
							"max_memory_chars":       toolIntegerSchema("Maximum character budget for memory context."),
							"keywords":               toolStringArraySchema("Expanded keywords, aliases, abbreviations, and synonyms."),
							"alternate_queries":      toolStringArraySchema("Alternate phrasings generated from the same goal."),
							"entity_names":           toolStringArraySchema("Structured entity hints."),
							"retrieval_mode":         toolEnumSchema("Preferred retrieval strategy.", RetrievalModeAuto, RetrievalModeLexical, RetrievalModeGraph),
							"disable_memory":         toolBooleanSchema("Skip episodic memory recall."),
							"disable_knowledge":      toolBooleanSchema("Skip durable knowledge recall."),
							"disable_graph":          toolBooleanSchema("Disable graph expansion."),
							"graph_light":            toolBooleanSchema("Enable lighter graph traversal defaults for lower latency."),
							"max_hops":               toolIntegerSchema("Graph expansion depth."),
							"max_related_chunks":     toolIntegerSchema("Maximum graph-expanded chunks."),
							"max_context_chunks":     toolIntegerSchema("Maximum chunks in final context."),
							"max_context_chars":      toolIntegerSchema("Maximum context character budget."),
							"per_document_limit":     toolIntegerSchema("Maximum chunks per document."),
							"max_expansion_seeds":    toolIntegerSchema("Optional cap on seed chunks expanded through the graph."),
							"max_traversal_nodes":    toolIntegerSchema("Optional cap on graph nodes inspected during expansion."),
							"max_entities_per_chunk": toolIntegerSchema("Optional cap on graph-derived entities attached to each chunk."),
							"plan":                   toolRetrievalPlanSchema("Optional structured retrieval plan."),
						},
					),
					"instructions":      toolStringSchema("Optional reflection instructions."),
					"max_summary_chars": toolIntegerSchema("Maximum summary character budget."),
					"max_facts":         toolIntegerSchema("Maximum number of facts to surface."),
					"max_themes":        toolIntegerSchema("Maximum number of themes to surface."),
				},
			),
		},
		{
			Name: "knowledge_memory_consolidate",
			// Reads like reflect with extra reporting; it persists a summary
			// memory on every call and can promote that into knowledge too.
			Mutates:     true,
			Description: "Reflect over recalled KnowledgeMemory context, persist a summary memory, and optionally promote that summary into durable knowledge.",
			InputSchema: toolObjectSchema(
				[]string{"reflect"},
				map[string]any{
					"reflect": toolObjectSchema(
						[]string{"recall"},
						map[string]any{
							"recall": toolObjectSchema(
								[]string{"query"},
								map[string]any{
									"query":                  toolStringSchema("Natural-language recall goal."),
									"user_id":                toolStringSchema("Optional user ID for memory recall."),
									"session_id":             toolStringSchema("Optional session ID for session-scoped memory recall."),
									"scope":                  toolEnumSchema("Optional memory scope.", MemoryScopeGlobal, MemoryScopeUser, MemoryScopeSession),
									"namespace":              toolStringSchema("Optional memory namespace."),
									"collection":             toolStringSchema("Optional knowledge collection."),
									"top_k_memories":         toolIntegerSchema("Maximum number of memory hits."),
									"top_k_knowledge":        toolIntegerSchema("Maximum number of knowledge hits."),
									"max_memory_items":       toolIntegerSchema("Maximum memory items included in the context pack."),
									"max_memory_chars":       toolIntegerSchema("Maximum character budget for memory context."),
									"keywords":               toolStringArraySchema("Expanded keywords, aliases, abbreviations, and synonyms."),
									"alternate_queries":      toolStringArraySchema("Alternate phrasings generated from the same goal."),
									"entity_names":           toolStringArraySchema("Structured entity hints."),
									"retrieval_mode":         toolEnumSchema("Preferred retrieval strategy.", RetrievalModeAuto, RetrievalModeLexical, RetrievalModeGraph),
									"disable_memory":         toolBooleanSchema("Skip episodic memory recall."),
									"disable_knowledge":      toolBooleanSchema("Skip durable knowledge recall."),
									"disable_graph":          toolBooleanSchema("Disable graph expansion."),
									"graph_light":            toolBooleanSchema("Enable lighter graph traversal defaults for lower latency."),
									"max_hops":               toolIntegerSchema("Graph expansion depth."),
									"max_related_chunks":     toolIntegerSchema("Maximum graph-expanded chunks."),
									"max_context_chunks":     toolIntegerSchema("Maximum chunks in final context."),
									"max_context_chars":      toolIntegerSchema("Maximum context character budget."),
									"per_document_limit":     toolIntegerSchema("Maximum chunks per document."),
									"max_expansion_seeds":    toolIntegerSchema("Optional cap on seed chunks expanded through the graph."),
									"max_traversal_nodes":    toolIntegerSchema("Optional cap on graph nodes inspected during expansion."),
									"max_entities_per_chunk": toolIntegerSchema("Optional cap on graph-derived entities attached to each chunk."),
									"plan":                   toolRetrievalPlanSchema("Optional structured retrieval plan."),
								},
							),
							"instructions":      toolStringSchema("Optional reflection instructions."),
							"max_summary_chars": toolIntegerSchema("Maximum summary character budget."),
							"max_facts":         toolIntegerSchema("Maximum number of facts to surface."),
							"max_themes":        toolIntegerSchema("Maximum number of themes to surface."),
						},
					),
					"memory_id":            toolStringSchema("Optional stable summary memory ID."),
					"user_id":              toolStringSchema("Optional user ID for the saved summary memory."),
					"session_id":           toolStringSchema("Optional session ID for the saved summary memory."),
					"scope":                toolEnumSchema("Optional memory scope for the saved summary.", MemoryScopeGlobal, MemoryScopeUser, MemoryScopeSession),
					"namespace":            toolStringSchema("Optional memory namespace for the saved summary."),
					"role":                 toolStringSchema("Optional role for the saved summary memory."),
					"metadata":             toolMapSchema("Optional metadata merged onto the saved summary memory."),
					"importance":           toolNumberSchema("Optional importance score for the saved summary."),
					"ttl_seconds":          toolIntegerSchema("Optional TTL in seconds for the saved summary."),
					"promote_to_knowledge": toolBooleanSchema("When true, also promote the summary into durable knowledge."),
					"promotion": toolObjectSchema(
						[]string{},
						map[string]any{
							"memory_ids":    toolStringArraySchema("Optional memory IDs to promote. Defaults to the saved summary memory."),
							"knowledge_id":  toolStringSchema("Optional stable knowledge ID."),
							"title":         toolStringSchema("Optional title."),
							"source_url":    toolStringSchema("Optional source URL."),
							"author":        toolStringSchema("Optional author."),
							"collection":    toolStringSchema("Optional chunk collection."),
							"chunk_size":    toolIntegerSchema("Optional chunk size in words."),
							"chunk_overlap": toolIntegerSchema("Optional chunk overlap in words."),
							"join_with":     toolStringSchema("Optional separator used to join source memories."),
							"metadata":      toolMapSchema("Optional metadata."),
							"entities":      toolEntityArraySchema(),
							"relations":     toolRelationArraySchema(),
						},
					),
				},
			),
		},
	}
	return definitions
}
