package cortexdb

import (
	"context"
	"encoding/json"
	"fmt"
)

// Definitions returns the JSON-schema-like definitions for the available tools.
func (t *GraphRAGToolbox) Definitions() []ToolDefinition {
	definitions := []ToolDefinition{
		{
			Name:        "ingest_document",
			Description: "Store a document, split it into chunks, index it lexically, and create document/chunk graph nodes.",
			InputSchema: toolObjectSchema(
				[]string{"document_id", "content"},
				map[string]any{
					"document_id":   toolStringSchema("Stable document ID."),
					"title":         toolStringSchema("Optional human-readable title."),
					"content":       toolStringSchema("Raw document content."),
					"collection":    toolStringSchema("Optional chunk collection name."),
					"chunk_size":    toolIntegerSchema("Optional chunk size in words."),
					"chunk_overlap": toolIntegerSchema("Optional chunk overlap in words."),
					"metadata":      toolMapSchema("Optional document metadata."),
				},
			),
		},
		{
			Name:        "upsert_entities",
			Description: "Create entity nodes and connect chunks to those entities with mention edges.",
			InputSchema: toolObjectSchema(
				[]string{"entities"},
				map[string]any{
					"document_id": toolStringSchema("Optional source document ID."),
					"entities": map[string]any{
						"type": "array",
						"items": toolObjectSchema(
							[]string{"name"},
							map[string]any{
								"id":          toolStringSchema("Optional explicit entity node ID."),
								"name":        toolStringSchema("Entity display name."),
								"type":        toolStringSchema("Optional entity type."),
								"description": toolStringSchema("Optional entity description."),
								"chunk_ids":   toolStringArraySchema("Chunk IDs that mention this entity."),
								"metadata":    toolMapSchema("Optional metadata."),
							},
						),
					},
				},
			),
		},
		{
			Name:        "upsert_relations",
			Description: "Create relation edges between entity nodes.",
			InputSchema: toolObjectSchema(
				[]string{"relations"},
				map[string]any{
					"document_id": toolStringSchema("Optional source document ID."),
					"relations": map[string]any{
						"type": "array",
						"items": toolObjectSchema(
							[]string{"from", "to"},
							map[string]any{
								"from":             toolStringSchema("Source entity name or entity node ID."),
								"to":               toolStringSchema("Target entity name or entity node ID."),
								"type":             toolStringSchema("Optional relation type."),
								"weight":           toolNumberSchema("Optional edge weight."),
								"chunk_ids":        toolStringArraySchema("Optional supporting chunk IDs."),
								"metadata":         toolMapSchema("Optional metadata."),
								"inferred":         toolBooleanSchema("Set true when this relation is inferred rather than explicit."),
								"provenance":       toolStringSchema("Optional provenance source such as rule or llm."),
								"rule_id":          toolStringSchema("Optional rule or inference identifier."),
								"support_edge_ids": toolStringArraySchema("Optional supporting relation edge IDs for provenance."),
							},
						),
					},
				},
			),
		},
		{
			Name:        "search_text",
			Description: "Run lexical BM25/FTS5 retrieval over stored chunks. Prefer sending a structured plan, and before calling, expand the user goal into many keywords, aliases, synonyms, and multilingual variants.",
			InputSchema: toolObjectSchema(
				[]string{"query"},
				map[string]any{
					"query":                  toolStringSchema("User goal or natural-language question."),
					"collection":             toolStringSchema("Optional collection name."),
					"top_k":                  toolIntegerSchema("Maximum number of chunks to return."),
					"threshold":              toolNumberSchema("Optional minimum normalized score."),
					"keywords":               toolStringArraySchema("LLM-generated keyword bank derived from the goal. Include aliases, synonyms, abbreviations, translations, and domain terms."),
					"alternate_queries":      toolStringArraySchema("Alternate phrasings generated by the LLM planner from the same goal."),
					"retrieval_mode":         toolEnumSchema("Preferred retrieval strategy.", RetrievalModeAuto, RetrievalModeLexical, RetrievalModeGraph),
					"disable_graph":          toolBooleanSchema("Legacy alias. Set true to avoid graph-based entity enrichment and force lexical-only retrieval."),
					"graph_light":            toolBooleanSchema("Enable lighter graph enrichment defaults for lower latency."),
					"max_entities_per_chunk": toolIntegerSchema("Optional cap on graph-derived entities attached to each chunk."),
					"plan":                   toolRetrievalPlanSchema("Preferred structured retrieval plan produced by the external LLM before search."),
				},
			),
		},
		{
			Name:        "search_chunks_by_entities",
			Description: "Find chunks linked to specific entity nodes.",
			InputSchema: toolObjectSchema(
				[]string{"entity_names"},
				map[string]any{
					"entity_names": toolStringArraySchema("Entity names or node IDs."),
					"top_k":        toolIntegerSchema("Maximum number of chunks to return."),
					"max_hops":     toolIntegerSchema("Traversal depth from entities."),
				},
			),
		},
		{
			Name:        "expand_graph",
			Description: "Expand a graph neighborhood and return a subgraph.",
			InputSchema: toolObjectSchema(
				[]string{"node_ids"},
				map[string]any{
					"node_ids":   toolStringArraySchema("Starting node IDs."),
					"max_hops":   toolIntegerSchema("Traversal depth."),
					"edge_types": toolStringArraySchema("Optional edge type filter."),
					"node_types": toolStringArraySchema("Optional node type filter."),
					"limit":      toolIntegerSchema("Optional node result limit."),
				},
			),
		},
		{
			Name:        "get_nodes",
			Description: "Fetch graph nodes by ID.",
			InputSchema: toolObjectSchema(
				[]string{"node_ids"},
				map[string]any{
					"node_ids": toolStringArraySchema("Node IDs to load."),
				},
			),
		},
		{
			Name:        "get_chunks",
			Description: "Fetch chunk records by chunk ID.",
			InputSchema: toolObjectSchema(
				[]string{"chunk_ids"},
				map[string]any{
					"chunk_ids":              toolStringArraySchema("Chunk IDs to load."),
					"retrieval_mode":         toolEnumSchema("Preferred retrieval strategy for entity enrichment.", RetrievalModeAuto, RetrievalModeLexical, RetrievalModeGraph),
					"disable_graph":          toolBooleanSchema("Legacy alias. Set true to skip graph-derived entity lookups while loading chunks."),
					"graph_light":            toolBooleanSchema("Enable lighter graph enrichment defaults while loading chunks."),
					"max_entities_per_chunk": toolIntegerSchema("Optional cap on graph-derived entities attached to each chunk."),
				},
			),
		},
		{
			Name:        "build_context",
			Description: "Pack chunk text into a bounded context window.",
			InputSchema: toolObjectSchema(
				[]string{"chunk_ids"},
				map[string]any{
					"chunk_ids":              toolStringArraySchema("Ordered chunk IDs."),
					"max_context_chunks":     toolIntegerSchema("Maximum number of chunks to include."),
					"max_context_chars":      toolIntegerSchema("Maximum total character budget."),
					"per_document_limit":     toolIntegerSchema("Maximum chunks per document."),
					"retrieval_mode":         toolEnumSchema("Preferred retrieval strategy for entity enrichment.", RetrievalModeAuto, RetrievalModeLexical, RetrievalModeGraph),
					"disable_graph":          toolBooleanSchema("Legacy alias. Set true to skip graph-derived entity lookups while packing context."),
					"graph_light":            toolBooleanSchema("Enable lighter graph enrichment defaults while packing context."),
					"max_entities_per_chunk": toolIntegerSchema("Optional cap on graph-derived entities attached to each chunk."),
				},
			),
		},
		{
			Name:        "search_graphrag_lexical",
			Description: "Perform lexical GraphRAG retrieval using FTS5 seeds, graph expansion, rerank, and context packing. Prefer sending a structured plan, and first expand the user goal into many keywords, aliases, synonyms, and multilingual variants.",
			InputSchema: toolObjectSchema(
				[]string{"query"},
				map[string]any{
					"query":                  toolStringSchema("User goal or natural-language question."),
					"collection":             toolStringSchema("Optional chunk collection name."),
					"top_k":                  toolIntegerSchema("Seed chunk count."),
					"max_hops":               toolIntegerSchema("Graph expansion depth."),
					"max_related_chunks":     toolIntegerSchema("Maximum graph-expanded chunks."),
					"max_context_chunks":     toolIntegerSchema("Maximum chunks in final context."),
					"max_context_chars":      toolIntegerSchema("Maximum context character budget."),
					"per_document_limit":     toolIntegerSchema("Maximum chunks per document."),
					"disable_rerank":         toolBooleanSchema("Disable reranking and keep chunk order close to retrieval order."),
					"diversity_lambda":       toolNumberSchema("Rerank diversity weight between 0 and 1."),
					"entity_names":           toolStringArraySchema("Optional entities from structured LLM planning."),
					"keywords":               toolStringArraySchema("LLM-generated keyword bank derived from the goal. Include aliases, synonyms, abbreviations, translations, and domain terms."),
					"alternate_queries":      toolStringArraySchema("Alternate phrasings generated by the LLM planner from the same goal."),
					"retrieval_mode":         toolEnumSchema("Preferred retrieval strategy. Use lexical for speed, graph for full expansion, or auto for heuristic selection.", RetrievalModeAuto, RetrievalModeLexical, RetrievalModeGraph),
					"disable_graph":          toolBooleanSchema("Legacy alias. Set true to disable graph traversal and force lexical-only retrieval."),
					"graph_light":            toolBooleanSchema("Enable lighter graph traversal defaults for lower latency."),
					"max_expansion_seeds":    toolIntegerSchema("Optional cap on how many seed chunks will be expanded through the graph."),
					"max_traversal_nodes":    toolIntegerSchema("Optional cap on how many graph nodes will be inspected during expansion."),
					"max_entities_per_chunk": toolIntegerSchema("Optional cap on graph-derived entities attached to each chunk."),
					"plan":                   toolRetrievalPlanSchema("Preferred structured retrieval plan produced by the external LLM before search."),
				},
			),
		},
	}
	definitions = append(definitions, inferenceToolDefinitions()...)
	definitions = append(definitions, ontologyToolDefinitions()...)
	return append(definitions, knowledgeMemoryToolDefinitions()...)
}

// Call dispatches a tool request from JSON input to a typed implementation.
func (t *GraphRAGToolbox) Call(ctx context.Context, name string, input json.RawMessage) (any, error) {
	if resp, handled, err := t.callInferenceTool(ctx, name, input); handled {
		return resp, err
	}
	if resp, handled, err := t.callOntologyTool(ctx, name, input); handled {
		return resp, err
	}
	switch name {
	case "ingest_document":
		var req ToolIngestDocumentRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.IngestDocument(ctx, req)
	case "upsert_entities":
		var req ToolUpsertEntitiesRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.UpsertEntities(ctx, req)
	case "upsert_relations":
		var req ToolUpsertRelationsRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.UpsertRelations(ctx, req)
	case "search_text":
		var req ToolSearchTextRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.SearchText(ctx, req)
	case "search_chunks_by_entities":
		var req ToolSearchChunksByEntitiesRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.SearchChunksByEntities(ctx, req)
	case "expand_graph":
		var req ToolExpandGraphRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.ExpandGraph(ctx, req)
	case "get_nodes":
		var req ToolGetNodesRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.GetNodes(ctx, req)
	case "get_chunks":
		var req ToolGetChunksRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.GetChunks(ctx, req)
	case "build_context":
		var req ToolBuildContextRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.BuildContext(ctx, req)
	case "search_graphrag_lexical":
		var req ToolSearchGraphRAGLexicalRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.SearchGraphRAGLexical(ctx, req)
	case "knowledge_save":
		var req KnowledgeSaveRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.SaveKnowledge(ctx, req)
	case "knowledge_update":
		var req KnowledgeUpdateRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.UpdateKnowledge(ctx, req)
	case "knowledge_get":
		var req KnowledgeGetRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.GetKnowledge(ctx, req)
	case "knowledge_search":
		var req KnowledgeSearchRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.SearchKnowledge(ctx, req)
	case "knowledge_delete":
		var req KnowledgeDeleteRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.DeleteKnowledge(ctx, req)
	case "memory_save":
		var req MemorySaveRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.SaveMemory(ctx, req)
	case "memory_update":
		var req MemoryUpdateRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.UpdateMemory(ctx, req)
	case "memory_get":
		var req MemoryGetRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.GetMemory(ctx, req)
	case "memory_search":
		var req MemorySearchRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.SearchMemory(ctx, req)
	case "memory_delete":
		var req MemoryDeleteRequest
		if err := json.Unmarshal(input, &req); err != nil {
			return nil, fmt.Errorf("decode %s: %w", name, err)
		}
		return t.DeleteMemory(ctx, req)
	default:
		return nil, fmt.Errorf("unknown tool: %s", name)
	}
}

func toolObjectSchema(required []string, properties map[string]any) map[string]any {
	return map[string]any{
		"type":       "object",
		"properties": properties,
		"required":   required,
	}
}

func toolStringSchema(description string) map[string]any {
	return map[string]any{"type": "string", "description": description}
}

func toolIntegerSchema(description string) map[string]any {
	return map[string]any{"type": "integer", "description": description}
}

func toolNumberSchema(description string) map[string]any {
	return map[string]any{"type": "number", "description": description}
}

func toolBooleanSchema(description string) map[string]any {
	return map[string]any{"type": "boolean", "description": description}
}

func toolEnumSchema(description string, values ...string) map[string]any {
	enumValues := make([]any, 0, len(values))
	for _, value := range values {
		enumValues = append(enumValues, value)
	}
	return map[string]any{
		"type":        "string",
		"description": description,
		"enum":        enumValues,
	}
}

func toolMapSchema(description string) map[string]any {
	return map[string]any{
		"type":                 "object",
		"description":          description,
		"additionalProperties": true,
	}
}

func toolStringArraySchema(description string) map[string]any {
	return map[string]any{
		"type":        "array",
		"description": description,
		"items":       map[string]any{"type": "string"},
	}
}
