// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.1
// source: cortexdb/v1/admin.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_cortexdb_v1_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_admin_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_cortexdb_v1_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_admin_proto_rawDescGZIP(), []int{1}
}

func (x *HealthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_cortexdb_v1_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_admin_proto_rawDescGZIP(), []int{2}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	DbPath        string                 `protobuf:"bytes,2,opt,name=db_path,json=dbPath,proto3" json:"db_path,omitempty"`
	HasEmbedder   bool                   `protobuf:"varint,3,opt,name=has_embedder,json=hasEmbedder,proto3" json:"has_embedder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_cortexdb_v1_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_admin_proto_rawDescGZIP(), []int{3}
}

func (x *InfoResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *InfoResponse) GetDbPath() string {
	if x != nil {
		return x.DbPath
	}
	return ""
}

func (x *InfoResponse) GetHasEmbedder() bool {
	if x != nil {
		return x.HasEmbedder
	}
	return false
}

var File_cortexdb_v1_admin_proto protoreflect.FileDescriptor

const file_cortexdb_v1_admin_proto_rawDesc = "" +
	"\n" +
	"\x17cortexdb/v1/admin.proto\x12\vcortexdb.v1\"\x0f\n" +
	"\rHealthRequest\" \n" +
	"\x0eHealthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\r\n" +
	"\vInfoRequest\"d\n" +
	"\fInfoResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x17\n" +
	"\adb_path\x18\x02 \x01(\tR\x06dbPath\x12!\n" +
	"\fhas_embedder\x18\x03 \x01(\bR\vhasEmbedder2\x8e\x01\n" +
	"\fAdminService\x12A\n" +
	"\x06Health\x12\x1a.cortexdb.v1.HealthRequest\x1a\x1b.cortexdb.v1.HealthResponse\x12;\n" +
	"\x04Info\x12\x18.cortexdb.v1.InfoRequest\x1a\x19.cortexdb.v1.InfoResponseB4Z2github.com/liliang-cn/cortexdb/v2/pkg/rpc/v1;rpcv1b\x06proto3"

var (
	file_cortexdb_v1_admin_proto_rawDescOnce sync.Once
	file_cortexdb_v1_admin_proto_rawDescData []byte
)

func file_cortexdb_v1_admin_proto_rawDescGZIP() []byte {
	file_cortexdb_v1_admin_proto_rawDescOnce.Do(func() {
		file_cortexdb_v1_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortexdb_v1_admin_proto_rawDesc), len(file_cortexdb_v1_admin_proto_rawDesc)))
	})
	return file_cortexdb_v1_admin_proto_rawDescData
}

var file_cortexdb_v1_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_cortexdb_v1_admin_proto_goTypes = []any{
	(*HealthRequest)(nil),  // 0: cortexdb.v1.HealthRequest
	(*HealthResponse)(nil), // 1: cortexdb.v1.HealthResponse
	(*InfoRequest)(nil),    // 2: cortexdb.v1.InfoRequest
	(*InfoResponse)(nil),   // 3: cortexdb.v1.InfoResponse
}
var file_cortexdb_v1_admin_proto_depIdxs = []int32{
	0, // 0: cortexdb.v1.AdminService.Health:input_type -> cortexdb.v1.HealthRequest
	2, // 1: cortexdb.v1.AdminService.Info:input_type -> cortexdb.v1.InfoRequest
	1, // 2: cortexdb.v1.AdminService.Health:output_type -> cortexdb.v1.HealthResponse
	3, // 3: cortexdb.v1.AdminService.Info:output_type -> cortexdb.v1.InfoResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_cortexdb_v1_admin_proto_init() }
func file_cortexdb_v1_admin_proto_init() {
	if File_cortexdb_v1_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortexdb_v1_admin_proto_rawDesc), len(file_cortexdb_v1_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cortexdb_v1_admin_proto_goTypes,
		DependencyIndexes: file_cortexdb_v1_admin_proto_depIdxs,
		MessageInfos:      file_cortexdb_v1_admin_proto_msgTypes,
	}.Build()
	File_cortexdb_v1_admin_proto = out.File
	file_cortexdb_v1_admin_proto_goTypes = nil
	file_cortexdb_v1_admin_proto_depIdxs = nil
}
