// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.1
// source: cortexdb/v1/common.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RetrievalFilters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	DocumentIds   []string               `protobuf:"bytes,2,rep,name=document_ids,json=documentIds,proto3" json:"document_ids,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,4,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Namespace     string                 `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievalFilters) Reset() {
	*x = RetrievalFilters{}
	mi := &file_cortexdb_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalFilters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalFilters) ProtoMessage() {}

func (x *RetrievalFilters) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalFilters.ProtoReflect.Descriptor instead.
func (*RetrievalFilters) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *RetrievalFilters) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *RetrievalFilters) GetDocumentIds() []string {
	if x != nil {
		return x.DocumentIds
	}
	return nil
}

func (x *RetrievalFilters) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RetrievalFilters) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RetrievalFilters) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *RetrievalFilters) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type RetrievalPlan struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Query            string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Keywords         []string               `protobuf:"bytes,2,rep,name=keywords,proto3" json:"keywords,omitempty"`
	AlternateQueries []string               `protobuf:"bytes,3,rep,name=alternate_queries,json=alternateQueries,proto3" json:"alternate_queries,omitempty"`
	EntityNames      []string               `protobuf:"bytes,4,rep,name=entity_names,json=entityNames,proto3" json:"entity_names,omitempty"`
	RetrievalMode    string                 `protobuf:"bytes,5,opt,name=retrieval_mode,json=retrievalMode,proto3" json:"retrieval_mode,omitempty"`
	Filters          *RetrievalFilters      `protobuf:"bytes,6,opt,name=filters,proto3,oneof" json:"filters,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RetrievalPlan) Reset() {
	*x = RetrievalPlan{}
	mi := &file_cortexdb_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalPlan) ProtoMessage() {}

func (x *RetrievalPlan) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalPlan.ProtoReflect.Descriptor instead.
func (*RetrievalPlan) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *RetrievalPlan) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *RetrievalPlan) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *RetrievalPlan) GetAlternateQueries() []string {
	if x != nil {
		return x.AlternateQueries
	}
	return nil
}

func (x *RetrievalPlan) GetEntityNames() []string {
	if x != nil {
		return x.EntityNames
	}
	return nil
}

func (x *RetrievalPlan) GetRetrievalMode() string {
	if x != nil {
		return x.RetrievalMode
	}
	return ""
}

func (x *RetrievalPlan) GetFilters() *RetrievalFilters {
	if x != nil {
		return x.Filters
	}
	return nil
}

type RetrievalDecision struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestedMode string                 `protobuf:"bytes,1,opt,name=requested_mode,json=requestedMode,proto3" json:"requested_mode,omitempty"`
	EffectiveMode string                 `protobuf:"bytes,2,opt,name=effective_mode,json=effectiveMode,proto3" json:"effective_mode,omitempty"`
	UseGraph      bool                   `protobuf:"varint,3,opt,name=use_graph,json=useGraph,proto3" json:"use_graph,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RetrievalDecision) Reset() {
	*x = RetrievalDecision{}
	mi := &file_cortexdb_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetrievalDecision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetrievalDecision) ProtoMessage() {}

func (x *RetrievalDecision) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetrievalDecision.ProtoReflect.Descriptor instead.
func (*RetrievalDecision) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *RetrievalDecision) GetRequestedMode() string {
	if x != nil {
		return x.RequestedMode
	}
	return ""
}

func (x *RetrievalDecision) GetEffectiveMode() string {
	if x != nil {
		return x.EffectiveMode
	}
	return ""
}

func (x *RetrievalDecision) GetUseGraph() bool {
	if x != nil {
		return x.UseGraph
	}
	return false
}

func (x *RetrievalDecision) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type GraphRagChunkResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	DocumentId    string                 `protobuf:"bytes,2,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	BaseScore     float64                `protobuf:"fixed64,5,opt,name=base_score,json=baseScore,proto3" json:"base_score,omitempty"`
	RerankScore   float64                `protobuf:"fixed64,6,opt,name=rerank_score,json=rerankScore,proto3" json:"rerank_score,omitempty"`
	Entities      []string               `protobuf:"bytes,7,rep,name=entities,proto3" json:"entities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GraphRagChunkResult) Reset() {
	*x = GraphRagChunkResult{}
	mi := &file_cortexdb_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GraphRagChunkResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GraphRagChunkResult) ProtoMessage() {}

func (x *GraphRagChunkResult) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GraphRagChunkResult.ProtoReflect.Descriptor instead.
func (*GraphRagChunkResult) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *GraphRagChunkResult) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GraphRagChunkResult) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *GraphRagChunkResult) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GraphRagChunkResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *GraphRagChunkResult) GetBaseScore() float64 {
	if x != nil {
		return x.BaseScore
	}
	return 0
}

func (x *GraphRagChunkResult) GetRerankScore() float64 {
	if x != nil {
		return x.RerankScore
	}
	return 0
}

func (x *GraphRagChunkResult) GetEntities() []string {
	if x != nil {
		return x.Entities
	}
	return nil
}

type ToolEntityInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	ChunkIds      []string               `protobuf:"bytes,5,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToolEntityInput) Reset() {
	*x = ToolEntityInput{}
	mi := &file_cortexdb_v1_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolEntityInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolEntityInput) ProtoMessage() {}

func (x *ToolEntityInput) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolEntityInput.ProtoReflect.Descriptor instead.
func (*ToolEntityInput) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_common_proto_rawDescGZIP(), []int{4}
}

func (x *ToolEntityInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ToolEntityInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ToolEntityInput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolEntityInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ToolEntityInput) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

func (x *ToolEntityInput) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ToolRelationInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	From           string                 `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To             string                 `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Type           string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Weight         float64                `protobuf:"fixed64,4,opt,name=weight,proto3" json:"weight,omitempty"`
	ChunkIds       []string               `protobuf:"bytes,5,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Inferred       bool                   `protobuf:"varint,7,opt,name=inferred,proto3" json:"inferred,omitempty"`
	Provenance     string                 `protobuf:"bytes,8,opt,name=provenance,proto3" json:"provenance,omitempty"`
	RuleId         string                 `protobuf:"bytes,9,opt,name=rule_id,json=ruleId,proto3" json:"rule_id,omitempty"`
	SupportEdgeIds []string               `protobuf:"bytes,10,rep,name=support_edge_ids,json=supportEdgeIds,proto3" json:"support_edge_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToolRelationInput) Reset() {
	*x = ToolRelationInput{}
	mi := &file_cortexdb_v1_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToolRelationInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToolRelationInput) ProtoMessage() {}

func (x *ToolRelationInput) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToolRelationInput.ProtoReflect.Descriptor instead.
func (*ToolRelationInput) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_common_proto_rawDescGZIP(), []int{5}
}

func (x *ToolRelationInput) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ToolRelationInput) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ToolRelationInput) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ToolRelationInput) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ToolRelationInput) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

func (x *ToolRelationInput) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ToolRelationInput) GetInferred() bool {
	if x != nil {
		return x.Inferred
	}
	return false
}

func (x *ToolRelationInput) GetProvenance() string {
	if x != nil {
		return x.Provenance
	}
	return ""
}

func (x *ToolRelationInput) GetRuleId() string {
	if x != nil {
		return x.RuleId
	}
	return ""
}

func (x *ToolRelationInput) GetSupportEdgeIds() []string {
	if x != nil {
		return x.SupportEdgeIds
	}
	return nil
}

var File_cortexdb_v1_common_proto protoreflect.FileDescriptor

const file_cortexdb_v1_common_proto_rawDesc = "" +
	"\n" +
	"\x18cortexdb/v1/common.proto\x12\vcortexdb.v1\"\xc1\x01\n" +
	"\x10RetrievalFilters\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12!\n" +
	"\fdocument_ids\x18\x02 \x03(\tR\vdocumentIds\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x04 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\x12\x1c\n" +
	"\tnamespace\x18\x06 \x01(\tR\tnamespace\"\x82\x02\n" +
	"\rRetrievalPlan\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1a\n" +
	"\bkeywords\x18\x02 \x03(\tR\bkeywords\x12+\n" +
	"\x11alternate_queries\x18\x03 \x03(\tR\x10alternateQueries\x12!\n" +
	"\fentity_names\x18\x04 \x03(\tR\ventityNames\x12%\n" +
	"\x0eretrieval_mode\x18\x05 \x01(\tR\rretrievalMode\x12<\n" +
	"\afilters\x18\x06 \x01(\v2\x1d.cortexdb.v1.RetrievalFiltersH\x00R\afilters\x88\x01\x01B\n" +
	"\n" +
	"\b_filters\"\x96\x01\n" +
	"\x11RetrievalDecision\x12%\n" +
	"\x0erequested_mode\x18\x01 \x01(\tR\rrequestedMode\x12%\n" +
	"\x0eeffective_mode\x18\x02 \x01(\tR\reffectiveMode\x12\x1b\n" +
	"\tuse_graph\x18\x03 \x01(\bR\buseGraph\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xd4\x01\n" +
	"\x13GraphRagChunkResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vdocument_id\x18\x02 \x01(\tR\n" +
	"documentId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x1d\n" +
	"\n" +
	"base_score\x18\x05 \x01(\x01R\tbaseScore\x12!\n" +
	"\frerank_score\x18\x06 \x01(\x01R\vrerankScore\x12\x1a\n" +
	"\bentities\x18\a \x03(\tR\bentities\"\x8d\x02\n" +
	"\x0fToolEntityInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1b\n" +
	"\tchunk_ids\x18\x05 \x03(\tR\bchunkIds\x12F\n" +
	"\bmetadata\x18\x06 \x03(\v2*.cortexdb.v1.ToolEntityInput.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x03\n" +
	"\x11ToolRelationInput\x12\x12\n" +
	"\x04from\x18\x01 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x02 \x01(\tR\x02to\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06weight\x18\x04 \x01(\x01R\x06weight\x12\x1b\n" +
	"\tchunk_ids\x18\x05 \x03(\tR\bchunkIds\x12H\n" +
	"\bmetadata\x18\x06 \x03(\v2,.cortexdb.v1.ToolRelationInput.MetadataEntryR\bmetadata\x12\x1a\n" +
	"\binferred\x18\a \x01(\bR\binferred\x12\x1e\n" +
	"\n" +
	"provenance\x18\b \x01(\tR\n" +
	"provenance\x12\x17\n" +
	"\arule_id\x18\t \x01(\tR\x06ruleId\x12(\n" +
	"\x10support_edge_ids\x18\n" +
	" \x03(\tR\x0esupportEdgeIds\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B4Z2github.com/liliang-cn/cortexdb/v2/pkg/rpc/v1;rpcv1b\x06proto3"

var (
	file_cortexdb_v1_common_proto_rawDescOnce sync.Once
	file_cortexdb_v1_common_proto_rawDescData []byte
)

func file_cortexdb_v1_common_proto_rawDescGZIP() []byte {
	file_cortexdb_v1_common_proto_rawDescOnce.Do(func() {
		file_cortexdb_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortexdb_v1_common_proto_rawDesc), len(file_cortexdb_v1_common_proto_rawDesc)))
	})
	return file_cortexdb_v1_common_proto_rawDescData
}

var file_cortexdb_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cortexdb_v1_common_proto_goTypes = []any{
	(*RetrievalFilters)(nil),    // 0: cortexdb.v1.RetrievalFilters
	(*RetrievalPlan)(nil),       // 1: cortexdb.v1.RetrievalPlan
	(*RetrievalDecision)(nil),   // 2: cortexdb.v1.RetrievalDecision
	(*GraphRagChunkResult)(nil), // 3: cortexdb.v1.GraphRagChunkResult
	(*ToolEntityInput)(nil),     // 4: cortexdb.v1.ToolEntityInput
	(*ToolRelationInput)(nil),   // 5: cortexdb.v1.ToolRelationInput
	nil,                         // 6: cortexdb.v1.ToolEntityInput.MetadataEntry
	nil,                         // 7: cortexdb.v1.ToolRelationInput.MetadataEntry
}
var file_cortexdb_v1_common_proto_depIdxs = []int32{
	0, // 0: cortexdb.v1.RetrievalPlan.filters:type_name -> cortexdb.v1.RetrievalFilters
	6, // 1: cortexdb.v1.ToolEntityInput.metadata:type_name -> cortexdb.v1.ToolEntityInput.MetadataEntry
	7, // 2: cortexdb.v1.ToolRelationInput.metadata:type_name -> cortexdb.v1.ToolRelationInput.MetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_cortexdb_v1_common_proto_init() }
func file_cortexdb_v1_common_proto_init() {
	if File_cortexdb_v1_common_proto != nil {
		return
	}
	file_cortexdb_v1_common_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortexdb_v1_common_proto_rawDesc), len(file_cortexdb_v1_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_cortexdb_v1_common_proto_goTypes,
		DependencyIndexes: file_cortexdb_v1_common_proto_depIdxs,
		MessageInfos:      file_cortexdb_v1_common_proto_msgTypes,
	}.Build()
	File_cortexdb_v1_common_proto = out.File
	file_cortexdb_v1_common_proto_goTypes = nil
	file_cortexdb_v1_common_proto_depIdxs = nil
}
