// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.1
// source: cortexdb/v1/contract.proto

package rpcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ContractService_ContractTally_FullMethodName  = "/cortexdb.v1.ContractService/ContractTally"
	ContractService_NeedsAttention_FullMethodName = "/cortexdb.v1.ContractService/NeedsAttention"
)

// ContractServiceClient is the client API for ContractService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ContractService reads the knowledge contract. Read-only by construction:
// what goes on the shelf is written through the stores' own RPCs, and a
// producer that could stamp a grade without writing the record would be a way
// to make the tally disagree with the shelf.
type ContractServiceClient interface {
	// ContractTally counts every node and edge by its grade.
	ContractTally(ctx context.Context, in *ContractTallyRequest, opts ...grpc.CallOption) (*ContractTallyResponse, error)
	// NeedsAttention lists what a person has to deal with. It is a named call
	// rather than a filter language because it is the one question the contract
	// exists to make answerable, and because held and refused belong in one list
	// — split into two calls, it is likely only one gets rendered.
	NeedsAttention(ctx context.Context, in *NeedsAttentionRequest, opts ...grpc.CallOption) (*NeedsAttentionResponse, error)
}

type contractServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewContractServiceClient(cc grpc.ClientConnInterface) ContractServiceClient {
	return &contractServiceClient{cc}
}

func (c *contractServiceClient) ContractTally(ctx context.Context, in *ContractTallyRequest, opts ...grpc.CallOption) (*ContractTallyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContractTallyResponse)
	err := c.cc.Invoke(ctx, ContractService_ContractTally_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *contractServiceClient) NeedsAttention(ctx context.Context, in *NeedsAttentionRequest, opts ...grpc.CallOption) (*NeedsAttentionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NeedsAttentionResponse)
	err := c.cc.Invoke(ctx, ContractService_NeedsAttention_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContractServiceServer is the server API for ContractService service.
// All implementations must embed UnimplementedContractServiceServer
// for forward compatibility.
//
// ContractService reads the knowledge contract. Read-only by construction:
// what goes on the shelf is written through the stores' own RPCs, and a
// producer that could stamp a grade without writing the record would be a way
// to make the tally disagree with the shelf.
type ContractServiceServer interface {
	// ContractTally counts every node and edge by its grade.
	ContractTally(context.Context, *ContractTallyRequest) (*ContractTallyResponse, error)
	// NeedsAttention lists what a person has to deal with. It is a named call
	// rather than a filter language because it is the one question the contract
	// exists to make answerable, and because held and refused belong in one list
	// — split into two calls, it is likely only one gets rendered.
	NeedsAttention(context.Context, *NeedsAttentionRequest) (*NeedsAttentionResponse, error)
	mustEmbedUnimplementedContractServiceServer()
}

// UnimplementedContractServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedContractServiceServer struct{}

func (UnimplementedContractServiceServer) ContractTally(context.Context, *ContractTallyRequest) (*ContractTallyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContractTally not implemented")
}
func (UnimplementedContractServiceServer) NeedsAttention(context.Context, *NeedsAttentionRequest) (*NeedsAttentionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NeedsAttention not implemented")
}
func (UnimplementedContractServiceServer) mustEmbedUnimplementedContractServiceServer() {}
func (UnimplementedContractServiceServer) testEmbeddedByValue()                         {}

// UnsafeContractServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ContractServiceServer will
// result in compilation errors.
type UnsafeContractServiceServer interface {
	mustEmbedUnimplementedContractServiceServer()
}

func RegisterContractServiceServer(s grpc.ServiceRegistrar, srv ContractServiceServer) {
	// If the following call pancis, it indicates UnimplementedContractServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ContractService_ServiceDesc, srv)
}

func _ContractService_ContractTally_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContractTallyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).ContractTally(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractService_ContractTally_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).ContractTally(ctx, req.(*ContractTallyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ContractService_NeedsAttention_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NeedsAttentionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContractServiceServer).NeedsAttention(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ContractService_NeedsAttention_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContractServiceServer).NeedsAttention(ctx, req.(*NeedsAttentionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ContractService_ServiceDesc is the grpc.ServiceDesc for ContractService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ContractService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cortexdb.v1.ContractService",
	HandlerType: (*ContractServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ContractTally",
			Handler:    _ContractService_ContractTally_Handler,
		},
		{
			MethodName: "NeedsAttention",
			Handler:    _ContractService_NeedsAttention_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cortexdb/v1/contract.proto",
}
