// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.1
// source: cortexdb/v1/contract.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GradeCount is how many nodes and how many edges carry one grade.
//
// The two are kept apart rather than summed for the reason the Go type gives:
// an edge is an assertion about two things and a node is one thing, so "40
// records" over 4 nodes and 36 edges describes a different shelf than the
// reverse. A caller that wants the total adds them.
type GradeCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         int64                  `protobuf:"varint,1,opt,name=nodes,proto3" json:"nodes,omitempty"`
	Edges         int64                  `protobuf:"varint,2,opt,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeCount) Reset() {
	*x = GradeCount{}
	mi := &file_cortexdb_v1_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeCount) ProtoMessage() {}

func (x *GradeCount) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeCount.ProtoReflect.Descriptor instead.
func (*GradeCount) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_contract_proto_rawDescGZIP(), []int{0}
}

func (x *GradeCount) GetNodes() int64 {
	if x != nil {
		return x.Nodes
	}
	return 0
}

func (x *GradeCount) GetEdges() int64 {
	if x != nil {
		return x.Edges
	}
	return 0
}

// ContractTallyRequest takes nothing on purpose: the tally is over the whole
// store, and narrowing it to a collection answers a different question than
// the one a reader opens with ("what is on this shelf").
type ContractTallyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractTallyRequest) Reset() {
	*x = ContractTallyRequest{}
	mi := &file_cortexdb_v1_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractTallyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractTallyRequest) ProtoMessage() {}

func (x *ContractTallyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractTallyRequest.ProtoReflect.Descriptor instead.
func (*ContractTallyRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_contract_proto_rawDescGZIP(), []int{1}
}

// ContractTallyResponse is how much of the shelf stands on what.
//
// The five graded fields are the contract's closed set. The last two are why
// this message is not just a map: untagged is every record carrying no _grade
// at all — usually the largest number here, and a five-bar chart drawn without
// it describes 3% of the data while looking like all of it — and unknown is
// every grade this build does not recognise, which means some producer is
// writing a vocabulary the contract does not define. Folding those into
// untagged would hide the one case a maintainer has to act on.
type ContractTallyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Verified       *GradeCount            `protobuf:"bytes,1,opt,name=verified,proto3" json:"verified,omitempty"`
	SelfConsistent *GradeCount            `protobuf:"bytes,2,opt,name=self_consistent,json=selfConsistent,proto3" json:"self_consistent,omitempty"`
	Asserted       *GradeCount            `protobuf:"bytes,3,opt,name=asserted,proto3" json:"asserted,omitempty"`
	Held           *GradeCount            `protobuf:"bytes,4,opt,name=held,proto3" json:"held,omitempty"`
	Refused        *GradeCount            `protobuf:"bytes,5,opt,name=refused,proto3" json:"refused,omitempty"`
	Untagged       *GradeCount            `protobuf:"bytes,6,opt,name=untagged,proto3" json:"untagged,omitempty"`
	Unknown        map[string]*GradeCount `protobuf:"bytes,7,rep,name=unknown,proto3" json:"unknown,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ContractTallyResponse) Reset() {
	*x = ContractTallyResponse{}
	mi := &file_cortexdb_v1_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractTallyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractTallyResponse) ProtoMessage() {}

func (x *ContractTallyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractTallyResponse.ProtoReflect.Descriptor instead.
func (*ContractTallyResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_contract_proto_rawDescGZIP(), []int{2}
}

func (x *ContractTallyResponse) GetVerified() *GradeCount {
	if x != nil {
		return x.Verified
	}
	return nil
}

func (x *ContractTallyResponse) GetSelfConsistent() *GradeCount {
	if x != nil {
		return x.SelfConsistent
	}
	return nil
}

func (x *ContractTallyResponse) GetAsserted() *GradeCount {
	if x != nil {
		return x.Asserted
	}
	return nil
}

func (x *ContractTallyResponse) GetHeld() *GradeCount {
	if x != nil {
		return x.Held
	}
	return nil
}

func (x *ContractTallyResponse) GetRefused() *GradeCount {
	if x != nil {
		return x.Refused
	}
	return nil
}

func (x *ContractTallyResponse) GetUntagged() *GradeCount {
	if x != nil {
		return x.Untagged
	}
	return nil
}

func (x *ContractTallyResponse) GetUnknown() map[string]*GradeCount {
	if x != nil {
		return x.Unknown
	}
	return nil
}

// GradedRecord is one record with the contract keys a reader renders.
//
// The contract's other keys (_chunk, _model, _confidence, and whatever a
// producer adds under the prefix) are deliberately absent: this is what a wall
// shows and what an agent cites, and a message that grew a field per key would
// be a second place to keep the contract in step. A caller wanting the rest
// has the id.
type GradedRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// edge tells a node from an edge without a client guessing from the shape of
	// the id. A graph's assertions are mostly edges, so a reader that renders
	// only nodes misses the half that matters.
	Edge bool `protobuf:"varint,2,opt,name=edge,proto3" json:"edge,omitempty"`
	// type is node_type or edge_type.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// content is a node's label. Edges have none — they are named by their type
	// and their ends.
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// from and to are an edge's ends, empty on a node. Ids rather than labels:
	// resolving them costs a query per row, and a caller that wants the labels
	// already knows how to ask for nodes.
	From  string `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To    string `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	Grade string `protobuf:"bytes,7,opt,name=grade,proto3" json:"grade,omitempty"`
	// state is the producer's own word for where the record stands, verbatim,
	// and is never interpreted across producers — that is what keeps grade from
	// flattening di-consult's Met/Short/Missed into di-anchor's Anchored.
	State string `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	// why is the reason a record is held or refused. Every record this API
	// returns under those grades carries one: a refusal without a reason is
	// noise the reader will delete.
	Why      string `protobuf:"bytes,9,opt,name=why,proto3" json:"why,omitempty"`
	Source   string `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	Producer string `protobuf:"bytes,11,opt,name=producer,proto3" json:"producer,omitempty"`
	// at is RFC 3339, as written. Left a string rather than a Timestamp because
	// the store keeps whatever the producer stamped and a parse here would turn
	// one producer's malformed record into a failed read of the whole list.
	At            string `protobuf:"bytes,12,opt,name=at,proto3" json:"at,omitempty"`
	By            string `protobuf:"bytes,13,opt,name=by,proto3" json:"by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradedRecord) Reset() {
	*x = GradedRecord{}
	mi := &file_cortexdb_v1_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradedRecord) ProtoMessage() {}

func (x *GradedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradedRecord.ProtoReflect.Descriptor instead.
func (*GradedRecord) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_contract_proto_rawDescGZIP(), []int{3}
}

func (x *GradedRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GradedRecord) GetEdge() bool {
	if x != nil {
		return x.Edge
	}
	return false
}

func (x *GradedRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GradedRecord) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GradedRecord) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *GradedRecord) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *GradedRecord) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *GradedRecord) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *GradedRecord) GetWhy() string {
	if x != nil {
		return x.Why
	}
	return ""
}

func (x *GradedRecord) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *GradedRecord) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *GradedRecord) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

func (x *GradedRecord) GetBy() string {
	if x != nil {
		return x.By
	}
	return ""
}

// NeedsAttentionRequest caps the list.
type NeedsAttentionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// limit caps the records returned. 0 takes the server's default, which keeps
	// an unbounded ask from returning a whole shelf into a model's context. It
	// is a cap on the answer, not on the work — total still reports everything.
	Limit         int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeedsAttentionRequest) Reset() {
	*x = NeedsAttentionRequest{}
	mi := &file_cortexdb_v1_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedsAttentionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedsAttentionRequest) ProtoMessage() {}

func (x *NeedsAttentionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedsAttentionRequest.ProtoReflect.Descriptor instead.
func (*NeedsAttentionRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_contract_proto_rawDescGZIP(), []int{4}
}

func (x *NeedsAttentionRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// NeedsAttentionResponse is the work waiting on the shelf: held (nobody has
// looked yet) and refused (somebody looked and said no), told apart by grade
// and each carrying its reason.
type NeedsAttentionResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Records []*GradedRecord        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// truncated and total let a capped caller say what it is not showing. A list
	// that quietly stopped at fifty reads as "fifty things need a person", and
	// the number is the half a reader acts on.
	Truncated     bool  `protobuf:"varint,2,opt,name=truncated,proto3" json:"truncated,omitempty"`
	Total         int64 `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NeedsAttentionResponse) Reset() {
	*x = NeedsAttentionResponse{}
	mi := &file_cortexdb_v1_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NeedsAttentionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NeedsAttentionResponse) ProtoMessage() {}

func (x *NeedsAttentionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NeedsAttentionResponse.ProtoReflect.Descriptor instead.
func (*NeedsAttentionResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_contract_proto_rawDescGZIP(), []int{5}
}

func (x *NeedsAttentionResponse) GetRecords() []*GradedRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *NeedsAttentionResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

func (x *NeedsAttentionResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

var File_cortexdb_v1_contract_proto protoreflect.FileDescriptor

const file_cortexdb_v1_contract_proto_rawDesc = "" +
	"\n" +
	"\x1acortexdb/v1/contract.proto\x12\vcortexdb.v1\"8\n" +
	"\n" +
	"GradeCount\x12\x14\n" +
	"\x05nodes\x18\x01 \x01(\x03R\x05nodes\x12\x14\n" +
	"\x05edges\x18\x02 \x01(\x03R\x05edges\"\x16\n" +
	"\x14ContractTallyRequest\"\xf8\x03\n" +
	"\x15ContractTallyResponse\x123\n" +
	"\bverified\x18\x01 \x01(\v2\x17.cortexdb.v1.GradeCountR\bverified\x12@\n" +
	"\x0fself_consistent\x18\x02 \x01(\v2\x17.cortexdb.v1.GradeCountR\x0eselfConsistent\x123\n" +
	"\basserted\x18\x03 \x01(\v2\x17.cortexdb.v1.GradeCountR\basserted\x12+\n" +
	"\x04held\x18\x04 \x01(\v2\x17.cortexdb.v1.GradeCountR\x04held\x121\n" +
	"\arefused\x18\x05 \x01(\v2\x17.cortexdb.v1.GradeCountR\arefused\x123\n" +
	"\buntagged\x18\x06 \x01(\v2\x17.cortexdb.v1.GradeCountR\buntagged\x12I\n" +
	"\aunknown\x18\a \x03(\v2/.cortexdb.v1.ContractTallyResponse.UnknownEntryR\aunknown\x1aS\n" +
	"\fUnknownEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.cortexdb.v1.GradeCountR\x05value:\x028\x01\"\x96\x02\n" +
	"\fGradedRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04edge\x18\x02 \x01(\bR\x04edge\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04from\x18\x05 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x06 \x01(\tR\x02to\x12\x14\n" +
	"\x05grade\x18\a \x01(\tR\x05grade\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\x12\x10\n" +
	"\x03why\x18\t \x01(\tR\x03why\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source\x12\x1a\n" +
	"\bproducer\x18\v \x01(\tR\bproducer\x12\x0e\n" +
	"\x02at\x18\f \x01(\tR\x02at\x12\x0e\n" +
	"\x02by\x18\r \x01(\tR\x02by\"-\n" +
	"\x15NeedsAttentionRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"\x81\x01\n" +
	"\x16NeedsAttentionResponse\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.cortexdb.v1.GradedRecordR\arecords\x12\x1c\n" +
	"\ttruncated\x18\x02 \x01(\bR\ttruncated\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total2\xc4\x01\n" +
	"\x0fContractService\x12V\n" +
	"\rContractTally\x12!.cortexdb.v1.ContractTallyRequest\x1a\".cortexdb.v1.ContractTallyResponse\x12Y\n" +
	"\x0eNeedsAttention\x12\".cortexdb.v1.NeedsAttentionRequest\x1a#.cortexdb.v1.NeedsAttentionResponseB4Z2github.com/liliang-cn/cortexdb/v2/pkg/rpc/v1;rpcv1b\x06proto3"

var (
	file_cortexdb_v1_contract_proto_rawDescOnce sync.Once
	file_cortexdb_v1_contract_proto_rawDescData []byte
)

func file_cortexdb_v1_contract_proto_rawDescGZIP() []byte {
	file_cortexdb_v1_contract_proto_rawDescOnce.Do(func() {
		file_cortexdb_v1_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortexdb_v1_contract_proto_rawDesc), len(file_cortexdb_v1_contract_proto_rawDesc)))
	})
	return file_cortexdb_v1_contract_proto_rawDescData
}

var file_cortexdb_v1_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_cortexdb_v1_contract_proto_goTypes = []any{
	(*GradeCount)(nil),             // 0: cortexdb.v1.GradeCount
	(*ContractTallyRequest)(nil),   // 1: cortexdb.v1.ContractTallyRequest
	(*ContractTallyResponse)(nil),  // 2: cortexdb.v1.ContractTallyResponse
	(*GradedRecord)(nil),           // 3: cortexdb.v1.GradedRecord
	(*NeedsAttentionRequest)(nil),  // 4: cortexdb.v1.NeedsAttentionRequest
	(*NeedsAttentionResponse)(nil), // 5: cortexdb.v1.NeedsAttentionResponse
	nil,                            // 6: cortexdb.v1.ContractTallyResponse.UnknownEntry
}
var file_cortexdb_v1_contract_proto_depIdxs = []int32{
	0,  // 0: cortexdb.v1.ContractTallyResponse.verified:type_name -> cortexdb.v1.GradeCount
	0,  // 1: cortexdb.v1.ContractTallyResponse.self_consistent:type_name -> cortexdb.v1.GradeCount
	0,  // 2: cortexdb.v1.ContractTallyResponse.asserted:type_name -> cortexdb.v1.GradeCount
	0,  // 3: cortexdb.v1.ContractTallyResponse.held:type_name -> cortexdb.v1.GradeCount
	0,  // 4: cortexdb.v1.ContractTallyResponse.refused:type_name -> cortexdb.v1.GradeCount
	0,  // 5: cortexdb.v1.ContractTallyResponse.untagged:type_name -> cortexdb.v1.GradeCount
	6,  // 6: cortexdb.v1.ContractTallyResponse.unknown:type_name -> cortexdb.v1.ContractTallyResponse.UnknownEntry
	3,  // 7: cortexdb.v1.NeedsAttentionResponse.records:type_name -> cortexdb.v1.GradedRecord
	0,  // 8: cortexdb.v1.ContractTallyResponse.UnknownEntry.value:type_name -> cortexdb.v1.GradeCount
	1,  // 9: cortexdb.v1.ContractService.ContractTally:input_type -> cortexdb.v1.ContractTallyRequest
	4,  // 10: cortexdb.v1.ContractService.NeedsAttention:input_type -> cortexdb.v1.NeedsAttentionRequest
	2,  // 11: cortexdb.v1.ContractService.ContractTally:output_type -> cortexdb.v1.ContractTallyResponse
	5,  // 12: cortexdb.v1.ContractService.NeedsAttention:output_type -> cortexdb.v1.NeedsAttentionResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_cortexdb_v1_contract_proto_init() }
func file_cortexdb_v1_contract_proto_init() {
	if File_cortexdb_v1_contract_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortexdb_v1_contract_proto_rawDesc), len(file_cortexdb_v1_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cortexdb_v1_contract_proto_goTypes,
		DependencyIndexes: file_cortexdb_v1_contract_proto_depIdxs,
		MessageInfos:      file_cortexdb_v1_contract_proto_msgTypes,
	}.Build()
	File_cortexdb_v1_contract_proto = out.File
	file_cortexdb_v1_contract_proto_goTypes = nil
	file_cortexdb_v1_contract_proto_depIdxs = nil
}
