// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.1
// source: cortexdb/v1/decision.proto

package rpcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DecisionService_RecordDecision_FullMethodName = "/cortexdb.v1.DecisionService/RecordDecision"
	DecisionService_DecisionChain_FullMethodName  = "/cortexdb.v1.DecisionService/DecisionChain"
	DecisionService_Precedents_FullMethodName     = "/cortexdb.v1.DecisionService/Precedents"
)

// DecisionServiceClient is the client API for DecisionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// DecisionService records and reads the ledger. RecordDecision is the only
// write, and it is a write in the ordinary sense — it puts a node and its
// edges on the same shelf every other producer writes to, graded by the same
// contract, so contract_tally counts a decision without being told about
// decisions.
type DecisionServiceClient interface {
	// RecordDecision writes a decision and the edges that explain it. It fails
	// closed and it fails before writing anything: an unknown premise, an empty
	// actor or metadata the knowledge contract refuses leaves the store
	// untouched, because a decision that half-wrote has fewer premises than its
	// author believes and nothing downstream can tell that from a decision that
	// genuinely rested on less.
	RecordDecision(ctx context.Context, in *RecordDecisionRequest, opts ...grpc.CallOption) (*RecordDecisionResponse, error)
	// DecisionChain walks back from a decision to what it rested on.
	DecisionChain(ctx context.Context, in *DecisionChainRequest, opts ...grpc.CallOption) (*DecisionChainResponse, error)
	// Precedents lists earlier decisions of the same kind or about the same
	// subject, newest first.
	Precedents(ctx context.Context, in *PrecedentsRequest, opts ...grpc.CallOption) (*PrecedentsResponse, error)
}

type decisionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDecisionServiceClient(cc grpc.ClientConnInterface) DecisionServiceClient {
	return &decisionServiceClient{cc}
}

func (c *decisionServiceClient) RecordDecision(ctx context.Context, in *RecordDecisionRequest, opts ...grpc.CallOption) (*RecordDecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordDecisionResponse)
	err := c.cc.Invoke(ctx, DecisionService_RecordDecision_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decisionServiceClient) DecisionChain(ctx context.Context, in *DecisionChainRequest, opts ...grpc.CallOption) (*DecisionChainResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionChainResponse)
	err := c.cc.Invoke(ctx, DecisionService_DecisionChain_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *decisionServiceClient) Precedents(ctx context.Context, in *PrecedentsRequest, opts ...grpc.CallOption) (*PrecedentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrecedentsResponse)
	err := c.cc.Invoke(ctx, DecisionService_Precedents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DecisionServiceServer is the server API for DecisionService service.
// All implementations must embed UnimplementedDecisionServiceServer
// for forward compatibility.
//
// DecisionService records and reads the ledger. RecordDecision is the only
// write, and it is a write in the ordinary sense — it puts a node and its
// edges on the same shelf every other producer writes to, graded by the same
// contract, so contract_tally counts a decision without being told about
// decisions.
type DecisionServiceServer interface {
	// RecordDecision writes a decision and the edges that explain it. It fails
	// closed and it fails before writing anything: an unknown premise, an empty
	// actor or metadata the knowledge contract refuses leaves the store
	// untouched, because a decision that half-wrote has fewer premises than its
	// author believes and nothing downstream can tell that from a decision that
	// genuinely rested on less.
	RecordDecision(context.Context, *RecordDecisionRequest) (*RecordDecisionResponse, error)
	// DecisionChain walks back from a decision to what it rested on.
	DecisionChain(context.Context, *DecisionChainRequest) (*DecisionChainResponse, error)
	// Precedents lists earlier decisions of the same kind or about the same
	// subject, newest first.
	Precedents(context.Context, *PrecedentsRequest) (*PrecedentsResponse, error)
	mustEmbedUnimplementedDecisionServiceServer()
}

// UnimplementedDecisionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDecisionServiceServer struct{}

func (UnimplementedDecisionServiceServer) RecordDecision(context.Context, *RecordDecisionRequest) (*RecordDecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordDecision not implemented")
}
func (UnimplementedDecisionServiceServer) DecisionChain(context.Context, *DecisionChainRequest) (*DecisionChainResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecisionChain not implemented")
}
func (UnimplementedDecisionServiceServer) Precedents(context.Context, *PrecedentsRequest) (*PrecedentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Precedents not implemented")
}
func (UnimplementedDecisionServiceServer) mustEmbedUnimplementedDecisionServiceServer() {}
func (UnimplementedDecisionServiceServer) testEmbeddedByValue()                         {}

// UnsafeDecisionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DecisionServiceServer will
// result in compilation errors.
type UnsafeDecisionServiceServer interface {
	mustEmbedUnimplementedDecisionServiceServer()
}

func RegisterDecisionServiceServer(s grpc.ServiceRegistrar, srv DecisionServiceServer) {
	// If the following call pancis, it indicates UnimplementedDecisionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DecisionService_ServiceDesc, srv)
}

func _DecisionService_RecordDecision_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordDecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecisionServiceServer).RecordDecision(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecisionService_RecordDecision_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecisionServiceServer).RecordDecision(ctx, req.(*RecordDecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DecisionService_DecisionChain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionChainRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecisionServiceServer).DecisionChain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecisionService_DecisionChain_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecisionServiceServer).DecisionChain(ctx, req.(*DecisionChainRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DecisionService_Precedents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrecedentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DecisionServiceServer).Precedents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DecisionService_Precedents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DecisionServiceServer).Precedents(ctx, req.(*PrecedentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DecisionService_ServiceDesc is the grpc.ServiceDesc for DecisionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DecisionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cortexdb.v1.DecisionService",
	HandlerType: (*DecisionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordDecision",
			Handler:    _DecisionService_RecordDecision_Handler,
		},
		{
			MethodName: "DecisionChain",
			Handler:    _DecisionService_DecisionChain_Handler,
		},
		{
			MethodName: "Precedents",
			Handler:    _DecisionService_Precedents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cortexdb/v1/decision.proto",
}
