// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.1
// source: cortexdb/v1/decision.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DecisionPremise is one thing a decision rested on, with how sure that thing
// was.
type DecisionPremise struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id is the node id or edge id the decision named.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// edge says the premise is a fact — a relation — rather than a thing. It
	// matters to a reader: a graph's assertions are mostly edges, and a client
	// that renders only the nodes drops the half a decision usually stood on.
	Edge bool `protobuf:"varint,2,opt,name=edge,proto3" json:"edge,omitempty"`
	// type is node_type or edge_type.
	Type string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	// content is a node's label; edges have none.
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	// from and to are a fact's ends, empty on a node.
	From string `protobuf:"bytes,5,opt,name=from,proto3" json:"from,omitempty"`
	To   string `protobuf:"bytes,6,opt,name=to,proto3" json:"to,omitempty"`
	// decision says this premise is itself a decision, which is what makes a
	// chain recurse.
	Decision bool `protobuf:"varint,7,opt,name=decision,proto3" json:"decision,omitempty"`
	// grade and source are the premise's own contract keys. Empty means the
	// record carries none, which is an answer and a different one from
	// "asserted".
	Grade  string `protobuf:"bytes,8,opt,name=grade,proto3" json:"grade,omitempty"`
	Source string `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	// missing says the premise was recorded and has since been deleted. It
	// cannot happen at write time — recording refuses an unknown premise — so it
	// means the shelf changed under a decision that already stands, which the
	// reader has to be told rather than shown a gap.
	Missing       bool `protobuf:"varint,10,opt,name=missing,proto3" json:"missing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionPremise) Reset() {
	*x = DecisionPremise{}
	mi := &file_cortexdb_v1_decision_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionPremise) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionPremise) ProtoMessage() {}

func (x *DecisionPremise) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_decision_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionPremise.ProtoReflect.Descriptor instead.
func (*DecisionPremise) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_decision_proto_rawDescGZIP(), []int{0}
}

func (x *DecisionPremise) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DecisionPremise) GetEdge() bool {
	if x != nil {
		return x.Edge
	}
	return false
}

func (x *DecisionPremise) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DecisionPremise) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DecisionPremise) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *DecisionPremise) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *DecisionPremise) GetDecision() bool {
	if x != nil {
		return x.Decision
	}
	return false
}

func (x *DecisionPremise) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *DecisionPremise) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *DecisionPremise) GetMissing() bool {
	if x != nil {
		return x.Missing
	}
	return false
}

// Decision is one ledger entry.
type Decision struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// kind is the shape of the decision: load, review, action, assert, or a word
	// of the caller's own. The vocabulary is open — precedents groups by
	// whatever is written — and those four are what the product uses.
	Kind  string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Actor string `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	// at is RFC 3339, as written. A string rather than a Timestamp for the
	// reason GradedRecord.at is one: the store keeps what the producer stamped,
	// and a parse here would turn one malformed record into a failed read of the
	// whole list.
	At string `protobuf:"bytes,4,opt,name=at,proto3" json:"at,omitempty"`
	// verdict is the outcome in the actor's own word — hold, ship, rejected —
	// and is never interpreted across actors, for the reason state is not.
	Verdict string `protobuf:"bytes,5,opt,name=verdict,proto3" json:"verdict,omitempty"`
	// subject is the node id the decision was about.
	Subject string `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	// note is the decision in words.
	Note     string             `protobuf:"bytes,7,opt,name=note,proto3" json:"note,omitempty"`
	Grade    string             `protobuf:"bytes,8,opt,name=grade,proto3" json:"grade,omitempty"`
	Source   string             `protobuf:"bytes,9,opt,name=source,proto3" json:"source,omitempty"`
	Producer string             `protobuf:"bytes,10,opt,name=producer,proto3" json:"producer,omitempty"`
	State    string             `protobuf:"bytes,11,opt,name=state,proto3" json:"state,omitempty"`
	Why      string             `protobuf:"bytes,12,opt,name=why,proto3" json:"why,omitempty"`
	Premises []*DecisionPremise `protobuf:"bytes,13,rep,name=premises,proto3" json:"premises,omitempty"`
	// supersedes is what this decision replaced. Repeated rather than a single
	// id because a decision consolidating three earlier ones is ordinary, and a
	// field that could only hold one would make the ledger lie by arithmetic.
	Supersedes    []string `protobuf:"bytes,14,rep,name=supersedes,proto3" json:"supersedes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decision) Reset() {
	*x = Decision{}
	mi := &file_cortexdb_v1_decision_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decision) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decision) ProtoMessage() {}

func (x *Decision) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_decision_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decision.ProtoReflect.Descriptor instead.
func (*Decision) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_decision_proto_rawDescGZIP(), []int{1}
}

func (x *Decision) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Decision) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Decision) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Decision) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

func (x *Decision) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *Decision) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Decision) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Decision) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *Decision) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Decision) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *Decision) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Decision) GetWhy() string {
	if x != nil {
		return x.Why
	}
	return ""
}

func (x *Decision) GetPremises() []*DecisionPremise {
	if x != nil {
		return x.Premises
	}
	return nil
}

func (x *Decision) GetSupersedes() []string {
	if x != nil {
		return x.Supersedes
	}
	return nil
}

// RecordDecisionRequest writes why something was done.
type RecordDecisionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id names the decision. Empty mints one. Given, it makes the write
	// idempotent, which is what lets a caller replay a transcript without
	// doubling its ledger.
	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// actor is required: a decision nobody made is a note.
	Actor string `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	// note is required, for the reason a refused record needs a why — a ledger
	// entry a reader cannot act on is noise.
	Note    string `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	Verdict string `protobuf:"bytes,5,opt,name=verdict,proto3" json:"verdict,omitempty"`
	// subject must be a node that exists.
	Subject string `protobuf:"bytes,6,opt,name=subject,proto3" json:"subject,omitempty"`
	// premises are node ids and edge ids the decision rested on. Every one must
	// exist: a decision resting on a fact that does not exist is not a decision,
	// and accepting it would produce a chain that reads as evidence while
	// pointing at nothing. The whole request is refused and nothing is written.
	Premises []string `protobuf:"bytes,7,rep,name=premises,proto3" json:"premises,omitempty"`
	// supersedes must exist and must be a decision.
	Supersedes string `protobuf:"bytes,8,opt,name=supersedes,proto3" json:"supersedes,omitempty"`
	// at is RFC 3339. Empty means now.
	At string `protobuf:"bytes,9,opt,name=at,proto3" json:"at,omitempty"`
	// The contract keys a caller may override. The defaults are the case the
	// ledger exists for — a named person signing a decision, which is
	// established outside any producer and so is verified — and an agent
	// recording its own decision says so by setting producer and grade.
	Source   string `protobuf:"bytes,10,opt,name=source,proto3" json:"source,omitempty"`
	Producer string `protobuf:"bytes,11,opt,name=producer,proto3" json:"producer,omitempty"`
	Grade    string `protobuf:"bytes,12,opt,name=grade,proto3" json:"grade,omitempty"`
	State    string `protobuf:"bytes,13,opt,name=state,proto3" json:"state,omitempty"`
	// why is required by the contract when grade is held or refused.
	Why           string `protobuf:"bytes,14,opt,name=why,proto3" json:"why,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordDecisionRequest) Reset() {
	*x = RecordDecisionRequest{}
	mi := &file_cortexdb_v1_decision_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordDecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordDecisionRequest) ProtoMessage() {}

func (x *RecordDecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_decision_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordDecisionRequest.ProtoReflect.Descriptor instead.
func (*RecordDecisionRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_decision_proto_rawDescGZIP(), []int{2}
}

func (x *RecordDecisionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RecordDecisionRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *RecordDecisionRequest) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *RecordDecisionRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *RecordDecisionRequest) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *RecordDecisionRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *RecordDecisionRequest) GetPremises() []string {
	if x != nil {
		return x.Premises
	}
	return nil
}

func (x *RecordDecisionRequest) GetSupersedes() string {
	if x != nil {
		return x.Supersedes
	}
	return ""
}

func (x *RecordDecisionRequest) GetAt() string {
	if x != nil {
		return x.At
	}
	return ""
}

func (x *RecordDecisionRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RecordDecisionRequest) GetProducer() string {
	if x != nil {
		return x.Producer
	}
	return ""
}

func (x *RecordDecisionRequest) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *RecordDecisionRequest) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *RecordDecisionRequest) GetWhy() string {
	if x != nil {
		return x.Why
	}
	return ""
}

type RecordDecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Decision      *Decision              `protobuf:"bytes,1,opt,name=decision,proto3" json:"decision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordDecisionResponse) Reset() {
	*x = RecordDecisionResponse{}
	mi := &file_cortexdb_v1_decision_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordDecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordDecisionResponse) ProtoMessage() {}

func (x *RecordDecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_decision_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordDecisionResponse.ProtoReflect.Descriptor instead.
func (*RecordDecisionResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_decision_proto_rawDescGZIP(), []int{3}
}

func (x *RecordDecisionResponse) GetDecision() *Decision {
	if x != nil {
		return x.Decision
	}
	return nil
}

// DecisionChainRequest asks why one decision was made.
type DecisionChainRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// id, with or without the "decision:" prefix.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// max_depth is how many decision hops to follow. 0 takes the server's
	// default; the server also caps it, because a chain is a graph walk and a
	// graph is not a tree.
	MaxDepth      int32 `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionChainRequest) Reset() {
	*x = DecisionChainRequest{}
	mi := &file_cortexdb_v1_decision_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionChainRequest) ProtoMessage() {}

func (x *DecisionChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_decision_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionChainRequest.ProtoReflect.Descriptor instead.
func (*DecisionChainRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_decision_proto_rawDescGZIP(), []int{4}
}

func (x *DecisionChainRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DecisionChainRequest) GetMaxDepth() int32 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

// DecisionChainResponse is a decision and everything it stands on.
type DecisionChainResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Root  string                 `protobuf:"bytes,1,opt,name=root,proto3" json:"root,omitempty"`
	// decisions is the root first, then every decision reachable through
	// supersedes and through premises that are themselves decisions, breadth
	// first — so a truncated chain is truncated at the far end.
	Decisions []*Decision `protobuf:"bytes,2,rep,name=decisions,proto3" json:"decisions,omitempty"`
	Depth     int32       `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	// truncated says the depth bound stopped the walk with decisions still
	// unvisited. A chain that quietly stopped reads as a complete account of why
	// something was done, which is the one thing it must never do.
	Truncated     bool `protobuf:"varint,4,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionChainResponse) Reset() {
	*x = DecisionChainResponse{}
	mi := &file_cortexdb_v1_decision_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionChainResponse) ProtoMessage() {}

func (x *DecisionChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_decision_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionChainResponse.ProtoReflect.Descriptor instead.
func (*DecisionChainResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_decision_proto_rawDescGZIP(), []int{5}
}

func (x *DecisionChainResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *DecisionChainResponse) GetDecisions() []*Decision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *DecisionChainResponse) GetDepth() int32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *DecisionChainResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

// PrecedentsRequest asks what was decided this way before. Both kind and
// subject empty is refused rather than meaning "the whole ledger": a caller
// asking for every decision anybody ever made is not asking about a precedent,
// and on a shared brain that is other people's ledger.
type PrecedentsRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Kind    string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Subject string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	// exclude leaves one decision out — the one being decided now is not its own
	// precedent.
	Exclude string `protobuf:"bytes,3,opt,name=exclude,proto3" json:"exclude,omitempty"`
	// limit caps the rows. 0 takes the server's default.
	Limit         int32 `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrecedentsRequest) Reset() {
	*x = PrecedentsRequest{}
	mi := &file_cortexdb_v1_decision_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrecedentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecedentsRequest) ProtoMessage() {}

func (x *PrecedentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_decision_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecedentsRequest.ProtoReflect.Descriptor instead.
func (*PrecedentsRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_decision_proto_rawDescGZIP(), []int{6}
}

func (x *PrecedentsRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *PrecedentsRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PrecedentsRequest) GetExclude() string {
	if x != nil {
		return x.Exclude
	}
	return ""
}

func (x *PrecedentsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type PrecedentsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// decisions are newest first.
	Decisions []*Decision `protobuf:"bytes,1,rep,name=decisions,proto3" json:"decisions,omitempty"`
	Count     int32       `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	// truncated says the limit cut the list short, so "3 precedents" is never
	// mistaken for "only 3 precedents".
	Truncated     bool `protobuf:"varint,3,opt,name=truncated,proto3" json:"truncated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrecedentsResponse) Reset() {
	*x = PrecedentsResponse{}
	mi := &file_cortexdb_v1_decision_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrecedentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrecedentsResponse) ProtoMessage() {}

func (x *PrecedentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_decision_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrecedentsResponse.ProtoReflect.Descriptor instead.
func (*PrecedentsResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_decision_proto_rawDescGZIP(), []int{7}
}

func (x *PrecedentsResponse) GetDecisions() []*Decision {
	if x != nil {
		return x.Decisions
	}
	return nil
}

func (x *PrecedentsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *PrecedentsResponse) GetTruncated() bool {
	if x != nil {
		return x.Truncated
	}
	return false
}

var File_cortexdb_v1_decision_proto protoreflect.FileDescriptor

const file_cortexdb_v1_decision_proto_rawDesc = "" +
	"\n" +
	"\x1acortexdb/v1/decision.proto\x12\vcortexdb.v1\"\xeb\x01\n" +
	"\x0fDecisionPremise\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04edge\x18\x02 \x01(\bR\x04edge\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04from\x18\x05 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x06 \x01(\tR\x02to\x12\x1a\n" +
	"\bdecision\x18\a \x01(\bR\bdecision\x12\x14\n" +
	"\x05grade\x18\b \x01(\tR\x05grade\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x12\x18\n" +
	"\amissing\x18\n" +
	" \x01(\bR\amissing\"\xe8\x02\n" +
	"\bDecision\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x0e\n" +
	"\x02at\x18\x04 \x01(\tR\x02at\x12\x18\n" +
	"\averdict\x18\x05 \x01(\tR\averdict\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12\x12\n" +
	"\x04note\x18\a \x01(\tR\x04note\x12\x14\n" +
	"\x05grade\x18\b \x01(\tR\x05grade\x12\x16\n" +
	"\x06source\x18\t \x01(\tR\x06source\x12\x1a\n" +
	"\bproducer\x18\n" +
	" \x01(\tR\bproducer\x12\x14\n" +
	"\x05state\x18\v \x01(\tR\x05state\x12\x10\n" +
	"\x03why\x18\f \x01(\tR\x03why\x128\n" +
	"\bpremises\x18\r \x03(\v2\x1c.cortexdb.v1.DecisionPremiseR\bpremises\x12\x1e\n" +
	"\n" +
	"supersedes\x18\x0e \x03(\tR\n" +
	"supersedes\"\xd7\x02\n" +
	"\x15RecordDecisionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x12\x18\n" +
	"\averdict\x18\x05 \x01(\tR\averdict\x12\x18\n" +
	"\asubject\x18\x06 \x01(\tR\asubject\x12\x1a\n" +
	"\bpremises\x18\a \x03(\tR\bpremises\x12\x1e\n" +
	"\n" +
	"supersedes\x18\b \x01(\tR\n" +
	"supersedes\x12\x0e\n" +
	"\x02at\x18\t \x01(\tR\x02at\x12\x16\n" +
	"\x06source\x18\n" +
	" \x01(\tR\x06source\x12\x1a\n" +
	"\bproducer\x18\v \x01(\tR\bproducer\x12\x14\n" +
	"\x05grade\x18\f \x01(\tR\x05grade\x12\x14\n" +
	"\x05state\x18\r \x01(\tR\x05state\x12\x10\n" +
	"\x03why\x18\x0e \x01(\tR\x03why\"K\n" +
	"\x16RecordDecisionResponse\x121\n" +
	"\bdecision\x18\x01 \x01(\v2\x15.cortexdb.v1.DecisionR\bdecision\"C\n" +
	"\x14DecisionChainRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\x05R\bmaxDepth\"\x94\x01\n" +
	"\x15DecisionChainResponse\x12\x12\n" +
	"\x04root\x18\x01 \x01(\tR\x04root\x123\n" +
	"\tdecisions\x18\x02 \x03(\v2\x15.cortexdb.v1.DecisionR\tdecisions\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\x05R\x05depth\x12\x1c\n" +
	"\ttruncated\x18\x04 \x01(\bR\ttruncated\"q\n" +
	"\x11PrecedentsRequest\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x18\n" +
	"\aexclude\x18\x03 \x01(\tR\aexclude\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"}\n" +
	"\x12PrecedentsResponse\x123\n" +
	"\tdecisions\x18\x01 \x03(\v2\x15.cortexdb.v1.DecisionR\tdecisions\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x1c\n" +
	"\ttruncated\x18\x03 \x01(\bR\ttruncated2\x93\x02\n" +
	"\x0fDecisionService\x12Y\n" +
	"\x0eRecordDecision\x12\".cortexdb.v1.RecordDecisionRequest\x1a#.cortexdb.v1.RecordDecisionResponse\x12V\n" +
	"\rDecisionChain\x12!.cortexdb.v1.DecisionChainRequest\x1a\".cortexdb.v1.DecisionChainResponse\x12M\n" +
	"\n" +
	"Precedents\x12\x1e.cortexdb.v1.PrecedentsRequest\x1a\x1f.cortexdb.v1.PrecedentsResponseB4Z2github.com/liliang-cn/cortexdb/v2/pkg/rpc/v1;rpcv1b\x06proto3"

var (
	file_cortexdb_v1_decision_proto_rawDescOnce sync.Once
	file_cortexdb_v1_decision_proto_rawDescData []byte
)

func file_cortexdb_v1_decision_proto_rawDescGZIP() []byte {
	file_cortexdb_v1_decision_proto_rawDescOnce.Do(func() {
		file_cortexdb_v1_decision_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortexdb_v1_decision_proto_rawDesc), len(file_cortexdb_v1_decision_proto_rawDesc)))
	})
	return file_cortexdb_v1_decision_proto_rawDescData
}

var file_cortexdb_v1_decision_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_cortexdb_v1_decision_proto_goTypes = []any{
	(*DecisionPremise)(nil),        // 0: cortexdb.v1.DecisionPremise
	(*Decision)(nil),               // 1: cortexdb.v1.Decision
	(*RecordDecisionRequest)(nil),  // 2: cortexdb.v1.RecordDecisionRequest
	(*RecordDecisionResponse)(nil), // 3: cortexdb.v1.RecordDecisionResponse
	(*DecisionChainRequest)(nil),   // 4: cortexdb.v1.DecisionChainRequest
	(*DecisionChainResponse)(nil),  // 5: cortexdb.v1.DecisionChainResponse
	(*PrecedentsRequest)(nil),      // 6: cortexdb.v1.PrecedentsRequest
	(*PrecedentsResponse)(nil),     // 7: cortexdb.v1.PrecedentsResponse
}
var file_cortexdb_v1_decision_proto_depIdxs = []int32{
	0, // 0: cortexdb.v1.Decision.premises:type_name -> cortexdb.v1.DecisionPremise
	1, // 1: cortexdb.v1.RecordDecisionResponse.decision:type_name -> cortexdb.v1.Decision
	1, // 2: cortexdb.v1.DecisionChainResponse.decisions:type_name -> cortexdb.v1.Decision
	1, // 3: cortexdb.v1.PrecedentsResponse.decisions:type_name -> cortexdb.v1.Decision
	2, // 4: cortexdb.v1.DecisionService.RecordDecision:input_type -> cortexdb.v1.RecordDecisionRequest
	4, // 5: cortexdb.v1.DecisionService.DecisionChain:input_type -> cortexdb.v1.DecisionChainRequest
	6, // 6: cortexdb.v1.DecisionService.Precedents:input_type -> cortexdb.v1.PrecedentsRequest
	3, // 7: cortexdb.v1.DecisionService.RecordDecision:output_type -> cortexdb.v1.RecordDecisionResponse
	5, // 8: cortexdb.v1.DecisionService.DecisionChain:output_type -> cortexdb.v1.DecisionChainResponse
	7, // 9: cortexdb.v1.DecisionService.Precedents:output_type -> cortexdb.v1.PrecedentsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_cortexdb_v1_decision_proto_init() }
func file_cortexdb_v1_decision_proto_init() {
	if File_cortexdb_v1_decision_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortexdb_v1_decision_proto_rawDesc), len(file_cortexdb_v1_decision_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cortexdb_v1_decision_proto_goTypes,
		DependencyIndexes: file_cortexdb_v1_decision_proto_depIdxs,
		MessageInfos:      file_cortexdb_v1_decision_proto_msgTypes,
	}.Build()
	File_cortexdb_v1_decision_proto = out.File
	file_cortexdb_v1_decision_proto_goTypes = nil
	file_cortexdb_v1_decision_proto_depIdxs = nil
}
