// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.1
// source: cortexdb/v1/graph.proto

package rpcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KnowledgeGraphService_UpsertNamespace_FullMethodName       = "/cortexdb.v1.KnowledgeGraphService/UpsertNamespace"
	KnowledgeGraphService_ListNamespaces_FullMethodName        = "/cortexdb.v1.KnowledgeGraphService/ListNamespaces"
	KnowledgeGraphService_UpsertKnowledgeGraph_FullMethodName  = "/cortexdb.v1.KnowledgeGraphService/UpsertKnowledgeGraph"
	KnowledgeGraphService_FindKnowledgeGraph_FullMethodName    = "/cortexdb.v1.KnowledgeGraphService/FindKnowledgeGraph"
	KnowledgeGraphService_DeleteKnowledgeGraph_FullMethodName  = "/cortexdb.v1.KnowledgeGraphService/DeleteKnowledgeGraph"
	KnowledgeGraphService_ImportKnowledgeGraph_FullMethodName  = "/cortexdb.v1.KnowledgeGraphService/ImportKnowledgeGraph"
	KnowledgeGraphService_ExportKnowledgeGraph_FullMethodName  = "/cortexdb.v1.KnowledgeGraphService/ExportKnowledgeGraph"
	KnowledgeGraphService_QuerySparql_FullMethodName           = "/cortexdb.v1.KnowledgeGraphService/QuerySparql"
	KnowledgeGraphService_ValidateShacl_FullMethodName         = "/cortexdb.v1.KnowledgeGraphService/ValidateShacl"
	KnowledgeGraphService_RefreshInference_FullMethodName      = "/cortexdb.v1.KnowledgeGraphService/RefreshInference"
	KnowledgeGraphService_SummarizeInference_FullMethodName    = "/cortexdb.v1.KnowledgeGraphService/SummarizeInference"
	KnowledgeGraphService_ExplainInference_FullMethodName      = "/cortexdb.v1.KnowledgeGraphService/ExplainInference"
	KnowledgeGraphService_ExplainInferenceMatch_FullMethodName = "/cortexdb.v1.KnowledgeGraphService/ExplainInferenceMatch"
	KnowledgeGraphService_SaveOntologySchema_FullMethodName    = "/cortexdb.v1.KnowledgeGraphService/SaveOntologySchema"
	KnowledgeGraphService_GetOntologySchema_FullMethodName     = "/cortexdb.v1.KnowledgeGraphService/GetOntologySchema"
	KnowledgeGraphService_ListOntologySchemas_FullMethodName   = "/cortexdb.v1.KnowledgeGraphService/ListOntologySchemas"
	KnowledgeGraphService_DeleteOntologySchema_FullMethodName  = "/cortexdb.v1.KnowledgeGraphService/DeleteOntologySchema"
)

// KnowledgeGraphServiceClient is the client API for KnowledgeGraphService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KnowledgeGraphServiceClient interface {
	UpsertNamespace(ctx context.Context, in *UpsertNamespaceRequest, opts ...grpc.CallOption) (*UpsertNamespaceResponse, error)
	ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error)
	UpsertKnowledgeGraph(ctx context.Context, in *UpsertKnowledgeGraphRequest, opts ...grpc.CallOption) (*UpsertKnowledgeGraphResponse, error)
	FindKnowledgeGraph(ctx context.Context, in *FindKnowledgeGraphRequest, opts ...grpc.CallOption) (*FindKnowledgeGraphResponse, error)
	DeleteKnowledgeGraph(ctx context.Context, in *DeleteKnowledgeGraphRequest, opts ...grpc.CallOption) (*DeleteKnowledgeGraphResponse, error)
	ImportKnowledgeGraph(ctx context.Context, in *ImportKnowledgeGraphRequest, opts ...grpc.CallOption) (*ImportKnowledgeGraphResponse, error)
	ExportKnowledgeGraph(ctx context.Context, in *ExportKnowledgeGraphRequest, opts ...grpc.CallOption) (*ExportKnowledgeGraphResponse, error)
	QuerySparql(ctx context.Context, in *QuerySparqlRequest, opts ...grpc.CallOption) (*QuerySparqlResponse, error)
	ValidateShacl(ctx context.Context, in *ValidateShaclRequest, opts ...grpc.CallOption) (*ValidateShaclResponse, error)
	RefreshInference(ctx context.Context, in *RefreshInferenceRequest, opts ...grpc.CallOption) (*RefreshInferenceResponse, error)
	SummarizeInference(ctx context.Context, in *SummarizeInferenceRequest, opts ...grpc.CallOption) (*SummarizeInferenceResponse, error)
	ExplainInference(ctx context.Context, in *ExplainInferenceRequest, opts ...grpc.CallOption) (*ExplainInferenceResponse, error)
	ExplainInferenceMatch(ctx context.Context, in *ExplainInferenceMatchRequest, opts ...grpc.CallOption) (*ExplainInferenceMatchResponse, error)
	SaveOntologySchema(ctx context.Context, in *SaveOntologySchemaRequest, opts ...grpc.CallOption) (*SaveOntologySchemaResponse, error)
	GetOntologySchema(ctx context.Context, in *GetOntologySchemaRequest, opts ...grpc.CallOption) (*GetOntologySchemaResponse, error)
	ListOntologySchemas(ctx context.Context, in *ListOntologySchemasRequest, opts ...grpc.CallOption) (*ListOntologySchemasResponse, error)
	DeleteOntologySchema(ctx context.Context, in *DeleteOntologySchemaRequest, opts ...grpc.CallOption) (*DeleteOntologySchemaResponse, error)
}

type knowledgeGraphServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKnowledgeGraphServiceClient(cc grpc.ClientConnInterface) KnowledgeGraphServiceClient {
	return &knowledgeGraphServiceClient{cc}
}

func (c *knowledgeGraphServiceClient) UpsertNamespace(ctx context.Context, in *UpsertNamespaceRequest, opts ...grpc.CallOption) (*UpsertNamespaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertNamespaceResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_UpsertNamespace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) ListNamespaces(ctx context.Context, in *ListNamespacesRequest, opts ...grpc.CallOption) (*ListNamespacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNamespacesResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_ListNamespaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) UpsertKnowledgeGraph(ctx context.Context, in *UpsertKnowledgeGraphRequest, opts ...grpc.CallOption) (*UpsertKnowledgeGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertKnowledgeGraphResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_UpsertKnowledgeGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) FindKnowledgeGraph(ctx context.Context, in *FindKnowledgeGraphRequest, opts ...grpc.CallOption) (*FindKnowledgeGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindKnowledgeGraphResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_FindKnowledgeGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) DeleteKnowledgeGraph(ctx context.Context, in *DeleteKnowledgeGraphRequest, opts ...grpc.CallOption) (*DeleteKnowledgeGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteKnowledgeGraphResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_DeleteKnowledgeGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) ImportKnowledgeGraph(ctx context.Context, in *ImportKnowledgeGraphRequest, opts ...grpc.CallOption) (*ImportKnowledgeGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportKnowledgeGraphResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_ImportKnowledgeGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) ExportKnowledgeGraph(ctx context.Context, in *ExportKnowledgeGraphRequest, opts ...grpc.CallOption) (*ExportKnowledgeGraphResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportKnowledgeGraphResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_ExportKnowledgeGraph_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) QuerySparql(ctx context.Context, in *QuerySparqlRequest, opts ...grpc.CallOption) (*QuerySparqlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QuerySparqlResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_QuerySparql_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) ValidateShacl(ctx context.Context, in *ValidateShaclRequest, opts ...grpc.CallOption) (*ValidateShaclResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateShaclResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_ValidateShacl_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) RefreshInference(ctx context.Context, in *RefreshInferenceRequest, opts ...grpc.CallOption) (*RefreshInferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshInferenceResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_RefreshInference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) SummarizeInference(ctx context.Context, in *SummarizeInferenceRequest, opts ...grpc.CallOption) (*SummarizeInferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SummarizeInferenceResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_SummarizeInference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) ExplainInference(ctx context.Context, in *ExplainInferenceRequest, opts ...grpc.CallOption) (*ExplainInferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainInferenceResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_ExplainInference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) ExplainInferenceMatch(ctx context.Context, in *ExplainInferenceMatchRequest, opts ...grpc.CallOption) (*ExplainInferenceMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExplainInferenceMatchResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_ExplainInferenceMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) SaveOntologySchema(ctx context.Context, in *SaveOntologySchemaRequest, opts ...grpc.CallOption) (*SaveOntologySchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveOntologySchemaResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_SaveOntologySchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) GetOntologySchema(ctx context.Context, in *GetOntologySchemaRequest, opts ...grpc.CallOption) (*GetOntologySchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOntologySchemaResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_GetOntologySchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) ListOntologySchemas(ctx context.Context, in *ListOntologySchemasRequest, opts ...grpc.CallOption) (*ListOntologySchemasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListOntologySchemasResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_ListOntologySchemas_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *knowledgeGraphServiceClient) DeleteOntologySchema(ctx context.Context, in *DeleteOntologySchemaRequest, opts ...grpc.CallOption) (*DeleteOntologySchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteOntologySchemaResponse)
	err := c.cc.Invoke(ctx, KnowledgeGraphService_DeleteOntologySchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KnowledgeGraphServiceServer is the server API for KnowledgeGraphService service.
// All implementations must embed UnimplementedKnowledgeGraphServiceServer
// for forward compatibility.
type KnowledgeGraphServiceServer interface {
	UpsertNamespace(context.Context, *UpsertNamespaceRequest) (*UpsertNamespaceResponse, error)
	ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error)
	UpsertKnowledgeGraph(context.Context, *UpsertKnowledgeGraphRequest) (*UpsertKnowledgeGraphResponse, error)
	FindKnowledgeGraph(context.Context, *FindKnowledgeGraphRequest) (*FindKnowledgeGraphResponse, error)
	DeleteKnowledgeGraph(context.Context, *DeleteKnowledgeGraphRequest) (*DeleteKnowledgeGraphResponse, error)
	ImportKnowledgeGraph(context.Context, *ImportKnowledgeGraphRequest) (*ImportKnowledgeGraphResponse, error)
	ExportKnowledgeGraph(context.Context, *ExportKnowledgeGraphRequest) (*ExportKnowledgeGraphResponse, error)
	QuerySparql(context.Context, *QuerySparqlRequest) (*QuerySparqlResponse, error)
	ValidateShacl(context.Context, *ValidateShaclRequest) (*ValidateShaclResponse, error)
	RefreshInference(context.Context, *RefreshInferenceRequest) (*RefreshInferenceResponse, error)
	SummarizeInference(context.Context, *SummarizeInferenceRequest) (*SummarizeInferenceResponse, error)
	ExplainInference(context.Context, *ExplainInferenceRequest) (*ExplainInferenceResponse, error)
	ExplainInferenceMatch(context.Context, *ExplainInferenceMatchRequest) (*ExplainInferenceMatchResponse, error)
	SaveOntologySchema(context.Context, *SaveOntologySchemaRequest) (*SaveOntologySchemaResponse, error)
	GetOntologySchema(context.Context, *GetOntologySchemaRequest) (*GetOntologySchemaResponse, error)
	ListOntologySchemas(context.Context, *ListOntologySchemasRequest) (*ListOntologySchemasResponse, error)
	DeleteOntologySchema(context.Context, *DeleteOntologySchemaRequest) (*DeleteOntologySchemaResponse, error)
	mustEmbedUnimplementedKnowledgeGraphServiceServer()
}

// UnimplementedKnowledgeGraphServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKnowledgeGraphServiceServer struct{}

func (UnimplementedKnowledgeGraphServiceServer) UpsertNamespace(context.Context, *UpsertNamespaceRequest) (*UpsertNamespaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertNamespace not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) ListNamespaces(context.Context, *ListNamespacesRequest) (*ListNamespacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNamespaces not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) UpsertKnowledgeGraph(context.Context, *UpsertKnowledgeGraphRequest) (*UpsertKnowledgeGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertKnowledgeGraph not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) FindKnowledgeGraph(context.Context, *FindKnowledgeGraphRequest) (*FindKnowledgeGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindKnowledgeGraph not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) DeleteKnowledgeGraph(context.Context, *DeleteKnowledgeGraphRequest) (*DeleteKnowledgeGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKnowledgeGraph not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) ImportKnowledgeGraph(context.Context, *ImportKnowledgeGraphRequest) (*ImportKnowledgeGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportKnowledgeGraph not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) ExportKnowledgeGraph(context.Context, *ExportKnowledgeGraphRequest) (*ExportKnowledgeGraphResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportKnowledgeGraph not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) QuerySparql(context.Context, *QuerySparqlRequest) (*QuerySparqlResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuerySparql not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) ValidateShacl(context.Context, *ValidateShaclRequest) (*ValidateShaclResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateShacl not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) RefreshInference(context.Context, *RefreshInferenceRequest) (*RefreshInferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RefreshInference not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) SummarizeInference(context.Context, *SummarizeInferenceRequest) (*SummarizeInferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SummarizeInference not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) ExplainInference(context.Context, *ExplainInferenceRequest) (*ExplainInferenceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExplainInference not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) ExplainInferenceMatch(context.Context, *ExplainInferenceMatchRequest) (*ExplainInferenceMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExplainInferenceMatch not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) SaveOntologySchema(context.Context, *SaveOntologySchemaRequest) (*SaveOntologySchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveOntologySchema not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) GetOntologySchema(context.Context, *GetOntologySchemaRequest) (*GetOntologySchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOntologySchema not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) ListOntologySchemas(context.Context, *ListOntologySchemasRequest) (*ListOntologySchemasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListOntologySchemas not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) DeleteOntologySchema(context.Context, *DeleteOntologySchemaRequest) (*DeleteOntologySchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteOntologySchema not implemented")
}
func (UnimplementedKnowledgeGraphServiceServer) mustEmbedUnimplementedKnowledgeGraphServiceServer() {}
func (UnimplementedKnowledgeGraphServiceServer) testEmbeddedByValue()                               {}

// UnsafeKnowledgeGraphServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KnowledgeGraphServiceServer will
// result in compilation errors.
type UnsafeKnowledgeGraphServiceServer interface {
	mustEmbedUnimplementedKnowledgeGraphServiceServer()
}

func RegisterKnowledgeGraphServiceServer(s grpc.ServiceRegistrar, srv KnowledgeGraphServiceServer) {
	// If the following call pancis, it indicates UnimplementedKnowledgeGraphServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KnowledgeGraphService_ServiceDesc, srv)
}

func _KnowledgeGraphService_UpsertNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertNamespaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).UpsertNamespace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_UpsertNamespace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).UpsertNamespace(ctx, req.(*UpsertNamespaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_ListNamespaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNamespacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).ListNamespaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_ListNamespaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).ListNamespaces(ctx, req.(*ListNamespacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_UpsertKnowledgeGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertKnowledgeGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).UpsertKnowledgeGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_UpsertKnowledgeGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).UpsertKnowledgeGraph(ctx, req.(*UpsertKnowledgeGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_FindKnowledgeGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindKnowledgeGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).FindKnowledgeGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_FindKnowledgeGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).FindKnowledgeGraph(ctx, req.(*FindKnowledgeGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_DeleteKnowledgeGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKnowledgeGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).DeleteKnowledgeGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_DeleteKnowledgeGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).DeleteKnowledgeGraph(ctx, req.(*DeleteKnowledgeGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_ImportKnowledgeGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportKnowledgeGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).ImportKnowledgeGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_ImportKnowledgeGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).ImportKnowledgeGraph(ctx, req.(*ImportKnowledgeGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_ExportKnowledgeGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportKnowledgeGraphRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).ExportKnowledgeGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_ExportKnowledgeGraph_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).ExportKnowledgeGraph(ctx, req.(*ExportKnowledgeGraphRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_QuerySparql_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySparqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).QuerySparql(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_QuerySparql_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).QuerySparql(ctx, req.(*QuerySparqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_ValidateShacl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateShaclRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).ValidateShacl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_ValidateShacl_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).ValidateShacl(ctx, req.(*ValidateShaclRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_RefreshInference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshInferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).RefreshInference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_RefreshInference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).RefreshInference(ctx, req.(*RefreshInferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_SummarizeInference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SummarizeInferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).SummarizeInference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_SummarizeInference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).SummarizeInference(ctx, req.(*SummarizeInferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_ExplainInference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainInferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).ExplainInference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_ExplainInference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).ExplainInference(ctx, req.(*ExplainInferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_ExplainInferenceMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExplainInferenceMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).ExplainInferenceMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_ExplainInferenceMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).ExplainInferenceMatch(ctx, req.(*ExplainInferenceMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_SaveOntologySchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveOntologySchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).SaveOntologySchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_SaveOntologySchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).SaveOntologySchema(ctx, req.(*SaveOntologySchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_GetOntologySchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOntologySchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).GetOntologySchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_GetOntologySchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).GetOntologySchema(ctx, req.(*GetOntologySchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_ListOntologySchemas_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOntologySchemasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).ListOntologySchemas(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_ListOntologySchemas_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).ListOntologySchemas(ctx, req.(*ListOntologySchemasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KnowledgeGraphService_DeleteOntologySchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOntologySchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KnowledgeGraphServiceServer).DeleteOntologySchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KnowledgeGraphService_DeleteOntologySchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KnowledgeGraphServiceServer).DeleteOntologySchema(ctx, req.(*DeleteOntologySchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KnowledgeGraphService_ServiceDesc is the grpc.ServiceDesc for KnowledgeGraphService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KnowledgeGraphService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cortexdb.v1.KnowledgeGraphService",
	HandlerType: (*KnowledgeGraphServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertNamespace",
			Handler:    _KnowledgeGraphService_UpsertNamespace_Handler,
		},
		{
			MethodName: "ListNamespaces",
			Handler:    _KnowledgeGraphService_ListNamespaces_Handler,
		},
		{
			MethodName: "UpsertKnowledgeGraph",
			Handler:    _KnowledgeGraphService_UpsertKnowledgeGraph_Handler,
		},
		{
			MethodName: "FindKnowledgeGraph",
			Handler:    _KnowledgeGraphService_FindKnowledgeGraph_Handler,
		},
		{
			MethodName: "DeleteKnowledgeGraph",
			Handler:    _KnowledgeGraphService_DeleteKnowledgeGraph_Handler,
		},
		{
			MethodName: "ImportKnowledgeGraph",
			Handler:    _KnowledgeGraphService_ImportKnowledgeGraph_Handler,
		},
		{
			MethodName: "ExportKnowledgeGraph",
			Handler:    _KnowledgeGraphService_ExportKnowledgeGraph_Handler,
		},
		{
			MethodName: "QuerySparql",
			Handler:    _KnowledgeGraphService_QuerySparql_Handler,
		},
		{
			MethodName: "ValidateShacl",
			Handler:    _KnowledgeGraphService_ValidateShacl_Handler,
		},
		{
			MethodName: "RefreshInference",
			Handler:    _KnowledgeGraphService_RefreshInference_Handler,
		},
		{
			MethodName: "SummarizeInference",
			Handler:    _KnowledgeGraphService_SummarizeInference_Handler,
		},
		{
			MethodName: "ExplainInference",
			Handler:    _KnowledgeGraphService_ExplainInference_Handler,
		},
		{
			MethodName: "ExplainInferenceMatch",
			Handler:    _KnowledgeGraphService_ExplainInferenceMatch_Handler,
		},
		{
			MethodName: "SaveOntologySchema",
			Handler:    _KnowledgeGraphService_SaveOntologySchema_Handler,
		},
		{
			MethodName: "GetOntologySchema",
			Handler:    _KnowledgeGraphService_GetOntologySchema_Handler,
		},
		{
			MethodName: "ListOntologySchemas",
			Handler:    _KnowledgeGraphService_ListOntologySchemas_Handler,
		},
		{
			MethodName: "DeleteOntologySchema",
			Handler:    _KnowledgeGraphService_DeleteOntologySchema_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cortexdb/v1/graph.proto",
}
