// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.1
// source: cortexdb/v1/graphrag.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InsertGraphDocumentRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title    string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content  string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Metadata map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// ingest options (GraphRAGIngestOptions minus Extractor)
	Collection    string `protobuf:"bytes,5,opt,name=collection,proto3" json:"collection,omitempty"`
	ChunkSize     int32  `protobuf:"varint,6,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	ChunkOverlap  int32  `protobuf:"varint,7,opt,name=chunk_overlap,json=chunkOverlap,proto3" json:"chunk_overlap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertGraphDocumentRequest) Reset() {
	*x = InsertGraphDocumentRequest{}
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertGraphDocumentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertGraphDocumentRequest) ProtoMessage() {}

func (x *InsertGraphDocumentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertGraphDocumentRequest.ProtoReflect.Descriptor instead.
func (*InsertGraphDocumentRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_graphrag_proto_rawDescGZIP(), []int{0}
}

func (x *InsertGraphDocumentRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertGraphDocumentRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InsertGraphDocumentRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InsertGraphDocumentRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *InsertGraphDocumentRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *InsertGraphDocumentRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *InsertGraphDocumentRequest) GetChunkOverlap() int32 {
	if x != nil {
		return x.ChunkOverlap
	}
	return 0
}

type InsertGraphDocumentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DocumentNodeId string                 `protobuf:"bytes,1,opt,name=document_node_id,json=documentNodeId,proto3" json:"document_node_id,omitempty"`
	ChunkNodeIds   []string               `protobuf:"bytes,2,rep,name=chunk_node_ids,json=chunkNodeIds,proto3" json:"chunk_node_ids,omitempty"`
	EntityNodeIds  []string               `protobuf:"bytes,3,rep,name=entity_node_ids,json=entityNodeIds,proto3" json:"entity_node_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *InsertGraphDocumentResponse) Reset() {
	*x = InsertGraphDocumentResponse{}
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertGraphDocumentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertGraphDocumentResponse) ProtoMessage() {}

func (x *InsertGraphDocumentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertGraphDocumentResponse.ProtoReflect.Descriptor instead.
func (*InsertGraphDocumentResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_graphrag_proto_rawDescGZIP(), []int{1}
}

func (x *InsertGraphDocumentResponse) GetDocumentNodeId() string {
	if x != nil {
		return x.DocumentNodeId
	}
	return ""
}

func (x *InsertGraphDocumentResponse) GetChunkNodeIds() []string {
	if x != nil {
		return x.ChunkNodeIds
	}
	return nil
}

func (x *InsertGraphDocumentResponse) GetEntityNodeIds() []string {
	if x != nil {
		return x.EntityNodeIds
	}
	return nil
}

type SearchGraphRagRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Query               string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Collection          string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	TopK                int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	MaxHops             int32                  `protobuf:"varint,4,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	MaxRelatedChunks    int32                  `protobuf:"varint,5,opt,name=max_related_chunks,json=maxRelatedChunks,proto3" json:"max_related_chunks,omitempty"`
	MaxContextChunks    int32                  `protobuf:"varint,6,opt,name=max_context_chunks,json=maxContextChunks,proto3" json:"max_context_chunks,omitempty"`
	MaxContextChars     int32                  `protobuf:"varint,7,opt,name=max_context_chars,json=maxContextChars,proto3" json:"max_context_chars,omitempty"`
	PerDocumentLimit    int32                  `protobuf:"varint,8,opt,name=per_document_limit,json=perDocumentLimit,proto3" json:"per_document_limit,omitempty"`
	Rerank              bool                   `protobuf:"varint,9,opt,name=rerank,proto3" json:"rerank,omitempty"`
	DisableRerank       bool                   `protobuf:"varint,10,opt,name=disable_rerank,json=disableRerank,proto3" json:"disable_rerank,omitempty"`
	DiversityLambda     float64                `protobuf:"fixed64,11,opt,name=diversity_lambda,json=diversityLambda,proto3" json:"diversity_lambda,omitempty"`
	DisableGraph        bool                   `protobuf:"varint,12,opt,name=disable_graph,json=disableGraph,proto3" json:"disable_graph,omitempty"`
	RetrievalMode       string                 `protobuf:"bytes,13,opt,name=retrieval_mode,json=retrievalMode,proto3" json:"retrieval_mode,omitempty"`
	GraphLight          bool                   `protobuf:"varint,14,opt,name=graph_light,json=graphLight,proto3" json:"graph_light,omitempty"`
	MaxExpansionSeeds   int32                  `protobuf:"varint,15,opt,name=max_expansion_seeds,json=maxExpansionSeeds,proto3" json:"max_expansion_seeds,omitempty"`
	MaxTraversalNodes   int32                  `protobuf:"varint,16,opt,name=max_traversal_nodes,json=maxTraversalNodes,proto3" json:"max_traversal_nodes,omitempty"`
	MaxEntitiesPerChunk int32                  `protobuf:"varint,17,opt,name=max_entities_per_chunk,json=maxEntitiesPerChunk,proto3" json:"max_entities_per_chunk,omitempty"`
	Plan                *RetrievalPlan         `protobuf:"bytes,18,opt,name=plan,proto3,oneof" json:"plan,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SearchGraphRagRequest) Reset() {
	*x = SearchGraphRagRequest{}
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGraphRagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGraphRagRequest) ProtoMessage() {}

func (x *SearchGraphRagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGraphRagRequest.ProtoReflect.Descriptor instead.
func (*SearchGraphRagRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_graphrag_proto_rawDescGZIP(), []int{2}
}

func (x *SearchGraphRagRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchGraphRagRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchGraphRagRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchGraphRagRequest) GetMaxHops() int32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *SearchGraphRagRequest) GetMaxRelatedChunks() int32 {
	if x != nil {
		return x.MaxRelatedChunks
	}
	return 0
}

func (x *SearchGraphRagRequest) GetMaxContextChunks() int32 {
	if x != nil {
		return x.MaxContextChunks
	}
	return 0
}

func (x *SearchGraphRagRequest) GetMaxContextChars() int32 {
	if x != nil {
		return x.MaxContextChars
	}
	return 0
}

func (x *SearchGraphRagRequest) GetPerDocumentLimit() int32 {
	if x != nil {
		return x.PerDocumentLimit
	}
	return 0
}

func (x *SearchGraphRagRequest) GetRerank() bool {
	if x != nil {
		return x.Rerank
	}
	return false
}

func (x *SearchGraphRagRequest) GetDisableRerank() bool {
	if x != nil {
		return x.DisableRerank
	}
	return false
}

func (x *SearchGraphRagRequest) GetDiversityLambda() float64 {
	if x != nil {
		return x.DiversityLambda
	}
	return 0
}

func (x *SearchGraphRagRequest) GetDisableGraph() bool {
	if x != nil {
		return x.DisableGraph
	}
	return false
}

func (x *SearchGraphRagRequest) GetRetrievalMode() string {
	if x != nil {
		return x.RetrievalMode
	}
	return ""
}

func (x *SearchGraphRagRequest) GetGraphLight() bool {
	if x != nil {
		return x.GraphLight
	}
	return false
}

func (x *SearchGraphRagRequest) GetMaxExpansionSeeds() int32 {
	if x != nil {
		return x.MaxExpansionSeeds
	}
	return 0
}

func (x *SearchGraphRagRequest) GetMaxTraversalNodes() int32 {
	if x != nil {
		return x.MaxTraversalNodes
	}
	return 0
}

func (x *SearchGraphRagRequest) GetMaxEntitiesPerChunk() int32 {
	if x != nil {
		return x.MaxEntitiesPerChunk
	}
	return 0
}

func (x *SearchGraphRagRequest) GetPlan() *RetrievalPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type SearchGraphRagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Plan          *RetrievalPlan         `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	Decision      *RetrievalDecision     `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	Chunks        []*GraphRagChunkResult `protobuf:"bytes,4,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Entities      []string               `protobuf:"bytes,5,rep,name=entities,proto3" json:"entities,omitempty"`
	Context       string                 `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGraphRagResponse) Reset() {
	*x = SearchGraphRagResponse{}
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGraphRagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGraphRagResponse) ProtoMessage() {}

func (x *SearchGraphRagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGraphRagResponse.ProtoReflect.Descriptor instead.
func (*SearchGraphRagResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_graphrag_proto_rawDescGZIP(), []int{3}
}

func (x *SearchGraphRagResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchGraphRagResponse) GetPlan() *RetrievalPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *SearchGraphRagResponse) GetDecision() *RetrievalDecision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *SearchGraphRagResponse) GetChunks() []*GraphRagChunkResult {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *SearchGraphRagResponse) GetEntities() []string {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SearchGraphRagResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

type InsertTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertTextRequest) Reset() {
	*x = InsertTextRequest{}
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTextRequest) ProtoMessage() {}

func (x *InsertTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTextRequest.ProtoReflect.Descriptor instead.
func (*InsertTextRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_graphrag_proto_rawDescGZIP(), []int{4}
}

func (x *InsertTextRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InsertTextRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *InsertTextRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InsertTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertTextResponse) Reset() {
	*x = InsertTextResponse{}
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTextResponse) ProtoMessage() {}

func (x *InsertTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTextResponse.ProtoReflect.Descriptor instead.
func (*InsertTextResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_graphrag_proto_rawDescGZIP(), []int{5}
}

type InsertTextBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Texts         map[string]string      `protobuf:"bytes,1,rep,name=texts,proto3" json:"texts,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertTextBatchRequest) Reset() {
	*x = InsertTextBatchRequest{}
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertTextBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTextBatchRequest) ProtoMessage() {}

func (x *InsertTextBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTextBatchRequest.ProtoReflect.Descriptor instead.
func (*InsertTextBatchRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_graphrag_proto_rawDescGZIP(), []int{6}
}

func (x *InsertTextBatchRequest) GetTexts() map[string]string {
	if x != nil {
		return x.Texts
	}
	return nil
}

func (x *InsertTextBatchRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type InsertTextBatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InsertTextBatchResponse) Reset() {
	*x = InsertTextBatchResponse{}
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InsertTextBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InsertTextBatchResponse) ProtoMessage() {}

func (x *InsertTextBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InsertTextBatchResponse.ProtoReflect.Descriptor instead.
func (*InsertTextBatchResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_graphrag_proto_rawDescGZIP(), []int{7}
}

type ScoredText struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	DocId         string                 `protobuf:"bytes,3,opt,name=doc_id,json=docId,proto3" json:"doc_id,omitempty"`
	Collection    string                 `protobuf:"bytes,4,opt,name=collection,proto3" json:"collection,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Score         float64                `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoredText) Reset() {
	*x = ScoredText{}
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoredText) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoredText) ProtoMessage() {}

func (x *ScoredText) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoredText.ProtoReflect.Descriptor instead.
func (*ScoredText) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_graphrag_proto_rawDescGZIP(), []int{8}
}

func (x *ScoredText) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ScoredText) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ScoredText) GetDocId() string {
	if x != nil {
		return x.DocId
	}
	return ""
}

func (x *ScoredText) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *ScoredText) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ScoredText) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Collection    string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	TopK          int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTextRequest) Reset() {
	*x = SearchTextRequest{}
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTextRequest) ProtoMessage() {}

func (x *SearchTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTextRequest.ProtoReflect.Descriptor instead.
func (*SearchTextRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_graphrag_proto_rawDescGZIP(), []int{9}
}

func (x *SearchTextRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchTextRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchTextRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type SearchTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScoredText          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchTextResponse) Reset() {
	*x = SearchTextResponse{}
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchTextResponse) ProtoMessage() {}

func (x *SearchTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchTextResponse.ProtoReflect.Descriptor instead.
func (*SearchTextResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_graphrag_proto_rawDescGZIP(), []int{10}
}

func (x *SearchTextResponse) GetResults() []*ScoredText {
	if x != nil {
		return x.Results
	}
	return nil
}

type HybridSearchTextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	TopK          int32                  `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridSearchTextRequest) Reset() {
	*x = HybridSearchTextRequest{}
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchTextRequest) ProtoMessage() {}

func (x *HybridSearchTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchTextRequest.ProtoReflect.Descriptor instead.
func (*HybridSearchTextRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_graphrag_proto_rawDescGZIP(), []int{11}
}

func (x *HybridSearchTextRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *HybridSearchTextRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

type HybridSearchTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*ScoredText          `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HybridSearchTextResponse) Reset() {
	*x = HybridSearchTextResponse{}
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HybridSearchTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HybridSearchTextResponse) ProtoMessage() {}

func (x *HybridSearchTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_graphrag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HybridSearchTextResponse.ProtoReflect.Descriptor instead.
func (*HybridSearchTextResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_graphrag_proto_rawDescGZIP(), []int{12}
}

func (x *HybridSearchTextResponse) GetResults() []*ScoredText {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_cortexdb_v1_graphrag_proto protoreflect.FileDescriptor

const file_cortexdb_v1_graphrag_proto_rawDesc = "" +
	"\n" +
	"\x1acortexdb/v1/graphrag.proto\x12\vcortexdb.v1\x1a\x18cortexdb/v1/common.proto\"\xd0\x02\n" +
	"\x1aInsertGraphDocumentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12Q\n" +
	"\bmetadata\x18\x04 \x03(\v25.cortexdb.v1.InsertGraphDocumentRequest.MetadataEntryR\bmetadata\x12\x1e\n" +
	"\n" +
	"collection\x18\x05 \x01(\tR\n" +
	"collection\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\x06 \x01(\x05R\tchunkSize\x12#\n" +
	"\rchunk_overlap\x18\a \x01(\x05R\fchunkOverlap\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x95\x01\n" +
	"\x1bInsertGraphDocumentResponse\x12(\n" +
	"\x10document_node_id\x18\x01 \x01(\tR\x0edocumentNodeId\x12$\n" +
	"\x0echunk_node_ids\x18\x02 \x03(\tR\fchunkNodeIds\x12&\n" +
	"\x0fentity_node_ids\x18\x03 \x03(\tR\rentityNodeIds\"\xdd\x05\n" +
	"\x15SearchGraphRagRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12\x19\n" +
	"\bmax_hops\x18\x04 \x01(\x05R\amaxHops\x12,\n" +
	"\x12max_related_chunks\x18\x05 \x01(\x05R\x10maxRelatedChunks\x12,\n" +
	"\x12max_context_chunks\x18\x06 \x01(\x05R\x10maxContextChunks\x12*\n" +
	"\x11max_context_chars\x18\a \x01(\x05R\x0fmaxContextChars\x12,\n" +
	"\x12per_document_limit\x18\b \x01(\x05R\x10perDocumentLimit\x12\x16\n" +
	"\x06rerank\x18\t \x01(\bR\x06rerank\x12%\n" +
	"\x0edisable_rerank\x18\n" +
	" \x01(\bR\rdisableRerank\x12)\n" +
	"\x10diversity_lambda\x18\v \x01(\x01R\x0fdiversityLambda\x12#\n" +
	"\rdisable_graph\x18\f \x01(\bR\fdisableGraph\x12%\n" +
	"\x0eretrieval_mode\x18\r \x01(\tR\rretrievalMode\x12\x1f\n" +
	"\vgraph_light\x18\x0e \x01(\bR\n" +
	"graphLight\x12.\n" +
	"\x13max_expansion_seeds\x18\x0f \x01(\x05R\x11maxExpansionSeeds\x12.\n" +
	"\x13max_traversal_nodes\x18\x10 \x01(\x05R\x11maxTraversalNodes\x123\n" +
	"\x16max_entities_per_chunk\x18\x11 \x01(\x05R\x13maxEntitiesPerChunk\x123\n" +
	"\x04plan\x18\x12 \x01(\v2\x1a.cortexdb.v1.RetrievalPlanH\x00R\x04plan\x88\x01\x01B\a\n" +
	"\x05_plan\"\x8a\x02\n" +
	"\x16SearchGraphRagResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12.\n" +
	"\x04plan\x18\x02 \x01(\v2\x1a.cortexdb.v1.RetrievalPlanR\x04plan\x12:\n" +
	"\bdecision\x18\x03 \x01(\v2\x1e.cortexdb.v1.RetrievalDecisionR\bdecision\x128\n" +
	"\x06chunks\x18\x04 \x03(\v2 .cortexdb.v1.GraphRagChunkResultR\x06chunks\x12\x1a\n" +
	"\bentities\x18\x05 \x03(\tR\bentities\x12\x18\n" +
	"\acontext\x18\x06 \x01(\tR\acontext\"\xbe\x01\n" +
	"\x11InsertTextRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12H\n" +
	"\bmetadata\x18\x03 \x03(\v2,.cortexdb.v1.InsertTextRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x14\n" +
	"\x12InsertTextResponse\"\xa4\x02\n" +
	"\x16InsertTextBatchRequest\x12D\n" +
	"\x05texts\x18\x01 \x03(\v2..cortexdb.v1.InsertTextBatchRequest.TextsEntryR\x05texts\x12M\n" +
	"\bmetadata\x18\x02 \x03(\v21.cortexdb.v1.InsertTextBatchRequest.MetadataEntryR\bmetadata\x1a8\n" +
	"\n" +
	"TextsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x19\n" +
	"\x17InsertTextBatchResponse\"\x83\x02\n" +
	"\n" +
	"ScoredText\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x15\n" +
	"\x06doc_id\x18\x03 \x01(\tR\x05docId\x12\x1e\n" +
	"\n" +
	"collection\x18\x04 \x01(\tR\n" +
	"collection\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.cortexdb.v1.ScoredText.MetadataEntryR\bmetadata\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"^\n" +
	"\x11SearchTextRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\"G\n" +
	"\x12SearchTextResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.cortexdb.v1.ScoredTextR\aresults\"D\n" +
	"\x17HybridSearchTextRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\x05R\x04topK\"M\n" +
	"\x18HybridSearchTextResponse\x121\n" +
	"\aresults\x18\x01 \x03(\v2\x17.cortexdb.v1.ScoredTextR\aresults2\xb3\x04\n" +
	"\x0fGraphRagService\x12h\n" +
	"\x13InsertGraphDocument\x12'.cortexdb.v1.InsertGraphDocumentRequest\x1a(.cortexdb.v1.InsertGraphDocumentResponse\x12Y\n" +
	"\x0eSearchGraphRag\x12\".cortexdb.v1.SearchGraphRagRequest\x1a#.cortexdb.v1.SearchGraphRagResponse\x12M\n" +
	"\n" +
	"InsertText\x12\x1e.cortexdb.v1.InsertTextRequest\x1a\x1f.cortexdb.v1.InsertTextResponse\x12\\\n" +
	"\x0fInsertTextBatch\x12#.cortexdb.v1.InsertTextBatchRequest\x1a$.cortexdb.v1.InsertTextBatchResponse\x12M\n" +
	"\n" +
	"SearchText\x12\x1e.cortexdb.v1.SearchTextRequest\x1a\x1f.cortexdb.v1.SearchTextResponse\x12_\n" +
	"\x10HybridSearchText\x12$.cortexdb.v1.HybridSearchTextRequest\x1a%.cortexdb.v1.HybridSearchTextResponseB4Z2github.com/liliang-cn/cortexdb/v2/pkg/rpc/v1;rpcv1b\x06proto3"

var (
	file_cortexdb_v1_graphrag_proto_rawDescOnce sync.Once
	file_cortexdb_v1_graphrag_proto_rawDescData []byte
)

func file_cortexdb_v1_graphrag_proto_rawDescGZIP() []byte {
	file_cortexdb_v1_graphrag_proto_rawDescOnce.Do(func() {
		file_cortexdb_v1_graphrag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortexdb_v1_graphrag_proto_rawDesc), len(file_cortexdb_v1_graphrag_proto_rawDesc)))
	})
	return file_cortexdb_v1_graphrag_proto_rawDescData
}

var file_cortexdb_v1_graphrag_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_cortexdb_v1_graphrag_proto_goTypes = []any{
	(*InsertGraphDocumentRequest)(nil),  // 0: cortexdb.v1.InsertGraphDocumentRequest
	(*InsertGraphDocumentResponse)(nil), // 1: cortexdb.v1.InsertGraphDocumentResponse
	(*SearchGraphRagRequest)(nil),       // 2: cortexdb.v1.SearchGraphRagRequest
	(*SearchGraphRagResponse)(nil),      // 3: cortexdb.v1.SearchGraphRagResponse
	(*InsertTextRequest)(nil),           // 4: cortexdb.v1.InsertTextRequest
	(*InsertTextResponse)(nil),          // 5: cortexdb.v1.InsertTextResponse
	(*InsertTextBatchRequest)(nil),      // 6: cortexdb.v1.InsertTextBatchRequest
	(*InsertTextBatchResponse)(nil),     // 7: cortexdb.v1.InsertTextBatchResponse
	(*ScoredText)(nil),                  // 8: cortexdb.v1.ScoredText
	(*SearchTextRequest)(nil),           // 9: cortexdb.v1.SearchTextRequest
	(*SearchTextResponse)(nil),          // 10: cortexdb.v1.SearchTextResponse
	(*HybridSearchTextRequest)(nil),     // 11: cortexdb.v1.HybridSearchTextRequest
	(*HybridSearchTextResponse)(nil),    // 12: cortexdb.v1.HybridSearchTextResponse
	nil,                                 // 13: cortexdb.v1.InsertGraphDocumentRequest.MetadataEntry
	nil,                                 // 14: cortexdb.v1.InsertTextRequest.MetadataEntry
	nil,                                 // 15: cortexdb.v1.InsertTextBatchRequest.TextsEntry
	nil,                                 // 16: cortexdb.v1.InsertTextBatchRequest.MetadataEntry
	nil,                                 // 17: cortexdb.v1.ScoredText.MetadataEntry
	(*RetrievalPlan)(nil),               // 18: cortexdb.v1.RetrievalPlan
	(*RetrievalDecision)(nil),           // 19: cortexdb.v1.RetrievalDecision
	(*GraphRagChunkResult)(nil),         // 20: cortexdb.v1.GraphRagChunkResult
}
var file_cortexdb_v1_graphrag_proto_depIdxs = []int32{
	13, // 0: cortexdb.v1.InsertGraphDocumentRequest.metadata:type_name -> cortexdb.v1.InsertGraphDocumentRequest.MetadataEntry
	18, // 1: cortexdb.v1.SearchGraphRagRequest.plan:type_name -> cortexdb.v1.RetrievalPlan
	18, // 2: cortexdb.v1.SearchGraphRagResponse.plan:type_name -> cortexdb.v1.RetrievalPlan
	19, // 3: cortexdb.v1.SearchGraphRagResponse.decision:type_name -> cortexdb.v1.RetrievalDecision
	20, // 4: cortexdb.v1.SearchGraphRagResponse.chunks:type_name -> cortexdb.v1.GraphRagChunkResult
	14, // 5: cortexdb.v1.InsertTextRequest.metadata:type_name -> cortexdb.v1.InsertTextRequest.MetadataEntry
	15, // 6: cortexdb.v1.InsertTextBatchRequest.texts:type_name -> cortexdb.v1.InsertTextBatchRequest.TextsEntry
	16, // 7: cortexdb.v1.InsertTextBatchRequest.metadata:type_name -> cortexdb.v1.InsertTextBatchRequest.MetadataEntry
	17, // 8: cortexdb.v1.ScoredText.metadata:type_name -> cortexdb.v1.ScoredText.MetadataEntry
	8,  // 9: cortexdb.v1.SearchTextResponse.results:type_name -> cortexdb.v1.ScoredText
	8,  // 10: cortexdb.v1.HybridSearchTextResponse.results:type_name -> cortexdb.v1.ScoredText
	0,  // 11: cortexdb.v1.GraphRagService.InsertGraphDocument:input_type -> cortexdb.v1.InsertGraphDocumentRequest
	2,  // 12: cortexdb.v1.GraphRagService.SearchGraphRag:input_type -> cortexdb.v1.SearchGraphRagRequest
	4,  // 13: cortexdb.v1.GraphRagService.InsertText:input_type -> cortexdb.v1.InsertTextRequest
	6,  // 14: cortexdb.v1.GraphRagService.InsertTextBatch:input_type -> cortexdb.v1.InsertTextBatchRequest
	9,  // 15: cortexdb.v1.GraphRagService.SearchText:input_type -> cortexdb.v1.SearchTextRequest
	11, // 16: cortexdb.v1.GraphRagService.HybridSearchText:input_type -> cortexdb.v1.HybridSearchTextRequest
	1,  // 17: cortexdb.v1.GraphRagService.InsertGraphDocument:output_type -> cortexdb.v1.InsertGraphDocumentResponse
	3,  // 18: cortexdb.v1.GraphRagService.SearchGraphRag:output_type -> cortexdb.v1.SearchGraphRagResponse
	5,  // 19: cortexdb.v1.GraphRagService.InsertText:output_type -> cortexdb.v1.InsertTextResponse
	7,  // 20: cortexdb.v1.GraphRagService.InsertTextBatch:output_type -> cortexdb.v1.InsertTextBatchResponse
	10, // 21: cortexdb.v1.GraphRagService.SearchText:output_type -> cortexdb.v1.SearchTextResponse
	12, // 22: cortexdb.v1.GraphRagService.HybridSearchText:output_type -> cortexdb.v1.HybridSearchTextResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_cortexdb_v1_graphrag_proto_init() }
func file_cortexdb_v1_graphrag_proto_init() {
	if File_cortexdb_v1_graphrag_proto != nil {
		return
	}
	file_cortexdb_v1_common_proto_init()
	file_cortexdb_v1_graphrag_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortexdb_v1_graphrag_proto_rawDesc), len(file_cortexdb_v1_graphrag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cortexdb_v1_graphrag_proto_goTypes,
		DependencyIndexes: file_cortexdb_v1_graphrag_proto_depIdxs,
		MessageInfos:      file_cortexdb_v1_graphrag_proto_msgTypes,
	}.Build()
	File_cortexdb_v1_graphrag_proto = out.File
	file_cortexdb_v1_graphrag_proto_goTypes = nil
	file_cortexdb_v1_graphrag_proto_depIdxs = nil
}
