// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.1
// source: cortexdb/v1/graphrag.proto

package rpcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GraphRagService_InsertGraphDocument_FullMethodName = "/cortexdb.v1.GraphRagService/InsertGraphDocument"
	GraphRagService_SearchGraphRag_FullMethodName      = "/cortexdb.v1.GraphRagService/SearchGraphRag"
	GraphRagService_InsertText_FullMethodName          = "/cortexdb.v1.GraphRagService/InsertText"
	GraphRagService_InsertTextBatch_FullMethodName     = "/cortexdb.v1.GraphRagService/InsertTextBatch"
	GraphRagService_SearchText_FullMethodName          = "/cortexdb.v1.GraphRagService/SearchText"
	GraphRagService_HybridSearchText_FullMethodName    = "/cortexdb.v1.GraphRagService/HybridSearchText"
)

// GraphRagServiceClient is the client API for GraphRagService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GraphRagServiceClient interface {
	InsertGraphDocument(ctx context.Context, in *InsertGraphDocumentRequest, opts ...grpc.CallOption) (*InsertGraphDocumentResponse, error)
	SearchGraphRag(ctx context.Context, in *SearchGraphRagRequest, opts ...grpc.CallOption) (*SearchGraphRagResponse, error)
	InsertText(ctx context.Context, in *InsertTextRequest, opts ...grpc.CallOption) (*InsertTextResponse, error)
	InsertTextBatch(ctx context.Context, in *InsertTextBatchRequest, opts ...grpc.CallOption) (*InsertTextBatchResponse, error)
	SearchText(ctx context.Context, in *SearchTextRequest, opts ...grpc.CallOption) (*SearchTextResponse, error)
	HybridSearchText(ctx context.Context, in *HybridSearchTextRequest, opts ...grpc.CallOption) (*HybridSearchTextResponse, error)
}

type graphRagServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGraphRagServiceClient(cc grpc.ClientConnInterface) GraphRagServiceClient {
	return &graphRagServiceClient{cc}
}

func (c *graphRagServiceClient) InsertGraphDocument(ctx context.Context, in *InsertGraphDocumentRequest, opts ...grpc.CallOption) (*InsertGraphDocumentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertGraphDocumentResponse)
	err := c.cc.Invoke(ctx, GraphRagService_InsertGraphDocument_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphRagServiceClient) SearchGraphRag(ctx context.Context, in *SearchGraphRagRequest, opts ...grpc.CallOption) (*SearchGraphRagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchGraphRagResponse)
	err := c.cc.Invoke(ctx, GraphRagService_SearchGraphRag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphRagServiceClient) InsertText(ctx context.Context, in *InsertTextRequest, opts ...grpc.CallOption) (*InsertTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertTextResponse)
	err := c.cc.Invoke(ctx, GraphRagService_InsertText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphRagServiceClient) InsertTextBatch(ctx context.Context, in *InsertTextBatchRequest, opts ...grpc.CallOption) (*InsertTextBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertTextBatchResponse)
	err := c.cc.Invoke(ctx, GraphRagService_InsertTextBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphRagServiceClient) SearchText(ctx context.Context, in *SearchTextRequest, opts ...grpc.CallOption) (*SearchTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchTextResponse)
	err := c.cc.Invoke(ctx, GraphRagService_SearchText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *graphRagServiceClient) HybridSearchText(ctx context.Context, in *HybridSearchTextRequest, opts ...grpc.CallOption) (*HybridSearchTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HybridSearchTextResponse)
	err := c.cc.Invoke(ctx, GraphRagService_HybridSearchText_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GraphRagServiceServer is the server API for GraphRagService service.
// All implementations must embed UnimplementedGraphRagServiceServer
// for forward compatibility.
type GraphRagServiceServer interface {
	InsertGraphDocument(context.Context, *InsertGraphDocumentRequest) (*InsertGraphDocumentResponse, error)
	SearchGraphRag(context.Context, *SearchGraphRagRequest) (*SearchGraphRagResponse, error)
	InsertText(context.Context, *InsertTextRequest) (*InsertTextResponse, error)
	InsertTextBatch(context.Context, *InsertTextBatchRequest) (*InsertTextBatchResponse, error)
	SearchText(context.Context, *SearchTextRequest) (*SearchTextResponse, error)
	HybridSearchText(context.Context, *HybridSearchTextRequest) (*HybridSearchTextResponse, error)
	mustEmbedUnimplementedGraphRagServiceServer()
}

// UnimplementedGraphRagServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGraphRagServiceServer struct{}

func (UnimplementedGraphRagServiceServer) InsertGraphDocument(context.Context, *InsertGraphDocumentRequest) (*InsertGraphDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertGraphDocument not implemented")
}
func (UnimplementedGraphRagServiceServer) SearchGraphRag(context.Context, *SearchGraphRagRequest) (*SearchGraphRagResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchGraphRag not implemented")
}
func (UnimplementedGraphRagServiceServer) InsertText(context.Context, *InsertTextRequest) (*InsertTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertText not implemented")
}
func (UnimplementedGraphRagServiceServer) InsertTextBatch(context.Context, *InsertTextBatchRequest) (*InsertTextBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InsertTextBatch not implemented")
}
func (UnimplementedGraphRagServiceServer) SearchText(context.Context, *SearchTextRequest) (*SearchTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchText not implemented")
}
func (UnimplementedGraphRagServiceServer) HybridSearchText(context.Context, *HybridSearchTextRequest) (*HybridSearchTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HybridSearchText not implemented")
}
func (UnimplementedGraphRagServiceServer) mustEmbedUnimplementedGraphRagServiceServer() {}
func (UnimplementedGraphRagServiceServer) testEmbeddedByValue()                         {}

// UnsafeGraphRagServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GraphRagServiceServer will
// result in compilation errors.
type UnsafeGraphRagServiceServer interface {
	mustEmbedUnimplementedGraphRagServiceServer()
}

func RegisterGraphRagServiceServer(s grpc.ServiceRegistrar, srv GraphRagServiceServer) {
	// If the following call pancis, it indicates UnimplementedGraphRagServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GraphRagService_ServiceDesc, srv)
}

func _GraphRagService_InsertGraphDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertGraphDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphRagServiceServer).InsertGraphDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphRagService_InsertGraphDocument_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphRagServiceServer).InsertGraphDocument(ctx, req.(*InsertGraphDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphRagService_SearchGraphRag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchGraphRagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphRagServiceServer).SearchGraphRag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphRagService_SearchGraphRag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphRagServiceServer).SearchGraphRag(ctx, req.(*SearchGraphRagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphRagService_InsertText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphRagServiceServer).InsertText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphRagService_InsertText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphRagServiceServer).InsertText(ctx, req.(*InsertTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphRagService_InsertTextBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertTextBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphRagServiceServer).InsertTextBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphRagService_InsertTextBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphRagServiceServer).InsertTextBatch(ctx, req.(*InsertTextBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphRagService_SearchText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphRagServiceServer).SearchText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphRagService_SearchText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphRagServiceServer).SearchText(ctx, req.(*SearchTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GraphRagService_HybridSearchText_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HybridSearchTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GraphRagServiceServer).HybridSearchText(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GraphRagService_HybridSearchText_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GraphRagServiceServer).HybridSearchText(ctx, req.(*HybridSearchTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GraphRagService_ServiceDesc is the grpc.ServiceDesc for GraphRagService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GraphRagService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cortexdb.v1.GraphRagService",
	HandlerType: (*GraphRagServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InsertGraphDocument",
			Handler:    _GraphRagService_InsertGraphDocument_Handler,
		},
		{
			MethodName: "SearchGraphRag",
			Handler:    _GraphRagService_SearchGraphRag_Handler,
		},
		{
			MethodName: "InsertText",
			Handler:    _GraphRagService_InsertText_Handler,
		},
		{
			MethodName: "InsertTextBatch",
			Handler:    _GraphRagService_InsertTextBatch_Handler,
		},
		{
			MethodName: "SearchText",
			Handler:    _GraphRagService_SearchText_Handler,
		},
		{
			MethodName: "HybridSearchText",
			Handler:    _GraphRagService_HybridSearchText_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cortexdb/v1/graphrag.proto",
}
