// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.1
// source: cortexdb/v1/knowledge.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type KnowledgeRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,4,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Collection    string                 `protobuf:"bytes,6,opt,name=collection,proto3" json:"collection,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ChunkIds      []string               `protobuf:"bytes,8,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	Entities      []string               `protobuf:"bytes,9,rep,name=entities,proto3" json:"entities,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeRecord) Reset() {
	*x = KnowledgeRecord{}
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeRecord) ProtoMessage() {}

func (x *KnowledgeRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeRecord.ProtoReflect.Descriptor instead.
func (*KnowledgeRecord) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_knowledge_proto_rawDescGZIP(), []int{0}
}

func (x *KnowledgeRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KnowledgeRecord) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *KnowledgeRecord) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *KnowledgeRecord) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *KnowledgeRecord) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *KnowledgeRecord) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *KnowledgeRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *KnowledgeRecord) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

func (x *KnowledgeRecord) GetEntities() []string {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *KnowledgeRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *KnowledgeRecord) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SaveKnowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeId   string                 `protobuf:"bytes,1,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,4,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	Author        string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	Collection    string                 `protobuf:"bytes,6,opt,name=collection,proto3" json:"collection,omitempty"`
	ChunkSize     int32                  `protobuf:"varint,7,opt,name=chunk_size,json=chunkSize,proto3" json:"chunk_size,omitempty"`
	ChunkOverlap  int32                  `protobuf:"varint,8,opt,name=chunk_overlap,json=chunkOverlap,proto3" json:"chunk_overlap,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Entities      []*ToolEntityInput     `protobuf:"bytes,10,rep,name=entities,proto3" json:"entities,omitempty"`
	Relations     []*ToolRelationInput   `protobuf:"bytes,11,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveKnowledgeRequest) Reset() {
	*x = SaveKnowledgeRequest{}
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveKnowledgeRequest) ProtoMessage() {}

func (x *SaveKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*SaveKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_knowledge_proto_rawDescGZIP(), []int{1}
}

func (x *SaveKnowledgeRequest) GetKnowledgeId() string {
	if x != nil {
		return x.KnowledgeId
	}
	return ""
}

func (x *SaveKnowledgeRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SaveKnowledgeRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SaveKnowledgeRequest) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *SaveKnowledgeRequest) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *SaveKnowledgeRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SaveKnowledgeRequest) GetChunkSize() int32 {
	if x != nil {
		return x.ChunkSize
	}
	return 0
}

func (x *SaveKnowledgeRequest) GetChunkOverlap() int32 {
	if x != nil {
		return x.ChunkOverlap
	}
	return 0
}

func (x *SaveKnowledgeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SaveKnowledgeRequest) GetEntities() []*ToolEntityInput {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SaveKnowledgeRequest) GetRelations() []*ToolRelationInput {
	if x != nil {
		return x.Relations
	}
	return nil
}

type SaveKnowledgeResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Knowledge       *KnowledgeRecord       `protobuf:"bytes,1,opt,name=knowledge,proto3" json:"knowledge,omitempty"`
	DocumentNodeId  string                 `protobuf:"bytes,2,opt,name=document_node_id,json=documentNodeId,proto3" json:"document_node_id,omitempty"`
	EntityNodeIds   []string               `protobuf:"bytes,3,rep,name=entity_node_ids,json=entityNodeIds,proto3" json:"entity_node_ids,omitempty"`
	RelationEdgeIds []string               `protobuf:"bytes,4,rep,name=relation_edge_ids,json=relationEdgeIds,proto3" json:"relation_edge_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SaveKnowledgeResponse) Reset() {
	*x = SaveKnowledgeResponse{}
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveKnowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveKnowledgeResponse) ProtoMessage() {}

func (x *SaveKnowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveKnowledgeResponse.ProtoReflect.Descriptor instead.
func (*SaveKnowledgeResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_knowledge_proto_rawDescGZIP(), []int{2}
}

func (x *SaveKnowledgeResponse) GetKnowledge() *KnowledgeRecord {
	if x != nil {
		return x.Knowledge
	}
	return nil
}

func (x *SaveKnowledgeResponse) GetDocumentNodeId() string {
	if x != nil {
		return x.DocumentNodeId
	}
	return ""
}

func (x *SaveKnowledgeResponse) GetEntityNodeIds() []string {
	if x != nil {
		return x.EntityNodeIds
	}
	return nil
}

func (x *SaveKnowledgeResponse) GetRelationEdgeIds() []string {
	if x != nil {
		return x.RelationEdgeIds
	}
	return nil
}

type UpdateKnowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeId   string                 `protobuf:"bytes,1,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	Title         *string                `protobuf:"bytes,2,opt,name=title,proto3,oneof" json:"title,omitempty"`
	Content       *string                `protobuf:"bytes,3,opt,name=content,proto3,oneof" json:"content,omitempty"`
	SourceUrl     *string                `protobuf:"bytes,4,opt,name=source_url,json=sourceUrl,proto3,oneof" json:"source_url,omitempty"`
	Author        *string                `protobuf:"bytes,5,opt,name=author,proto3,oneof" json:"author,omitempty"`
	Collection    *string                `protobuf:"bytes,6,opt,name=collection,proto3,oneof" json:"collection,omitempty"`
	ChunkSize     *int32                 `protobuf:"varint,7,opt,name=chunk_size,json=chunkSize,proto3,oneof" json:"chunk_size,omitempty"`
	ChunkOverlap  *int32                 `protobuf:"varint,8,opt,name=chunk_overlap,json=chunkOverlap,proto3,oneof" json:"chunk_overlap,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Entities      []*ToolEntityInput     `protobuf:"bytes,10,rep,name=entities,proto3" json:"entities,omitempty"`
	Relations     []*ToolRelationInput   `protobuf:"bytes,11,rep,name=relations,proto3" json:"relations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateKnowledgeRequest) Reset() {
	*x = UpdateKnowledgeRequest{}
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateKnowledgeRequest) ProtoMessage() {}

func (x *UpdateKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*UpdateKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_knowledge_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateKnowledgeRequest) GetKnowledgeId() string {
	if x != nil {
		return x.KnowledgeId
	}
	return ""
}

func (x *UpdateKnowledgeRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateKnowledgeRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *UpdateKnowledgeRequest) GetSourceUrl() string {
	if x != nil && x.SourceUrl != nil {
		return *x.SourceUrl
	}
	return ""
}

func (x *UpdateKnowledgeRequest) GetAuthor() string {
	if x != nil && x.Author != nil {
		return *x.Author
	}
	return ""
}

func (x *UpdateKnowledgeRequest) GetCollection() string {
	if x != nil && x.Collection != nil {
		return *x.Collection
	}
	return ""
}

func (x *UpdateKnowledgeRequest) GetChunkSize() int32 {
	if x != nil && x.ChunkSize != nil {
		return *x.ChunkSize
	}
	return 0
}

func (x *UpdateKnowledgeRequest) GetChunkOverlap() int32 {
	if x != nil && x.ChunkOverlap != nil {
		return *x.ChunkOverlap
	}
	return 0
}

func (x *UpdateKnowledgeRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateKnowledgeRequest) GetEntities() []*ToolEntityInput {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *UpdateKnowledgeRequest) GetRelations() []*ToolRelationInput {
	if x != nil {
		return x.Relations
	}
	return nil
}

type GetKnowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeId   string                 `protobuf:"bytes,1,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeRequest) Reset() {
	*x = GetKnowledgeRequest{}
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeRequest) ProtoMessage() {}

func (x *GetKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*GetKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_knowledge_proto_rawDescGZIP(), []int{4}
}

func (x *GetKnowledgeRequest) GetKnowledgeId() string {
	if x != nil {
		return x.KnowledgeId
	}
	return ""
}

type GetKnowledgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Knowledge     *KnowledgeRecord       `protobuf:"bytes,1,opt,name=knowledge,proto3" json:"knowledge,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKnowledgeResponse) Reset() {
	*x = GetKnowledgeResponse{}
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKnowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKnowledgeResponse) ProtoMessage() {}

func (x *GetKnowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKnowledgeResponse.ProtoReflect.Descriptor instead.
func (*GetKnowledgeResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_knowledge_proto_rawDescGZIP(), []int{5}
}

func (x *GetKnowledgeResponse) GetKnowledge() *KnowledgeRecord {
	if x != nil {
		return x.Knowledge
	}
	return nil
}

type DeleteKnowledgeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeId   string                 `protobuf:"bytes,1,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKnowledgeRequest) Reset() {
	*x = DeleteKnowledgeRequest{}
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeRequest) ProtoMessage() {}

func (x *DeleteKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_knowledge_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteKnowledgeRequest) GetKnowledgeId() string {
	if x != nil {
		return x.KnowledgeId
	}
	return ""
}

type DeleteKnowledgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeId   string                 `protobuf:"bytes,1,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteKnowledgeResponse) Reset() {
	*x = DeleteKnowledgeResponse{}
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteKnowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteKnowledgeResponse) ProtoMessage() {}

func (x *DeleteKnowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteKnowledgeResponse.ProtoReflect.Descriptor instead.
func (*DeleteKnowledgeResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_knowledge_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteKnowledgeResponse) GetKnowledgeId() string {
	if x != nil {
		return x.KnowledgeId
	}
	return ""
}

func (x *DeleteKnowledgeResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type SearchKnowledgeRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Query               string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Collection          string                 `protobuf:"bytes,2,opt,name=collection,proto3" json:"collection,omitempty"`
	TopK                int32                  `protobuf:"varint,3,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	MaxHops             int32                  `protobuf:"varint,4,opt,name=max_hops,json=maxHops,proto3" json:"max_hops,omitempty"`
	MaxRelatedChunks    int32                  `protobuf:"varint,5,opt,name=max_related_chunks,json=maxRelatedChunks,proto3" json:"max_related_chunks,omitempty"`
	MaxContextChunks    int32                  `protobuf:"varint,6,opt,name=max_context_chunks,json=maxContextChunks,proto3" json:"max_context_chunks,omitempty"`
	MaxContextChars     int32                  `protobuf:"varint,7,opt,name=max_context_chars,json=maxContextChars,proto3" json:"max_context_chars,omitempty"`
	PerDocumentLimit    int32                  `protobuf:"varint,8,opt,name=per_document_limit,json=perDocumentLimit,proto3" json:"per_document_limit,omitempty"`
	DiversityLambda     float64                `protobuf:"fixed64,9,opt,name=diversity_lambda,json=diversityLambda,proto3" json:"diversity_lambda,omitempty"`
	DisableRerank       bool                   `protobuf:"varint,10,opt,name=disable_rerank,json=disableRerank,proto3" json:"disable_rerank,omitempty"`
	EntityNames         []string               `protobuf:"bytes,11,rep,name=entity_names,json=entityNames,proto3" json:"entity_names,omitempty"`
	Keywords            []string               `protobuf:"bytes,12,rep,name=keywords,proto3" json:"keywords,omitempty"`
	AlternateQueries    []string               `protobuf:"bytes,13,rep,name=alternate_queries,json=alternateQueries,proto3" json:"alternate_queries,omitempty"`
	RetrievalMode       string                 `protobuf:"bytes,14,opt,name=retrieval_mode,json=retrievalMode,proto3" json:"retrieval_mode,omitempty"`
	DisableGraph        bool                   `protobuf:"varint,15,opt,name=disable_graph,json=disableGraph,proto3" json:"disable_graph,omitempty"`
	GraphLight          bool                   `protobuf:"varint,16,opt,name=graph_light,json=graphLight,proto3" json:"graph_light,omitempty"`
	MaxExpansionSeeds   int32                  `protobuf:"varint,17,opt,name=max_expansion_seeds,json=maxExpansionSeeds,proto3" json:"max_expansion_seeds,omitempty"`
	MaxTraversalNodes   int32                  `protobuf:"varint,18,opt,name=max_traversal_nodes,json=maxTraversalNodes,proto3" json:"max_traversal_nodes,omitempty"`
	MaxEntitiesPerChunk int32                  `protobuf:"varint,19,opt,name=max_entities_per_chunk,json=maxEntitiesPerChunk,proto3" json:"max_entities_per_chunk,omitempty"`
	Plan                *RetrievalPlan         `protobuf:"bytes,20,opt,name=plan,proto3,oneof" json:"plan,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SearchKnowledgeRequest) Reset() {
	*x = SearchKnowledgeRequest{}
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchKnowledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchKnowledgeRequest) ProtoMessage() {}

func (x *SearchKnowledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchKnowledgeRequest.ProtoReflect.Descriptor instead.
func (*SearchKnowledgeRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_knowledge_proto_rawDescGZIP(), []int{8}
}

func (x *SearchKnowledgeRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchKnowledgeRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *SearchKnowledgeRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchKnowledgeRequest) GetMaxHops() int32 {
	if x != nil {
		return x.MaxHops
	}
	return 0
}

func (x *SearchKnowledgeRequest) GetMaxRelatedChunks() int32 {
	if x != nil {
		return x.MaxRelatedChunks
	}
	return 0
}

func (x *SearchKnowledgeRequest) GetMaxContextChunks() int32 {
	if x != nil {
		return x.MaxContextChunks
	}
	return 0
}

func (x *SearchKnowledgeRequest) GetMaxContextChars() int32 {
	if x != nil {
		return x.MaxContextChars
	}
	return 0
}

func (x *SearchKnowledgeRequest) GetPerDocumentLimit() int32 {
	if x != nil {
		return x.PerDocumentLimit
	}
	return 0
}

func (x *SearchKnowledgeRequest) GetDiversityLambda() float64 {
	if x != nil {
		return x.DiversityLambda
	}
	return 0
}

func (x *SearchKnowledgeRequest) GetDisableRerank() bool {
	if x != nil {
		return x.DisableRerank
	}
	return false
}

func (x *SearchKnowledgeRequest) GetEntityNames() []string {
	if x != nil {
		return x.EntityNames
	}
	return nil
}

func (x *SearchKnowledgeRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *SearchKnowledgeRequest) GetAlternateQueries() []string {
	if x != nil {
		return x.AlternateQueries
	}
	return nil
}

func (x *SearchKnowledgeRequest) GetRetrievalMode() string {
	if x != nil {
		return x.RetrievalMode
	}
	return ""
}

func (x *SearchKnowledgeRequest) GetDisableGraph() bool {
	if x != nil {
		return x.DisableGraph
	}
	return false
}

func (x *SearchKnowledgeRequest) GetGraphLight() bool {
	if x != nil {
		return x.GraphLight
	}
	return false
}

func (x *SearchKnowledgeRequest) GetMaxExpansionSeeds() int32 {
	if x != nil {
		return x.MaxExpansionSeeds
	}
	return 0
}

func (x *SearchKnowledgeRequest) GetMaxTraversalNodes() int32 {
	if x != nil {
		return x.MaxTraversalNodes
	}
	return 0
}

func (x *SearchKnowledgeRequest) GetMaxEntitiesPerChunk() int32 {
	if x != nil {
		return x.MaxEntitiesPerChunk
	}
	return 0
}

func (x *SearchKnowledgeRequest) GetPlan() *RetrievalPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type KnowledgeSearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KnowledgeId   string                 `protobuf:"bytes,1,opt,name=knowledge_id,json=knowledgeId,proto3" json:"knowledge_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	SourceUrl     string                 `protobuf:"bytes,3,opt,name=source_url,json=sourceUrl,proto3" json:"source_url,omitempty"`
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`
	Snippet       string                 `protobuf:"bytes,5,opt,name=snippet,proto3" json:"snippet,omitempty"`
	Score         float64                `protobuf:"fixed64,6,opt,name=score,proto3" json:"score,omitempty"`
	ChunkIds      []string               `protobuf:"bytes,7,rep,name=chunk_ids,json=chunkIds,proto3" json:"chunk_ids,omitempty"`
	Entities      []string               `protobuf:"bytes,8,rep,name=entities,proto3" json:"entities,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,9,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KnowledgeSearchHit) Reset() {
	*x = KnowledgeSearchHit{}
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KnowledgeSearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KnowledgeSearchHit) ProtoMessage() {}

func (x *KnowledgeSearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KnowledgeSearchHit.ProtoReflect.Descriptor instead.
func (*KnowledgeSearchHit) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_knowledge_proto_rawDescGZIP(), []int{9}
}

func (x *KnowledgeSearchHit) GetKnowledgeId() string {
	if x != nil {
		return x.KnowledgeId
	}
	return ""
}

func (x *KnowledgeSearchHit) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *KnowledgeSearchHit) GetSourceUrl() string {
	if x != nil {
		return x.SourceUrl
	}
	return ""
}

func (x *KnowledgeSearchHit) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *KnowledgeSearchHit) GetSnippet() string {
	if x != nil {
		return x.Snippet
	}
	return ""
}

func (x *KnowledgeSearchHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *KnowledgeSearchHit) GetChunkIds() []string {
	if x != nil {
		return x.ChunkIds
	}
	return nil
}

func (x *KnowledgeSearchHit) GetEntities() []string {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *KnowledgeSearchHit) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type SearchKnowledgeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Plan          *RetrievalPlan         `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	Decision      *RetrievalDecision     `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	Results       []*KnowledgeSearchHit  `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	Chunks        []*GraphRagChunkResult `protobuf:"bytes,5,rep,name=chunks,proto3" json:"chunks,omitempty"`
	Entities      []string               `protobuf:"bytes,6,rep,name=entities,proto3" json:"entities,omitempty"`
	Context       string                 `protobuf:"bytes,7,opt,name=context,proto3" json:"context,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchKnowledgeResponse) Reset() {
	*x = SearchKnowledgeResponse{}
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchKnowledgeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchKnowledgeResponse) ProtoMessage() {}

func (x *SearchKnowledgeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_knowledge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchKnowledgeResponse.ProtoReflect.Descriptor instead.
func (*SearchKnowledgeResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_knowledge_proto_rawDescGZIP(), []int{10}
}

func (x *SearchKnowledgeResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchKnowledgeResponse) GetPlan() *RetrievalPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *SearchKnowledgeResponse) GetDecision() *RetrievalDecision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *SearchKnowledgeResponse) GetResults() []*KnowledgeSearchHit {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchKnowledgeResponse) GetChunks() []*GraphRagChunkResult {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *SearchKnowledgeResponse) GetEntities() []string {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *SearchKnowledgeResponse) GetContext() string {
	if x != nil {
		return x.Context
	}
	return ""
}

var File_cortexdb_v1_knowledge_proto protoreflect.FileDescriptor

const file_cortexdb_v1_knowledge_proto_rawDesc = "" +
	"\n" +
	"\x1bcortexdb/v1/knowledge.proto\x12\vcortexdb.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x18cortexdb/v1/common.proto\"\xdc\x03\n" +
	"\x0fKnowledgeRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"source_url\x18\x04 \x01(\tR\tsourceUrl\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x1e\n" +
	"\n" +
	"collection\x18\x06 \x01(\tR\n" +
	"collection\x12F\n" +
	"\bmetadata\x18\a \x03(\v2*.cortexdb.v1.KnowledgeRecord.MetadataEntryR\bmetadata\x12\x1b\n" +
	"\tchunk_ids\x18\b \x03(\tR\bchunkIds\x12\x1a\n" +
	"\bentities\x18\t \x03(\tR\bentities\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x04\n" +
	"\x14SaveKnowledgeRequest\x12!\n" +
	"\fknowledge_id\x18\x01 \x01(\tR\vknowledgeId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"source_url\x18\x04 \x01(\tR\tsourceUrl\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12\x1e\n" +
	"\n" +
	"collection\x18\x06 \x01(\tR\n" +
	"collection\x12\x1d\n" +
	"\n" +
	"chunk_size\x18\a \x01(\x05R\tchunkSize\x12#\n" +
	"\rchunk_overlap\x18\b \x01(\x05R\fchunkOverlap\x12K\n" +
	"\bmetadata\x18\t \x03(\v2/.cortexdb.v1.SaveKnowledgeRequest.MetadataEntryR\bmetadata\x128\n" +
	"\bentities\x18\n" +
	" \x03(\v2\x1c.cortexdb.v1.ToolEntityInputR\bentities\x12<\n" +
	"\trelations\x18\v \x03(\v2\x1e.cortexdb.v1.ToolRelationInputR\trelations\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd1\x01\n" +
	"\x15SaveKnowledgeResponse\x12:\n" +
	"\tknowledge\x18\x01 \x01(\v2\x1c.cortexdb.v1.KnowledgeRecordR\tknowledge\x12(\n" +
	"\x10document_node_id\x18\x02 \x01(\tR\x0edocumentNodeId\x12&\n" +
	"\x0fentity_node_ids\x18\x03 \x03(\tR\rentityNodeIds\x12*\n" +
	"\x11relation_edge_ids\x18\x04 \x03(\tR\x0frelationEdgeIds\"\x8d\x05\n" +
	"\x16UpdateKnowledgeRequest\x12!\n" +
	"\fknowledge_id\x18\x01 \x01(\tR\vknowledgeId\x12\x19\n" +
	"\x05title\x18\x02 \x01(\tH\x00R\x05title\x88\x01\x01\x12\x1d\n" +
	"\acontent\x18\x03 \x01(\tH\x01R\acontent\x88\x01\x01\x12\"\n" +
	"\n" +
	"source_url\x18\x04 \x01(\tH\x02R\tsourceUrl\x88\x01\x01\x12\x1b\n" +
	"\x06author\x18\x05 \x01(\tH\x03R\x06author\x88\x01\x01\x12#\n" +
	"\n" +
	"collection\x18\x06 \x01(\tH\x04R\n" +
	"collection\x88\x01\x01\x12\"\n" +
	"\n" +
	"chunk_size\x18\a \x01(\x05H\x05R\tchunkSize\x88\x01\x01\x12(\n" +
	"\rchunk_overlap\x18\b \x01(\x05H\x06R\fchunkOverlap\x88\x01\x01\x12M\n" +
	"\bmetadata\x18\t \x03(\v21.cortexdb.v1.UpdateKnowledgeRequest.MetadataEntryR\bmetadata\x128\n" +
	"\bentities\x18\n" +
	" \x03(\v2\x1c.cortexdb.v1.ToolEntityInputR\bentities\x12<\n" +
	"\trelations\x18\v \x03(\v2\x1e.cortexdb.v1.ToolRelationInputR\trelations\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_contentB\r\n" +
	"\v_source_urlB\t\n" +
	"\a_authorB\r\n" +
	"\v_collectionB\r\n" +
	"\v_chunk_sizeB\x10\n" +
	"\x0e_chunk_overlap\"8\n" +
	"\x13GetKnowledgeRequest\x12!\n" +
	"\fknowledge_id\x18\x01 \x01(\tR\vknowledgeId\"R\n" +
	"\x14GetKnowledgeResponse\x12:\n" +
	"\tknowledge\x18\x01 \x01(\v2\x1c.cortexdb.v1.KnowledgeRecordR\tknowledge\";\n" +
	"\x16DeleteKnowledgeRequest\x12!\n" +
	"\fknowledge_id\x18\x01 \x01(\tR\vknowledgeId\"V\n" +
	"\x17DeleteKnowledgeResponse\x12!\n" +
	"\fknowledge_id\x18\x01 \x01(\tR\vknowledgeId\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\"\xb2\x06\n" +
	"\x16SearchKnowledgeRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1e\n" +
	"\n" +
	"collection\x18\x02 \x01(\tR\n" +
	"collection\x12\x13\n" +
	"\x05top_k\x18\x03 \x01(\x05R\x04topK\x12\x19\n" +
	"\bmax_hops\x18\x04 \x01(\x05R\amaxHops\x12,\n" +
	"\x12max_related_chunks\x18\x05 \x01(\x05R\x10maxRelatedChunks\x12,\n" +
	"\x12max_context_chunks\x18\x06 \x01(\x05R\x10maxContextChunks\x12*\n" +
	"\x11max_context_chars\x18\a \x01(\x05R\x0fmaxContextChars\x12,\n" +
	"\x12per_document_limit\x18\b \x01(\x05R\x10perDocumentLimit\x12)\n" +
	"\x10diversity_lambda\x18\t \x01(\x01R\x0fdiversityLambda\x12%\n" +
	"\x0edisable_rerank\x18\n" +
	" \x01(\bR\rdisableRerank\x12!\n" +
	"\fentity_names\x18\v \x03(\tR\ventityNames\x12\x1a\n" +
	"\bkeywords\x18\f \x03(\tR\bkeywords\x12+\n" +
	"\x11alternate_queries\x18\r \x03(\tR\x10alternateQueries\x12%\n" +
	"\x0eretrieval_mode\x18\x0e \x01(\tR\rretrievalMode\x12#\n" +
	"\rdisable_graph\x18\x0f \x01(\bR\fdisableGraph\x12\x1f\n" +
	"\vgraph_light\x18\x10 \x01(\bR\n" +
	"graphLight\x12.\n" +
	"\x13max_expansion_seeds\x18\x11 \x01(\x05R\x11maxExpansionSeeds\x12.\n" +
	"\x13max_traversal_nodes\x18\x12 \x01(\x05R\x11maxTraversalNodes\x123\n" +
	"\x16max_entities_per_chunk\x18\x13 \x01(\x05R\x13maxEntitiesPerChunk\x123\n" +
	"\x04plan\x18\x14 \x01(\v2\x1a.cortexdb.v1.RetrievalPlanH\x00R\x04plan\x88\x01\x01B\a\n" +
	"\x05_plan\"\xf5\x02\n" +
	"\x12KnowledgeSearchHit\x12!\n" +
	"\fknowledge_id\x18\x01 \x01(\tR\vknowledgeId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1d\n" +
	"\n" +
	"source_url\x18\x03 \x01(\tR\tsourceUrl\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12\x18\n" +
	"\asnippet\x18\x05 \x01(\tR\asnippet\x12\x14\n" +
	"\x05score\x18\x06 \x01(\x01R\x05score\x12\x1b\n" +
	"\tchunk_ids\x18\a \x03(\tR\bchunkIds\x12\x1a\n" +
	"\bentities\x18\b \x03(\tR\bentities\x12I\n" +
	"\bmetadata\x18\t \x03(\v2-.cortexdb.v1.KnowledgeSearchHit.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc6\x02\n" +
	"\x17SearchKnowledgeResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12.\n" +
	"\x04plan\x18\x02 \x01(\v2\x1a.cortexdb.v1.RetrievalPlanR\x04plan\x12:\n" +
	"\bdecision\x18\x03 \x01(\v2\x1e.cortexdb.v1.RetrievalDecisionR\bdecision\x129\n" +
	"\aresults\x18\x04 \x03(\v2\x1f.cortexdb.v1.KnowledgeSearchHitR\aresults\x128\n" +
	"\x06chunks\x18\x05 \x03(\v2 .cortexdb.v1.GraphRagChunkResultR\x06chunks\x12\x1a\n" +
	"\bentities\x18\x06 \x03(\tR\bentities\x12\x18\n" +
	"\acontext\x18\a \x01(\tR\acontext2\xd7\x03\n" +
	"\x10KnowledgeService\x12V\n" +
	"\rSaveKnowledge\x12!.cortexdb.v1.SaveKnowledgeRequest\x1a\".cortexdb.v1.SaveKnowledgeResponse\x12Z\n" +
	"\x0fUpdateKnowledge\x12#.cortexdb.v1.UpdateKnowledgeRequest\x1a\".cortexdb.v1.SaveKnowledgeResponse\x12S\n" +
	"\fGetKnowledge\x12 .cortexdb.v1.GetKnowledgeRequest\x1a!.cortexdb.v1.GetKnowledgeResponse\x12\\\n" +
	"\x0fSearchKnowledge\x12#.cortexdb.v1.SearchKnowledgeRequest\x1a$.cortexdb.v1.SearchKnowledgeResponse\x12\\\n" +
	"\x0fDeleteKnowledge\x12#.cortexdb.v1.DeleteKnowledgeRequest\x1a$.cortexdb.v1.DeleteKnowledgeResponseB4Z2github.com/liliang-cn/cortexdb/v2/pkg/rpc/v1;rpcv1b\x06proto3"

var (
	file_cortexdb_v1_knowledge_proto_rawDescOnce sync.Once
	file_cortexdb_v1_knowledge_proto_rawDescData []byte
)

func file_cortexdb_v1_knowledge_proto_rawDescGZIP() []byte {
	file_cortexdb_v1_knowledge_proto_rawDescOnce.Do(func() {
		file_cortexdb_v1_knowledge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortexdb_v1_knowledge_proto_rawDesc), len(file_cortexdb_v1_knowledge_proto_rawDesc)))
	})
	return file_cortexdb_v1_knowledge_proto_rawDescData
}

var file_cortexdb_v1_knowledge_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_cortexdb_v1_knowledge_proto_goTypes = []any{
	(*KnowledgeRecord)(nil),         // 0: cortexdb.v1.KnowledgeRecord
	(*SaveKnowledgeRequest)(nil),    // 1: cortexdb.v1.SaveKnowledgeRequest
	(*SaveKnowledgeResponse)(nil),   // 2: cortexdb.v1.SaveKnowledgeResponse
	(*UpdateKnowledgeRequest)(nil),  // 3: cortexdb.v1.UpdateKnowledgeRequest
	(*GetKnowledgeRequest)(nil),     // 4: cortexdb.v1.GetKnowledgeRequest
	(*GetKnowledgeResponse)(nil),    // 5: cortexdb.v1.GetKnowledgeResponse
	(*DeleteKnowledgeRequest)(nil),  // 6: cortexdb.v1.DeleteKnowledgeRequest
	(*DeleteKnowledgeResponse)(nil), // 7: cortexdb.v1.DeleteKnowledgeResponse
	(*SearchKnowledgeRequest)(nil),  // 8: cortexdb.v1.SearchKnowledgeRequest
	(*KnowledgeSearchHit)(nil),      // 9: cortexdb.v1.KnowledgeSearchHit
	(*SearchKnowledgeResponse)(nil), // 10: cortexdb.v1.SearchKnowledgeResponse
	nil,                             // 11: cortexdb.v1.KnowledgeRecord.MetadataEntry
	nil,                             // 12: cortexdb.v1.SaveKnowledgeRequest.MetadataEntry
	nil,                             // 13: cortexdb.v1.UpdateKnowledgeRequest.MetadataEntry
	nil,                             // 14: cortexdb.v1.KnowledgeSearchHit.MetadataEntry
	(*timestamppb.Timestamp)(nil),   // 15: google.protobuf.Timestamp
	(*ToolEntityInput)(nil),         // 16: cortexdb.v1.ToolEntityInput
	(*ToolRelationInput)(nil),       // 17: cortexdb.v1.ToolRelationInput
	(*RetrievalPlan)(nil),           // 18: cortexdb.v1.RetrievalPlan
	(*RetrievalDecision)(nil),       // 19: cortexdb.v1.RetrievalDecision
	(*GraphRagChunkResult)(nil),     // 20: cortexdb.v1.GraphRagChunkResult
}
var file_cortexdb_v1_knowledge_proto_depIdxs = []int32{
	11, // 0: cortexdb.v1.KnowledgeRecord.metadata:type_name -> cortexdb.v1.KnowledgeRecord.MetadataEntry
	15, // 1: cortexdb.v1.KnowledgeRecord.created_at:type_name -> google.protobuf.Timestamp
	15, // 2: cortexdb.v1.KnowledgeRecord.updated_at:type_name -> google.protobuf.Timestamp
	12, // 3: cortexdb.v1.SaveKnowledgeRequest.metadata:type_name -> cortexdb.v1.SaveKnowledgeRequest.MetadataEntry
	16, // 4: cortexdb.v1.SaveKnowledgeRequest.entities:type_name -> cortexdb.v1.ToolEntityInput
	17, // 5: cortexdb.v1.SaveKnowledgeRequest.relations:type_name -> cortexdb.v1.ToolRelationInput
	0,  // 6: cortexdb.v1.SaveKnowledgeResponse.knowledge:type_name -> cortexdb.v1.KnowledgeRecord
	13, // 7: cortexdb.v1.UpdateKnowledgeRequest.metadata:type_name -> cortexdb.v1.UpdateKnowledgeRequest.MetadataEntry
	16, // 8: cortexdb.v1.UpdateKnowledgeRequest.entities:type_name -> cortexdb.v1.ToolEntityInput
	17, // 9: cortexdb.v1.UpdateKnowledgeRequest.relations:type_name -> cortexdb.v1.ToolRelationInput
	0,  // 10: cortexdb.v1.GetKnowledgeResponse.knowledge:type_name -> cortexdb.v1.KnowledgeRecord
	18, // 11: cortexdb.v1.SearchKnowledgeRequest.plan:type_name -> cortexdb.v1.RetrievalPlan
	14, // 12: cortexdb.v1.KnowledgeSearchHit.metadata:type_name -> cortexdb.v1.KnowledgeSearchHit.MetadataEntry
	18, // 13: cortexdb.v1.SearchKnowledgeResponse.plan:type_name -> cortexdb.v1.RetrievalPlan
	19, // 14: cortexdb.v1.SearchKnowledgeResponse.decision:type_name -> cortexdb.v1.RetrievalDecision
	9,  // 15: cortexdb.v1.SearchKnowledgeResponse.results:type_name -> cortexdb.v1.KnowledgeSearchHit
	20, // 16: cortexdb.v1.SearchKnowledgeResponse.chunks:type_name -> cortexdb.v1.GraphRagChunkResult
	1,  // 17: cortexdb.v1.KnowledgeService.SaveKnowledge:input_type -> cortexdb.v1.SaveKnowledgeRequest
	3,  // 18: cortexdb.v1.KnowledgeService.UpdateKnowledge:input_type -> cortexdb.v1.UpdateKnowledgeRequest
	4,  // 19: cortexdb.v1.KnowledgeService.GetKnowledge:input_type -> cortexdb.v1.GetKnowledgeRequest
	8,  // 20: cortexdb.v1.KnowledgeService.SearchKnowledge:input_type -> cortexdb.v1.SearchKnowledgeRequest
	6,  // 21: cortexdb.v1.KnowledgeService.DeleteKnowledge:input_type -> cortexdb.v1.DeleteKnowledgeRequest
	2,  // 22: cortexdb.v1.KnowledgeService.SaveKnowledge:output_type -> cortexdb.v1.SaveKnowledgeResponse
	2,  // 23: cortexdb.v1.KnowledgeService.UpdateKnowledge:output_type -> cortexdb.v1.SaveKnowledgeResponse
	5,  // 24: cortexdb.v1.KnowledgeService.GetKnowledge:output_type -> cortexdb.v1.GetKnowledgeResponse
	10, // 25: cortexdb.v1.KnowledgeService.SearchKnowledge:output_type -> cortexdb.v1.SearchKnowledgeResponse
	7,  // 26: cortexdb.v1.KnowledgeService.DeleteKnowledge:output_type -> cortexdb.v1.DeleteKnowledgeResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_cortexdb_v1_knowledge_proto_init() }
func file_cortexdb_v1_knowledge_proto_init() {
	if File_cortexdb_v1_knowledge_proto != nil {
		return
	}
	file_cortexdb_v1_common_proto_init()
	file_cortexdb_v1_knowledge_proto_msgTypes[3].OneofWrappers = []any{}
	file_cortexdb_v1_knowledge_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortexdb_v1_knowledge_proto_rawDesc), len(file_cortexdb_v1_knowledge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cortexdb_v1_knowledge_proto_goTypes,
		DependencyIndexes: file_cortexdb_v1_knowledge_proto_depIdxs,
		MessageInfos:      file_cortexdb_v1_knowledge_proto_msgTypes,
	}.Build()
	File_cortexdb_v1_knowledge_proto = out.File
	file_cortexdb_v1_knowledge_proto_goTypes = nil
	file_cortexdb_v1_knowledge_proto_depIdxs = nil
}
