// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.1
// source: cortexdb/v1/memory.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemoryRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Importance    float64                `protobuf:"fixed64,9,opt,name=importance,proto3" json:"importance,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,10,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemoryRecord) Reset() {
	*x = MemoryRecord{}
	mi := &file_cortexdb_v1_memory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemoryRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemoryRecord) ProtoMessage() {}

func (x *MemoryRecord) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_memory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemoryRecord.ProtoReflect.Descriptor instead.
func (*MemoryRecord) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_memory_proto_rawDescGZIP(), []int{0}
}

func (x *MemoryRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MemoryRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MemoryRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MemoryRecord) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *MemoryRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *MemoryRecord) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *MemoryRecord) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *MemoryRecord) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *MemoryRecord) GetImportance() float64 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *MemoryRecord) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *MemoryRecord) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *MemoryRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SaveMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Namespace     string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Role          string                 `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,7,opt,name=content,proto3" json:"content,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,8,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Importance    float64                `protobuf:"fixed64,9,opt,name=importance,proto3" json:"importance,omitempty"`
	TtlSeconds    int32                  `protobuf:"varint,10,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMemoryRequest) Reset() {
	*x = SaveMemoryRequest{}
	mi := &file_cortexdb_v1_memory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMemoryRequest) ProtoMessage() {}

func (x *SaveMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_memory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMemoryRequest.ProtoReflect.Descriptor instead.
func (*SaveMemoryRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_memory_proto_rawDescGZIP(), []int{1}
}

func (x *SaveMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *SaveMemoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SaveMemoryRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SaveMemoryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SaveMemoryRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *SaveMemoryRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SaveMemoryRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SaveMemoryRequest) GetImportance() float64 {
	if x != nil {
		return x.Importance
	}
	return 0
}

func (x *SaveMemoryRequest) GetTtlSeconds() int32 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type SaveMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *MemoryRecord          `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMemoryResponse) Reset() {
	*x = SaveMemoryResponse{}
	mi := &file_cortexdb_v1_memory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMemoryResponse) ProtoMessage() {}

func (x *SaveMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_memory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMemoryResponse.ProtoReflect.Descriptor instead.
func (*SaveMemoryResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_memory_proto_rawDescGZIP(), []int{2}
}

func (x *SaveMemoryResponse) GetMemory() *MemoryRecord {
	if x != nil {
		return x.Memory
	}
	return nil
}

type UpdateMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Content       *string                `protobuf:"bytes,2,opt,name=content,proto3,oneof" json:"content,omitempty"`
	Metadata      *structpb.Struct       `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Importance    *float64               `protobuf:"fixed64,4,opt,name=importance,proto3,oneof" json:"importance,omitempty"`
	TtlSeconds    *int32                 `protobuf:"varint,5,opt,name=ttl_seconds,json=ttlSeconds,proto3,oneof" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMemoryRequest) Reset() {
	*x = UpdateMemoryRequest{}
	mi := &file_cortexdb_v1_memory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMemoryRequest) ProtoMessage() {}

func (x *UpdateMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_memory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMemoryRequest.ProtoReflect.Descriptor instead.
func (*UpdateMemoryRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_memory_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *UpdateMemoryRequest) GetContent() string {
	if x != nil && x.Content != nil {
		return *x.Content
	}
	return ""
}

func (x *UpdateMemoryRequest) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateMemoryRequest) GetImportance() float64 {
	if x != nil && x.Importance != nil {
		return *x.Importance
	}
	return 0
}

func (x *UpdateMemoryRequest) GetTtlSeconds() int32 {
	if x != nil && x.TtlSeconds != nil {
		return *x.TtlSeconds
	}
	return 0
}

type GetMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryRequest) Reset() {
	*x = GetMemoryRequest{}
	mi := &file_cortexdb_v1_memory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryRequest) ProtoMessage() {}

func (x *GetMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_memory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryRequest.ProtoReflect.Descriptor instead.
func (*GetMemoryRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_memory_proto_rawDescGZIP(), []int{4}
}

func (x *GetMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

type GetMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *MemoryRecord          `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemoryResponse) Reset() {
	*x = GetMemoryResponse{}
	mi := &file_cortexdb_v1_memory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemoryResponse) ProtoMessage() {}

func (x *GetMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_memory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemoryResponse.ProtoReflect.Descriptor instead.
func (*GetMemoryResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_memory_proto_rawDescGZIP(), []int{5}
}

func (x *GetMemoryResponse) GetMemory() *MemoryRecord {
	if x != nil {
		return x.Memory
	}
	return nil
}

type DeleteMemoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryRequest) Reset() {
	*x = DeleteMemoryRequest{}
	mi := &file_cortexdb_v1_memory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryRequest) ProtoMessage() {}

func (x *DeleteMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_memory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteMemoryRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_memory_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteMemoryRequest) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

type DeleteMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemoryId      string                 `protobuf:"bytes,1,opt,name=memory_id,json=memoryId,proto3" json:"memory_id,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMemoryResponse) Reset() {
	*x = DeleteMemoryResponse{}
	mi := &file_cortexdb_v1_memory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMemoryResponse) ProtoMessage() {}

func (x *DeleteMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_memory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMemoryResponse.ProtoReflect.Descriptor instead.
func (*DeleteMemoryResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_memory_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMemoryResponse) GetMemoryId() string {
	if x != nil {
		return x.MemoryId
	}
	return ""
}

func (x *DeleteMemoryResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type SearchMemoryRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Query            string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	UserId           string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SessionId        string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Scope            string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	Namespace        string                 `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	TopK             int32                  `protobuf:"varint,6,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	Keywords         []string               `protobuf:"bytes,7,rep,name=keywords,proto3" json:"keywords,omitempty"`
	AlternateQueries []string               `protobuf:"bytes,8,rep,name=alternate_queries,json=alternateQueries,proto3" json:"alternate_queries,omitempty"`
	RetrievalMode    string                 `protobuf:"bytes,9,opt,name=retrieval_mode,json=retrievalMode,proto3" json:"retrieval_mode,omitempty"`
	Plan             *RetrievalPlan         `protobuf:"bytes,10,opt,name=plan,proto3,oneof" json:"plan,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchMemoryRequest) Reset() {
	*x = SearchMemoryRequest{}
	mi := &file_cortexdb_v1_memory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoryRequest) ProtoMessage() {}

func (x *SearchMemoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_memory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoryRequest.ProtoReflect.Descriptor instead.
func (*SearchMemoryRequest) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_memory_proto_rawDescGZIP(), []int{8}
}

func (x *SearchMemoryRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMemoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchMemoryRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SearchMemoryRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *SearchMemoryRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *SearchMemoryRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchMemoryRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *SearchMemoryRequest) GetAlternateQueries() []string {
	if x != nil {
		return x.AlternateQueries
	}
	return nil
}

func (x *SearchMemoryRequest) GetRetrievalMode() string {
	if x != nil {
		return x.RetrievalMode
	}
	return ""
}

func (x *SearchMemoryRequest) GetPlan() *RetrievalPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type MemorySearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Memory        *MemoryRecord          `protobuf:"bytes,1,opt,name=memory,proto3" json:"memory,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemorySearchHit) Reset() {
	*x = MemorySearchHit{}
	mi := &file_cortexdb_v1_memory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemorySearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemorySearchHit) ProtoMessage() {}

func (x *MemorySearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_memory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemorySearchHit.ProtoReflect.Descriptor instead.
func (*MemorySearchHit) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_memory_proto_rawDescGZIP(), []int{9}
}

func (x *MemorySearchHit) GetMemory() *MemoryRecord {
	if x != nil {
		return x.Memory
	}
	return nil
}

func (x *MemorySearchHit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type SearchMemoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Plan          *RetrievalPlan         `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	Decision      *RetrievalDecision     `protobuf:"bytes,3,opt,name=decision,proto3" json:"decision,omitempty"`
	Results       []*MemorySearchHit     `protobuf:"bytes,4,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchMemoryResponse) Reset() {
	*x = SearchMemoryResponse{}
	mi := &file_cortexdb_v1_memory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchMemoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchMemoryResponse) ProtoMessage() {}

func (x *SearchMemoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_cortexdb_v1_memory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchMemoryResponse.ProtoReflect.Descriptor instead.
func (*SearchMemoryResponse) Descriptor() ([]byte, []int) {
	return file_cortexdb_v1_memory_proto_rawDescGZIP(), []int{10}
}

func (x *SearchMemoryResponse) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchMemoryResponse) GetPlan() *RetrievalPlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *SearchMemoryResponse) GetDecision() *RetrievalDecision {
	if x != nil {
		return x.Decision
	}
	return nil
}

func (x *SearchMemoryResponse) GetResults() []*MemorySearchHit {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_cortexdb_v1_memory_proto protoreflect.FileDescriptor

const file_cortexdb_v1_memory_proto_rawDesc = "" +
	"\n" +
	"\x18cortexdb/v1/memory.proto\x12\vcortexdb.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x18cortexdb/v1/common.proto\"\xa4\x03\n" +
	"\fMemoryRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1e\n" +
	"\n" +
	"importance\x18\t \x01(\x01R\n" +
	"importance\x12\x1f\n" +
	"\vttl_seconds\x18\n" +
	" \x01(\x05R\n" +
	"ttlSeconds\x129\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xc0\x02\n" +
	"\x11SaveMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04role\x18\x06 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\a \x01(\tR\acontent\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12\x1e\n" +
	"\n" +
	"importance\x18\t \x01(\x01R\n" +
	"importance\x12\x1f\n" +
	"\vttl_seconds\x18\n" +
	" \x01(\x05R\n" +
	"ttlSeconds\"G\n" +
	"\x12SaveMemoryResponse\x121\n" +
	"\x06memory\x18\x01 \x01(\v2\x19.cortexdb.v1.MemoryRecordR\x06memory\"\xfc\x01\n" +
	"\x13UpdateMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x1d\n" +
	"\acontent\x18\x02 \x01(\tH\x00R\acontent\x88\x01\x01\x123\n" +
	"\bmetadata\x18\x03 \x01(\v2\x17.google.protobuf.StructR\bmetadata\x12#\n" +
	"\n" +
	"importance\x18\x04 \x01(\x01H\x01R\n" +
	"importance\x88\x01\x01\x12$\n" +
	"\vttl_seconds\x18\x05 \x01(\x05H\x02R\n" +
	"ttlSeconds\x88\x01\x01B\n" +
	"\n" +
	"\b_contentB\r\n" +
	"\v_importanceB\x0e\n" +
	"\f_ttl_seconds\"/\n" +
	"\x10GetMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\"F\n" +
	"\x11GetMemoryResponse\x121\n" +
	"\x06memory\x18\x01 \x01(\v2\x19.cortexdb.v1.MemoryRecordR\x06memory\"2\n" +
	"\x13DeleteMemoryRequest\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\"M\n" +
	"\x14DeleteMemoryResponse\x12\x1b\n" +
	"\tmemory_id\x18\x01 \x01(\tR\bmemoryId\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\"\xda\x02\n" +
	"\x13SearchMemoryRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x1c\n" +
	"\tnamespace\x18\x05 \x01(\tR\tnamespace\x12\x13\n" +
	"\x05top_k\x18\x06 \x01(\x05R\x04topK\x12\x1a\n" +
	"\bkeywords\x18\a \x03(\tR\bkeywords\x12+\n" +
	"\x11alternate_queries\x18\b \x03(\tR\x10alternateQueries\x12%\n" +
	"\x0eretrieval_mode\x18\t \x01(\tR\rretrievalMode\x123\n" +
	"\x04plan\x18\n" +
	" \x01(\v2\x1a.cortexdb.v1.RetrievalPlanH\x00R\x04plan\x88\x01\x01B\a\n" +
	"\x05_plan\"Z\n" +
	"\x0fMemorySearchHit\x121\n" +
	"\x06memory\x18\x01 \x01(\v2\x19.cortexdb.v1.MemoryRecordR\x06memory\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"\xd0\x01\n" +
	"\x14SearchMemoryResponse\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12.\n" +
	"\x04plan\x18\x02 \x01(\v2\x1a.cortexdb.v1.RetrievalPlanR\x04plan\x12:\n" +
	"\bdecision\x18\x03 \x01(\v2\x1e.cortexdb.v1.RetrievalDecisionR\bdecision\x126\n" +
	"\aresults\x18\x04 \x03(\v2\x1c.cortexdb.v1.MemorySearchHitR\aresults2\xa7\x03\n" +
	"\rMemoryService\x12M\n" +
	"\n" +
	"SaveMemory\x12\x1e.cortexdb.v1.SaveMemoryRequest\x1a\x1f.cortexdb.v1.SaveMemoryResponse\x12Q\n" +
	"\fUpdateMemory\x12 .cortexdb.v1.UpdateMemoryRequest\x1a\x1f.cortexdb.v1.SaveMemoryResponse\x12J\n" +
	"\tGetMemory\x12\x1d.cortexdb.v1.GetMemoryRequest\x1a\x1e.cortexdb.v1.GetMemoryResponse\x12S\n" +
	"\fSearchMemory\x12 .cortexdb.v1.SearchMemoryRequest\x1a!.cortexdb.v1.SearchMemoryResponse\x12S\n" +
	"\fDeleteMemory\x12 .cortexdb.v1.DeleteMemoryRequest\x1a!.cortexdb.v1.DeleteMemoryResponseB4Z2github.com/liliang-cn/cortexdb/v2/pkg/rpc/v1;rpcv1b\x06proto3"

var (
	file_cortexdb_v1_memory_proto_rawDescOnce sync.Once
	file_cortexdb_v1_memory_proto_rawDescData []byte
)

func file_cortexdb_v1_memory_proto_rawDescGZIP() []byte {
	file_cortexdb_v1_memory_proto_rawDescOnce.Do(func() {
		file_cortexdb_v1_memory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_cortexdb_v1_memory_proto_rawDesc), len(file_cortexdb_v1_memory_proto_rawDesc)))
	})
	return file_cortexdb_v1_memory_proto_rawDescData
}

var file_cortexdb_v1_memory_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_cortexdb_v1_memory_proto_goTypes = []any{
	(*MemoryRecord)(nil),          // 0: cortexdb.v1.MemoryRecord
	(*SaveMemoryRequest)(nil),     // 1: cortexdb.v1.SaveMemoryRequest
	(*SaveMemoryResponse)(nil),    // 2: cortexdb.v1.SaveMemoryResponse
	(*UpdateMemoryRequest)(nil),   // 3: cortexdb.v1.UpdateMemoryRequest
	(*GetMemoryRequest)(nil),      // 4: cortexdb.v1.GetMemoryRequest
	(*GetMemoryResponse)(nil),     // 5: cortexdb.v1.GetMemoryResponse
	(*DeleteMemoryRequest)(nil),   // 6: cortexdb.v1.DeleteMemoryRequest
	(*DeleteMemoryResponse)(nil),  // 7: cortexdb.v1.DeleteMemoryResponse
	(*SearchMemoryRequest)(nil),   // 8: cortexdb.v1.SearchMemoryRequest
	(*MemorySearchHit)(nil),       // 9: cortexdb.v1.MemorySearchHit
	(*SearchMemoryResponse)(nil),  // 10: cortexdb.v1.SearchMemoryResponse
	(*structpb.Struct)(nil),       // 11: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*RetrievalPlan)(nil),         // 13: cortexdb.v1.RetrievalPlan
	(*RetrievalDecision)(nil),     // 14: cortexdb.v1.RetrievalDecision
}
var file_cortexdb_v1_memory_proto_depIdxs = []int32{
	11, // 0: cortexdb.v1.MemoryRecord.metadata:type_name -> google.protobuf.Struct
	12, // 1: cortexdb.v1.MemoryRecord.expires_at:type_name -> google.protobuf.Timestamp
	12, // 2: cortexdb.v1.MemoryRecord.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: cortexdb.v1.SaveMemoryRequest.metadata:type_name -> google.protobuf.Struct
	0,  // 4: cortexdb.v1.SaveMemoryResponse.memory:type_name -> cortexdb.v1.MemoryRecord
	11, // 5: cortexdb.v1.UpdateMemoryRequest.metadata:type_name -> google.protobuf.Struct
	0,  // 6: cortexdb.v1.GetMemoryResponse.memory:type_name -> cortexdb.v1.MemoryRecord
	13, // 7: cortexdb.v1.SearchMemoryRequest.plan:type_name -> cortexdb.v1.RetrievalPlan
	0,  // 8: cortexdb.v1.MemorySearchHit.memory:type_name -> cortexdb.v1.MemoryRecord
	13, // 9: cortexdb.v1.SearchMemoryResponse.plan:type_name -> cortexdb.v1.RetrievalPlan
	14, // 10: cortexdb.v1.SearchMemoryResponse.decision:type_name -> cortexdb.v1.RetrievalDecision
	9,  // 11: cortexdb.v1.SearchMemoryResponse.results:type_name -> cortexdb.v1.MemorySearchHit
	1,  // 12: cortexdb.v1.MemoryService.SaveMemory:input_type -> cortexdb.v1.SaveMemoryRequest
	3,  // 13: cortexdb.v1.MemoryService.UpdateMemory:input_type -> cortexdb.v1.UpdateMemoryRequest
	4,  // 14: cortexdb.v1.MemoryService.GetMemory:input_type -> cortexdb.v1.GetMemoryRequest
	8,  // 15: cortexdb.v1.MemoryService.SearchMemory:input_type -> cortexdb.v1.SearchMemoryRequest
	6,  // 16: cortexdb.v1.MemoryService.DeleteMemory:input_type -> cortexdb.v1.DeleteMemoryRequest
	2,  // 17: cortexdb.v1.MemoryService.SaveMemory:output_type -> cortexdb.v1.SaveMemoryResponse
	2,  // 18: cortexdb.v1.MemoryService.UpdateMemory:output_type -> cortexdb.v1.SaveMemoryResponse
	5,  // 19: cortexdb.v1.MemoryService.GetMemory:output_type -> cortexdb.v1.GetMemoryResponse
	10, // 20: cortexdb.v1.MemoryService.SearchMemory:output_type -> cortexdb.v1.SearchMemoryResponse
	7,  // 21: cortexdb.v1.MemoryService.DeleteMemory:output_type -> cortexdb.v1.DeleteMemoryResponse
	17, // [17:22] is the sub-list for method output_type
	12, // [12:17] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cortexdb_v1_memory_proto_init() }
func file_cortexdb_v1_memory_proto_init() {
	if File_cortexdb_v1_memory_proto != nil {
		return
	}
	file_cortexdb_v1_common_proto_init()
	file_cortexdb_v1_memory_proto_msgTypes[3].OneofWrappers = []any{}
	file_cortexdb_v1_memory_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_cortexdb_v1_memory_proto_rawDesc), len(file_cortexdb_v1_memory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cortexdb_v1_memory_proto_goTypes,
		DependencyIndexes: file_cortexdb_v1_memory_proto_depIdxs,
		MessageInfos:      file_cortexdb_v1_memory_proto_msgTypes,
	}.Build()
	File_cortexdb_v1_memory_proto = out.File
	file_cortexdb_v1_memory_proto_goTypes = nil
	file_cortexdb_v1_memory_proto_depIdxs = nil
}
