package core

import (
	"strings"
	"unicode"
)

// CJK lexical search needs a different index than English.
//
// FTS5's default unicode61 tokenizer splits on non-alphanumeric characters. Chinese,
// Japanese and Korean text has no spaces, so a whole run of CJK characters becomes a
// single token and no realistic query can ever match it — lexical search silently
// returns zero rows for a CJK corpus while English works fine. The trigram tokenizer
// indexes substrings, which does match CJK, but it is a poor word index for
// space-separated languages: BM25 over trigrams reorders English results and matches
// fragments across word boundaries.
//
// So both indexes exist, and the query picks one by script. Anything containing CJK
// goes to the trigram companion; everything else keeps the word index it always used.

// ContainsCJK reports whether the text holds any Han, Hiragana, Katakana or Hangul
// character — the scripts whose text is not space-delimited.
func ContainsCJK(text string) bool {
	for _, r := range text {
		if unicode.Is(unicode.Han, r) ||
			unicode.Is(unicode.Hiragana, r) ||
			unicode.Is(unicode.Katakana, r) ||
			unicode.Is(unicode.Hangul, r) {
			return true
		}
	}
	return false
}

// CJKAwareIndex returns the FTS index to MATCH against for this query: the trigram
// companion for CJK text, otherwise the unicode61 word index.
//
// Note the trigram floor: a query of one or two CJK characters produces no trigrams and
// therefore matches nothing. Callers that may be handed such a query should route it past
// MATCH entirely — see BelowTrigramFloor.
func CJKAwareIndex(wordIndex, query string) string {
	if ContainsCJK(query) {
		return wordIndex + "_cjk"
	}
	return wordIndex
}

// TrigramFloor is the shortest run the trigram tokenizer can make a token from.
const TrigramFloor = 3

// BelowTrigramFloor reports whether a CJK query is too short for the trigram index to match it.
//
// Two characters is a whole word in Chinese, and a great many of the words a lesson is about are
// exactly two: 乘法, 除法, 分数, 面积, 周长. MATCH against a trigram index returns nothing for all
// of them, so a caller who does not notice reports "no results" for a term the corpus is full of.
// Falling back to a substring scan is slower than an index, but it is the difference between an
// answer and a silent zero.
func BelowTrigramFloor(query string) bool {
	trimmed := strings.TrimSpace(query)
	return ContainsCJK(trimmed) && len([]rune(trimmed)) < TrigramFloor
}

// SubstringPattern turns a literal into a LIKE pattern matching it anywhere, escaping the
// wildcards LIKE would otherwise read as syntax. Use it with ESCAPE '\'.
func SubstringPattern(literal string) string {
	var pattern strings.Builder
	pattern.WriteByte('%')
	for _, r := range literal {
		if r == '%' || r == '_' || r == '\\' {
			pattern.WriteByte('\\')
		}
		pattern.WriteRune(r)
	}
	pattern.WriteByte('%')
	return pattern.String()
}

// MatchExpression makes a query safe to hand to FTS5 MATCH, rewriting it only
// when the raw text would be read as syntax rather than as words.
//
// FTS5's MATCH argument is a query language, not a string: ":" filters a
// column, "*" is a prefix, parentheses group, and a stray "-" or quote is a
// parse error. A query typed by a person — or generated by a model — is none of
// those things, so ordinary technical vocabulary becomes a syntax error:
// "on-drbd-demote-failure" fails with `no such column: drbd`, and so does every
// other hyphenated identifier — al-extents, peer-disk, no-quorum, drbd-reactor.
// In a hybrid search the failure is silent, because the vector arm still
// answers; the keyword arm simply stops contributing, precisely for the exact
// technical terms it is best at.
//
// A query of plain words is returned UNCHANGED. That is the important half:
// those queries already work, FTS5's own operators (AND, OR, NOT, NEAR) still
// mean what they meant, and the retrieval evals that pin lexical quality keep
// measuring the same thing. Rewriting them "harmlessly" is not harmless —
// quoting every token cost recall@10 0.85 → 0.27 on cortexdb-retrieval-v2.
//
// Only when the query carries characters FTS5 would interpret is it rebuilt
// from its indexable runs, each quoted so nothing can be read as an operator.
// The result is empty when there is nothing indexable left; callers must skip
// the keyword arm rather than pass "" to MATCH, which is a syntax error of its
// own.
func MatchExpression(query string) string {
	terms := indexableTerms(query)
	if len(terms) == 0 {
		// Whitespace or punctuation only. There is nothing to search for, and
		// MATCH '   ' is a syntax error in its own right.
		return ""
	}
	if !needsEscaping(query) {
		return query
	}
	var b strings.Builder
	for _, term := range terms {
		if b.Len() > 0 {
			b.WriteByte(' ')
		}
		b.WriteByte('"')
		b.WriteString(term)
		b.WriteByte('"')
	}
	return b.String()
}

// needsEscaping reports whether a query contains anything FTS5 reads as syntax.
// Letters, digits and whitespace are inert; everything else is not.
func needsEscaping(query string) bool {
	for _, r := range query {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || unicode.IsSpace(r) {
			continue
		}
		return true
	}
	return false
}

// indexableTerms splits a query into the runs of letters and digits FTS5 would
// tokenize, discarding the punctuation it would otherwise read as syntax.
//
// CJK runs are kept whole: the trigram companion index tokenizes them itself,
// and splitting per rune would search for individual characters.
func indexableTerms(query string) []string {
	var terms []string
	var cur strings.Builder
	flush := func() {
		if cur.Len() > 0 {
			terms = append(terms, cur.String())
			cur.Reset()
		}
	}
	for _, r := range query {
		if unicode.IsLetter(r) || unicode.IsDigit(r) {
			cur.WriteRune(r)
			continue
		}
		flush()
	}
	flush()
	return terms
}
